### ISSUE TITLE
How to set different colors for different log levels

### ISSUE THREAD

**Issue by KublaikhanGeek** [log4cplus/log4cplus#111]

**Comment by wilx** [comment]
At this point this is built-in only for Windows console with [`Win32ConsoleAppender`](https://github.com/log4cplus/log4cplus/blob/master/include/log4cplus/win32consoleappender.h) and you have to use multiple appenders each set to specific colour and with filter to filter out other log levels.

**Comment by KublaikhanGeek** [comment]
Thanks for your answer, but do u know some simple ways to get it

**Comment by wilx** [comment]
> Thanks for your answer, but do u know some simple ways to get

There is no other way at the moment, let a lone simple.
