### ISSUE TITLE
how build a server for appender

### ISSUE THREAD

**Issue by hlee13** [log4cplus/log4cplus#112]
how build a server for appender, like SocketAppender has a test cxx, (tests/socket_test/main.cxx )

Log4jUdpAppender can?
AsyncAppender can ?
SysLogAppender can? 

log4cplus provides ?

**Comment by wilx** [comment]
`SocketAppender` receiver is source is in the [`loggingserver.cxx`](https://github.com/log4cplus/log4cplus/blob/master/simpleserver/loggingserver.cxx).

`Log4jUdpAppender` sends the events using UDP to whoever wants to receive them. The other end can be [Chainsaw GUI](https://logging.apache.org/chainsaw/) or any other compatible receiver like [Log2Console](https://log2console.codeplex.com/)

`AsyncAppender` is there to outsource possibly time consuming appending to separate thread. It is relevant on older branches than master. On master, there is a thread pool that does that same for all appenders automatically.

`SysLogAppender` can be used to append against any syslog server. Initially, it was UDP only, newer versions support TCP as well.

**Comment by hlee13** [comment]
SocketAppender model has memory leak under high press. It's so ungly, could it will be fixed? 
Or give a tiny code analysis.

**Comment by wilx** [comment]
@hlee13 I am not aware of any leaks. You will have to specify it a little bit more.

**Comment by hlee13** [comment]
briefly, i use SocketAppender as Client Appender, and logginserver.cxx as server.
![image](https://cloud.githubusercontent.com/assets/4981187/10881806/e23c0848-81a0-11e5-9496-ec55ba6da792.png)

pic is server process by top command .

**Comment by hlee13** [comment]
when logger in down, SocketAppender will reopen socket , is that socket release, fd leaks is abvirous.
![image](https://cloud.githubusercontent.com/assets/4981187/10881914/b517e732-81a1-11e5-88dd-816f6d1b14d1.png)

**Comment by wilx** [comment]
@hlee13  OK, that looks like a socket handle leak. What version are you using?

**Comment by hlee13** [comment]
version 1.1.2 release
perhaps memory leaks is non-relative with fd leaks, yet that is a problem.
I care about memory leaks as well as fd.

**Comment by wilx** [comment]
@hlee13 Well, I do not immediately see anything wrong. Are you able to use something like Valgrind to identify the leak? Also, can you check with master branch?

**Comment by hlee13** [comment]
ok, maybe  that is only short term solution

**Comment by wilx** [comment]
@hlee13 You said initially, it leaks under high pressure. What kind of pressure is it? Is it possible that, e.g., it is related to connection errors or disconnections?

**Comment by hlee13** [comment]
yes, It is related to reconnection. 
Both client and server have memory leak at a long term running. fd leaks is obvious.

**Comment by wilx** [comment]
@hlee13 TBH, I do not see the leak. I have used `performance_test` against the `loggingserver` and I do not see a leak of either FDs or memory. Maybe I am not producing the correct failure mode that triggers it. I do not know.

Which brings me to this: Are you sure your application is not dynamically creating too many loggers with `SocketAppender`s? The number of loggers should be proportional to code complexity and/or number of modules of the code. E.g., for, say, network server application, you should not be creating separate logger for each client but you should use [`NDCContextCreator`](https://github.com/log4cplus/log4cplus/blob/1.1.x/include/log4cplus/ndc.h#L319) to create NDC context with client identification/information.

**Comment by hlee13** [comment]
can you provide me loggingserver code, or loggingserver.cxx is same as https://github.com/log4cplus/log4cplus/blob/master/simpleserver/loggingserver.cxx ?

I found line 83 has new operator.

**Comment by wilx** [comment]
@hlee13 OK, I see the issue on the line now. I actually did not see it initially, because I have modified the loggingserver code to make testing easier.

**Comment by hlee13** [comment]
how your testing easier code deal with the new operator in line 83

**Comment by wilx** [comment]
@hlee13 The `loggingserver` leak should be fixed now on all branches since 1.1.x. Do you see any other leak?

**Comment by hlee13** [comment]
There are no up date.

**Comment by wilx** [comment]
> There are no up date.

I forgot to merge back the changes to log4cplus/log4cplus repository. It is done now. I hope this is why you saw no updates.

**Comment by wilx** [comment]
I think this should be fixed now. If you think there are more problems, please either reopen this issue or create a new one.
