### ISSUE TITLE
Option to disable CPack

### ISSUE THREAD

**Issue by theirix** [log4cplus/log4cplus#113]
It is useful to have an option to disable CPack (like ``LOG4CPLUS_BUILD_TESTING``). Complex cmake builds with log4cplus as an external project cannot be well packaged with dependencies that deal with CPack.

**Comment by wilx** [comment]
I have tried the following change but all it did was create less informed `CPackConfig.cmake` file:

```{.diff}
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -70,6 +70,8 @@ option(ENABLE_SYMBOLS_VISIBILITY
   "Enable compiler and platform specific options for symbols visibility"
   ON)
 
+option(LOG4CPLUS_ENABLE_CPACK "Enable CPack packaging" ON)
+
 option(WITH_UNIT_TESTS "Enable unit tests" ON)
 if (WITH_UNIT_TESTS)
   set (LOG4CPLUS_WITH_UNIT_TESTS 1)
@@ -152,4 +154,6 @@ if (LOG4CPLUS_QT5)
   add_subdirectory (qt5debugappender)
 endif (LOG4CPLUS_QT5)
 
-include(Log4CPlusCPack.cmake)
+if (LOG4CPLUS_ENABLE_CPACK)
+  include(Log4CPlusCPack.cmake)
+endif (LOG4CPLUS_ENABLE_CPACK)
```

Do you have any suggestion on how to do what you want? Or a patch even? :)

**Comment by theirix** [comment]
It is exactly the patch I had wrote in a local repo. But after a few thougths I discovered that CPack disabling was not a solution for my problem so this issue is not important for me now:)

**Comment by wilx** [comment]
OK. I am closing this as invalid then.
