### ISSUE TITLE
iOS cmake issue

### ISSUE THREAD

**Issue by Cross22** [log4cplus/log4cplus#118]
Not sure if this is a problem with the installed cmake 3.2.1 version, or some pathing problem. After cloning the repo I did this:
$ cd iOS
$ ./scripts/cmake_ios_armv7.sh 
CMake Error: The source directory "/Users/grubm012/dev/log4cplus/iOS/build_armv7" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
./scripts/cmake_ios_armv7.sh: line 18: /Users/grubm012/dev/log4cplus/iOS/scripts/../..: is a directory

**Comment by Cross22** [comment]
Oh. Turns out there is a backslash missing in the cmake_ios_armv7.sh script

**Comment by wilx** [comment]
I see it.

**Comment by wilx** [comment]
Fixed by 0134f30.
