### ISSUE TITLE
Incorrect behavior in DailyRollingFileAppender::close()

### ISSUE THREAD

**Issue by amorozov** [log4cplus/log4cplus#120]
Currently `DailyRollingFileAppender::close()` uncoditionally rolls over its files. This leads to a double rollover when used in a typical server application which uses `fork()` to put itself to background: first time the class rolls over when a parent process exits (usually quite soon after forking the child service process) and then when child (== actual server process) exits.

What's worth the actual logging is performed to a "backup log file", while the "regular log file" remains empty (the parent process moves the regular log file to backup on its exit, and the child process doesn't detect this).

A possible workaround/solution would be not to roll logfiles upon `close()` or maybe selectively skip rollover stage when such a use pattern is active.

**Comment by wilx** [comment]
This roll on close behaviour is historical. I am not sure if it is necessary, though. `DailyRollingFileAppender` is a strange beast. I guess what we can do is to and a property that would allow you to turn this roll-over on close off.

**Comment by amorozov** [comment]
Would you mind if I add `RotateOnShutdown` property to `DailyRollingFileAppender` and probably `TimeBasedRollingFileAppender` ?

**Comment by wilx** [comment]
Not at all. Just keep the default as is the current historical behaviour.

**Comment by wilx** [comment]
Also, unless `RotateOnShutdown` already exists elsewhere (log4j, log4net, etc.) let's use a different name: `RollOnClose`.

**Comment by amorozov** [comment]
I've created a pull request for this issue, as well as two other small pull request and a merge for your convenience.

**Comment by amorozov** [comment]
closed as #123
