### ISSUE TITLE
missing -fPIC on 1.2.x branch for Autotools

### ISSUE THREAD

**Issue by dmigous** [log4cplus/log4cplus#130]
as result when building shared lib libfoo.so, that includes liblog4cplus.a results in error:

```
log4cplus/lib/liblog4cplus.a(liblog4cplus_la-consoleappender.o): relocation R_X86_64_32 against `_ZTTN9log4cplus15ConsoleAppenderE' can not be used when making a shared object; recompile with -fPIC
/vagrant/target/native/debug/log4cplus/lib/liblog4cplus.a: error adding symbols: Bad value
```

**Comment by wilx** [comment]
This should not be necessary. The `configure.ac` script does use `pic-only` in `LT_INIT([win32-dll disable-static pic-only])`. I have just checked, it works if I just configure with `--disable-shared --with-pic`.

**Comment by dmigous** [comment]
agree, my bad.
Thanks for help
