### ISSUE TITLE
build failed vs2015

### ISSUE THREAD

**Issue by yunlhowk** [log4cplus/log4cplus#138]
used "log4cplus-master" "msvc14" log4cplus.sln building failed ,error info:

“ThreadPool.h”: No such file or directory	log4cplus	log4cplus-master\src\global-init.cxx
 “catch.hpp”: No such file or directory	log4cplus	log4cplus-master\src\mdc.cxx

**Comment by wilx** [comment]
These are Git submodules. You need to run Git clone with `--recursive` option.
