### ISSUE TITLE
Stable release versioning question

### ISSUE THREAD

**Issue by thozza** [log4cplus/log4cplus#139]
Hello.

I would like to ask what are the plans WRT the versions of log4cplus that are being released? The latest really stable version released seems to be 1.1.2, which is quite old. Since then, there have been only RC versions (of 1.1.3 and 1.2.0).

In Fedora, we use the the https://release-monitoring.org service to get notified when new version of the project is released. The service however detects only stable version of the project, because this is usually what we want to include in the distribution. So this means the latest stable version detected is 1.1.2 (https://release-monitoring.org/project/1835/) which is from 2013.

So my question is, if the project considers the RC releases as final and stable? Are you at all planning to release final version (not RC) of the newer versions (1.1.3, 1.2.0) of log4cplus?

PS: I'm not sure which place is considered as official, where the project lives. Is if GitHub or sourceforge?
(The discussion on the release-monitoring project page if you are interested: https://github.com/fedora-infra/anitya/issues/251)

Thank you

**Comment by wilx** [comment]
I have released log4cplus 1.2.0. It should be mostly source compatible with the previous release.

> PS: I'm not sure which place is considered as official, where the project lives. Is if GitHub or sourceforge?

Well, main is the SourceForge site. I still host docs, wiki and files there. I use GitHub for the Git repository and the functionality that allows people to contribute easier. I accept bug reports from both.
