### ISSUE TITLE
failed link to log4cplus library built using vs2013 and original CMakeLists int tar ball

### ISSUE THREAD

**Issue by cppbitman** [log4cplus/log4cplus#143]
Hello,
I  am building an application which links to log4cplus library.
The library project is generated using CMake with CMakeList file in the root directory of tar ball and built with VS2013 msbuild.

Build result reports unresolved external symbol link errors, which cannot find symbols `log4cplus::Logger::getInstance` and `log4cplus::FileAppender::FileAppender`.

Should I do some modification to the CMakeList file to realize my way building application?
log4cplus version is 1.2.0.

Can anybody help me ? Thanks a lot.

**Comment by wilx** [comment]
Is it possible that you are trying to link with non-UNICODE build of log4cplus while your application is being compiled with UNICODE defined.

**Comment by cppbitman** [comment]
I've solved my problem by turning off the UNICODE in CMakeList file.
Thanks.
