### ISSUE TITLE
Question regarding configuration of FileAppender and Appender in general

### ISSUE THREAD

**Issue by kaufManu** [log4cplus/log4cplus#147]
Hi,

While using log4cplus, I came across the following two questions that might rather be of conceptual nature:

- Is it intended that a file is only written to by exactly one FileAppender? Technically, it is possible that I specify the same filename in two different FileAppenders. In the `append` method of a FileAppender the output stream is only flushed if `UseLockFile` or `ImmediateFlush` is true and also `formatAndAppend` does not perform a flush by default. So, I guess that using the same file from two different FileAppenders is undefined behavior (if `immediateFlush` is not set). Could you may be comment on that?

- I've noticed that for logging events that are propagated to ancestors, the logging level is ignored. E.g. if I set the root logger to level `INFO` and attach a console appender to it and issue a `DEBUG` event to a logger `some.logger` whose level is set to `DEBUG`, the root logger will still print this event to the console. I've read several posts on Stackoverflow that confirm this, but only for log4j, for which this is actually the expected behavior. I currently work around this by setting the threshold level of the respective appender to some value (e.g. in the above example I would set the threshold level of the console appender attached to root to `INFO`). However, this is easily forgotten. I just wanted to know if you could comment on that as well and may be have a recommondation how this should/could be treated other than with the threshold level?

Thanks a lot in advance!

**Comment by wilx** [comment]
If you create multiple file appenders targeting the same files, you are going to run into some issues. You have identified one, that is the flushing issue. In case of rolling appenders, there is also an issue with who does the rolling and how to synchronize it. In newer log4cplus, it is possible to specify `UseLockFile` property and the appender will use file locking to synchronize appending to file and also rolling multiple files in rolling appenders. The flushing is silently enabled, if you use the `UseLockFile` property. So, it is best to use single appender in a process per file.

---

The log level threshold filtering is done at two points,

  1. at the point of logging, logger is checked for threshold, if one is missing, the threshold is searched for by following path towards root logger
  2. in appender

Yes, the scenario that you are describing can happen. You are right that you have to be careful how you set up your logging properties / hierarchy. Log level threshold on the root logger serves as a threshold for all loggers without explicit log level threshold of their own. You are right that you have to add an appender filter on the root logger's appenders, if you want to avoid the scenario that you are describing. You could also turn off additivity for your one logger to avoid events to propagate towards root.

**Comment by kaufManu** [comment]
Ok, great - thanks a lot for your quick and comprehensive answer!
