### ISSUE TITLE
Uninitialized condition in TTCCLayout

### ISSUE THREAD

**Issue by jpschewe** [log4cplus/log4cplus#150]
This may be in other layouts as well. However if you initialize a TTCCLayout using the constructor that takes a properties object and the properties object does not have keys for all values, then accessing one of the instance variables gives an uninitialized condition error from valgrind. 

I believe the solution for this is to provide a default value to properties.getBool (and other accessors as well) to ensure that the property gets a value even when the key doesn't exist. That or to initialize the variables to defaults in the initializer list of the constructor before the properties accessors are called.

**Comment by wilx** [comment]
This should be fixed by https://github.com/log4cplus/log4cplus/commit/78a51c38b3d1d0dc169896db80aff48e568e4ada.
