### ISSUE TITLE
Building a multi-threaded server using QThreads - blocking read does not return

### ISSUE THREAD

**Issue by kaufManu** [log4cplus/log4cplus#152]
Hello,

I want to build a multi-threaded application which uses `log4cplus::helpers::Socket`s and a `log4cplus::helpers::ServerSocket` respectively. Because I need to display the log statements in an existing GUI, which was built with Qt, I'm using `QThreads` to manage the acceptor thread on the server and to dispatch threads that read from the client. I am encountering an issue that the blocking call to `log4cplus::helpers::Socket::read` does not return immediately when I call the `close` function on the respective socket - it only returns and breaks when the next log statement has arrived. It is very well possible that this problem is introduced by the way I handle my `QThreads`, so I'm going to post in more detail in the following what I'm doing exactly. If you have any suggestions / recommondations for a better implementation of this use case, they are very welcome! I am using version 1.1.3 rc 4.

Generally I have the following setup: A dispatcher thread (which is a `QThread` as mentioned before) continuously listens for incoming connections. It's run method looks like this:

``` cpp
mStopRequested = false;

// create the server socket
// mServerSocket is wrapped in a smart pointer
mServerSocket.reset(new log4cplus::helpers::ServerSocket(PORT));

if (!mServerSocket->isOpen()
  {
   std::cout << "ERROR: Could not open server socket" << std::endl;
   return;
}

while (!mStopRequested)
{
  // wait for incoming connection
  log4cplus::helpers::Socket _socket = mServerSocket->accept();

  if (!mStopRequested)
  {
    dispatch(_socket);
  }
}
```

The `dispatch` function creates a new worker thread (which is again a `QThread`). I only expect very few client connections, so I chose not to use a thread pool. The client socket returned from `accept` is passed to this worker in the constructor. The run method of a worker looks like the following (`mSocket` is the client socket passed via the constructor):

``` cpp
 std::cout << "start worker" << std::endl;
  mStopRequested = false;

  while (!mStopRequested)
  {
    if (!mSocket.isOpen())
    {
      std::cout << "ERROR: socket not open - abort") << std::endl;
      mStopRequested = true;
      continue;
    }

    // read size of the message
    log4cplus::helpers::SocketBuffer _msgSizeBuffer(sizeof(unsigned int));

    if (!mSocket.read(_msgSizeBuffer)) // here is the problem
    {
      if (errno == 10054)
      {
        std::cout << "Connection reset on client side - abort" << std::endl;
      }
      else
      {
        std::cout<< "ERROR: error reading size of message from buffer - abort" << std::endl;
      }
      mStopRequested = true;
      continue;
    }

    unsigned int _msgSize = _msgSizeBuffer.readInt();

    // read the message
    log4cplus::helpers::SocketBuffer _buffer(_msgSize);
    if (!mSocket.read(_buffer))
    {
      std::cout << "ERROR: error reading message from buffer - abort" << std::endl;
      mStopRequested = true;
      break;
    }

    log4cplus::spi::InternalLoggingEvent _event = log4cplus::helpers::readFromBuffer(_buffer);

    // do something with the message
    // ...
  }
```

The problem is that `mSocket.read(_msgSizeBuffer)` does not break immediately when I call `mSocket.close()` from the outside. It only breaks when another message arrives. Is this expected behaviour? Or am I messing things up because I access the socket from multiple threads? Would you recommend to use `log4cplus::thread::AbstractThread` rather than `QThreads`? I realize that this question might be very localized. So feel free to just point me towards some examples that I might not have found yet or highlight some design issues that I'm not aware of. In any case, thanks a lot for your help!

**Comment by wilx** [comment]
That `read()` does not return when socket is `close()`d is OK per POSIX. log4cplus does not do anything special with the OS `read()` to make its own `read` handle this. So far it was not necessary.
