### ISSUE TITLE
Missing virtual destructors

### ISSUE THREAD

**Issue by jpschewe** [log4cplus/log4cplus#153]
These are minor issues, but got flagged by the static analyzer in Eclipse. 
  * Class FactoryTempl has virtual method createObject, but non-virtual destructor in spi/factory.h
  * Class LocalFactoryBase has virtual method createObject, but non-virtual destructor in spi/factory.h
  * no break at end of case in property.cxx line 147
  * no break at end of case in property.cxx line 150

**Comment by wilx** [comment]
> Class `FactoryTempl` has virtual method `createObject`, but non-virtual destructor in `spi/factory.h`

On master branch, `FactoryTempl` inherits from `LocalFactoryBase<ProductFactoryBase>` which inherits from the `ProductFactoryBase` template type parameter. This parameter is one of `spi::AppenderFactory`, `spi::LayoutFactory`, `spi::FilterFactory`, `spi::LocaleFactory`. Each of these has a virtual dtor, so even `FactoryTempl` has a virtual dtor in the end.

> Class `LocalFactoryBase` has virtual method `createObject`, but non-virtual destructor in `spi/factory.h`

Ditto.

> no break at end of case in `property.cxx` line 147

> no break at end of case in `property.cxx` line 150

I see the breaks in all appropriate places.

**Comment by jpschewe** [comment]
I understand that the right thing happens. I'm pointing out that some static analysis tools, in this case Eclipse, will flag this as a potential error. If someone changes the inheritance hierarchy or removes the virtual from a parent class's destructor it all breaks. Putting the explicit virtual keyboard on these destructors will avoid such possible issues in the future.
