### ISSUE TITLE
Release 1.2.0 // unable to compile with MSVS 2015 / CMake

### ISSUE THREAD

**Issue by snikulov** [log4cplus/log4cplus#163]
MSVS 2015 compilation error 

> C:\WORK\GitHub\log4cplus\include\log4cplus/internal/socket.h(88): error C3861: FreeAddrInfoW: identifier not found

The problem is related to https://github.com/log4cplus/log4cplus/blob/REL_1_2_0/CMakeLists.txt#L73

`set(_WIN32_WINNT 0x0500 CACHE STRING "Define Windows API version to use.")`

Must be at least 0x0502, because this function available in [Windows XP SP 2](https://msdn.microsoft.com/en-us/library/windows/desktop/ms737931(v=vs.85).aspx).

Or greater (Vista - 0x0600) as on master branch

**Comment by wilx** [comment]
Good catch. I am bumping it up to 0x502.

**Comment by wilx** [comment]
This hopefully fixes it.
