### ISSUE TITLE
Segmention fault at shutdown with CreateDirs property

### ISSUE THREAD

**Issue by havasd** [log4cplus/log4cplus#165]
Hi!

I am trying to use the CreateDirs property but I receive a segmention fault at shutdown and I couldn't find out what causes the problem.
Version: 1.2.0-RC3, 1.2.0
[Stacktrace](https://gist.github.com/havasd/98843196bbaa1947906d)
[Configuration file](https://gist.github.com/havasd/16b535c87620e7269378)

I have initialized log4cplus with the following calls:
`  log4cplus::initialize();`
`  log4cplus::PropertyConfigurator config("conf_log.conf");`
`  config.configure();`

Thanks for your help.

**Comment by wilx** [comment]
Please try to add call to `log4cplus::Logger::shutdown()` before your application exists.

**Comment by havasd** [comment]
Thanks this solved the problem.
But the original problem is really strange because there are vms where the original usage didn't cause segmention faults. Maybe an OS package update caused the problem?

**Comment by wilx** [comment]
If you have updated log4cplus to 1.2.0 from 1.1.x or earlier, it might make the difference. There are differences between the versions in how it does initialization and shutdown.
