### ISSUE TITLE
error : expected expression, when __VA_ARGS__ is NULL

### ISSUE THREAD

**Issue by hlee13** [log4cplus/log4cplus#173]
should be 
`include/log4cplus/loggingmacros.h`
replace all `__VA_ARGS__`  to `##__VA_ARGS__`

**Comment by wilx** [comment]
Nope. This is not [portable](https://sourceforge.net/p/log4cplus/bugs/285/). You should not be giving empty arguments to the `*_FMT()` macros anyway. If you know you will not be having any arguments, then you should use the `*_STR()` version instead.
