### ISSUE TITLE
remove logger

### ISSUE THREAD

**Issue by cppbitman** [log4cplus/log4cplus#174]
Hi, I'm working on an application, in which dynamically creating logger instance is needed !
Can log4cplus remove logger instance so the memory won't increase continuously ?

Can anybody help me?
Thanks

**Comment by wilx** [comment]
> Can log4cplus remove logger instance so the memory won't increase continuously ?

No, it cannot do that. What is the variable part that make the number of loggers unbound? Maybe you could use NDC or MDC instead?

**Comment by cppbitman** [comment]
> What is the variable part that make the number of loggers unbound?
loggers are working with Actors in my application. Actors are dynamically created.

**Comment by wilx** [comment]
> loggers are working with Actors in my application. Actors are dynamically created. I hope loggers can be removed together with actors

OK. This is not the way log4cplus and other log4* libraries are supposed to be used. The loggers hierarchy should reflect the static structure of your application in some way. The dynamic parts are handled by [`MDC`](https://github.com/log4cplus/log4cplus/blob/1.2.x/include/log4cplus/mdc.h), [`NDC`](https://github.com/log4cplus/log4cplus/blob/1.2.x/tests/ndc_test/main.cxx#L31) together with appropriate PatternLayout formatters (`%X` and `%x`), or just plain content of the logged events.
