### ISSUE TITLE
C++11 support

### ISSUE THREAD

**Issue by jpschewe** [log4cplus/log4cplus#177]
It would be nice to be able to build log4cplus with C++11. As it stands right now the usages of auto_ptr need to be removed as this is deprecated in C++11. There may be other issues as well.

**Comment by wilx** [comment]
Master branch is C++11 only already.

**Comment by jpschewe** [comment]
Great. I'm just waiting for a release after 1.2.0 then.

On Thu, Jun 16, 2016 at 3:25 PM, Václav Haisman <notifications@github.com>
wrote:

> Master branch is C++11 only already.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/log4cplus/log4cplus/issues/177#issuecomment-226603162>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAN1GeR6zrfCMQnpeXPWh19Y8mAOFNwRks5qMbE9gaJpZM4I3fVu>
> .
>



-- 
http://mtu.net/~jpschewe

**Comment by wilx** [comment]
FYI, I have just released [2.0.0-RC1](https://sourceforge.net/p/log4cplus/news/2017/02/log4cplus-200-rc1-released/).
