### ISSUE TITLE
iOS only single-threaded?

### ISSUE THREAD

**Issue by dmigous** [log4cplus/log4cplus#178]
Hello

__log4cplus version 1.2__

I have an issue. I've built log4cplus with multi-threaded version for iOS for armv7, arvm7s, arm64. When I tried to publish application that uses log4cplus in apple store they sent me back an error:

> Dear developer,
We have discovered one or more issues with your recent delivery for "ProjectX". To process your delivery, the following issues must be corrected: 
Non-public API usage: 
•    The app references non-public symbols in PROJECTX: __tlv_bootstrap
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. 

Then I investigated what is `__tlv_bootstrap` and found that only in __arm64__ version of liblog4cplus.a there is a usage of this symbol( a dependency to this symbol). As I understand it is due to Thread Local Storage usage? Also I found in `log4cplus/iOS/scripts/cmake_ios_armv7.sh` the flag `-DLOG4CPLUS_SINGLE_THREADED="TRUE"` does it mean that for iOS we can use only single threaded log4cplus?

**Comment by wilx** [comment]
IIRC there were some linking issues with the threaded version observed by somebody in the bast. I have no way of testing this so I rely on reports. There is no reason in log4cplus itself why it should not support threading on iOS as far as I know. Feel free to experiment and try different setting. Please report back if you make it work with threading.

**Comment by dmigous** [comment]
Multi-threaded works perfectly on the device. But somehow only arm64 version depends on `__tlv_bootstrap` that is private API for Apple...

If I will turn single-threaded mode, then what features will be turned off? NDC?

**Comment by wilx** [comment]
There is a section in README.md about [iOS support](https://github.com/log4cplus/log4cplus/tree/1.2.x#ios-support). At its very end there is note that suggests to comment out these lines from `ConfigureChecks.cmake`:

    set(LOG4CPLUS_HAVE_TLS_SUPPORT 1)
    set(LOG4CPLUS_THREAD_LOCAL_VAR "__thread")

This will disable use of TLS based on `__thread` keyword in log4cplus and it should fall back to POSIX' `pthread_setspecific()`. This, I think, should solve your problem.

To answer your question, NDC should work in single threaded build as well. In that case the "TLS" data are just a global variable then.

**Comment by dmigous** [comment]
So...
Thanks for you hint regarding how to turn off TLS. I'm using Autotools build system version. So I came to commenting line in `configure.ac`:
```
#AX_TLS_SUPPORT
```
Now I think we need to make TLS switchable with some flag to `cmake` and to `./configure`. What do you think?

**Comment by wilx** [comment]
> Now I think we need to make TLS switchable with some flag to `cmake` and to `./configure`. What do you think?

Using switches is suboptimal, IMHO.

I instead of switches, I would rather enhance the `AX_TLS_SUPPORT` macro to automatically disable TLS support for either iOS or Android or both, if it is simply never going to work. But if there is a reliable way how to detect that it will work, I would rather enhance it in this respect.

...

Well, I did some searching and it seems Android simply does not support `__thread`, so it should be disabled in the CMake configuration for Android by default.

I have actually never heard of anyone using log4cplus on Android through the Autotools build system, so fixing that might be less important.

So, if you feel like it, please submit patches that change the defaults for Android. If you know and can test and patch iOS support then do not hesitate to change it as well.

**Comment by wilx** [comment]
Ooops, somehow, I mentally switched from iOS that you are concerned about to Android. :)

**Comment by wilx** [comment]
I see <https://llvm.org/bugs/show_bug.cgi?id=19232>, it suggests iOS simply does not support TLS and only POSIX API is supported.

**Comment by dmigous** [comment]
I think it may be closed after pull request merged
