### ISSUE TITLE
Configuring log4cplus.properties location via an environment variable

### ISSUE THREAD

**Issue by bcopy** [log4cplus/log4cplus#194]
Similar to what can be done with log4j java system properties (-Dlog4j.configurationFile=....), is there a way to configure the log4cplus property file location via an environment variable ?

This would be handy to bootstrap logging from the get-go, prior to any application-specific configuration steps.

For reference :
 https://logging.apache.org/log4j/2.x/manual/configuration.html

**Comment by wilx** [comment]
That is not possible. If you want to configure log4cplus from a properties file then you have to either instantiate `PropertiesConfigurator` and call `configure()` or call `PropertiesConfigurator::doConfigure()` some time *after* entering `main()`.

**Comment by rjapagal** [comment]
Is there any way if we can update log4cplus configuration file at run time?
Like in log4j, log4j.appender.logfile.File=${logfile.name} and logfile.name is updated in java code using system properties as System.setProperty("logfile.name","some path/logfile name string");

Please let me know if this is possible in log4cplus?
