### ISSUE TITLE
SIGSEGV: invalid address at stop

### ISSUE THREAD

**Issue by tatouft** [log4cplus/log4cplus#195]
My process exits with code 11. If I run it in the debugger, there is a "SIGSEGV: invalid address".
Here is the call stack:

~~~
pthread_join
log4cplus::thread::AbstractThread::join()
log4cplus::AsyncAppender::close()
log4cplus::spi::LoggerImpl::closeNestedAppenders()
log4cplus::Hierarchy::shutdown()
log4cplus::Hierarchy::~Hierarchy()
~~~

I have tried to simplify the code  and here is what I have:

```cpp
#include <iostream>
#include <log4cplus/logger.h>
#include <log4cplus/configurator.h>
int main()
{
  log4cplus::PropertyConfigurator config("/tmp/log.txt");
  config.configure();

  return 0;
}
```

And the config file:

~~~
log4cplus.rootLogger=OFF, A1
log4cplus.logger.L1=OFF, A5
log4cplus.logger.L2=OFF, A2
log4cplus.logger.L4=OFF, A3
log4cplus.logger.L6=OFF, A4
log4cplus.logger.L7=OFF, A1

log4cplus.appender.A1=log4cplus::AsyncAppender
log4cplus.appender.A1.Appender=log4cplus::ConsoleAppender

log4cplus.appender.A2=log4cplus::AsyncAppender
log4cplus.appender.A2.Appender=log4cplus::ConsoleAppender

log4cplus.appender.A3=log4cplus::AsyncAppender
log4cplus.appender.A3.Appender=log4cplus::ConsoleAppender

log4cplus.appender.A4=log4cplus::AsyncAppender
log4cplus.appender.A4.Appender=log4cplus::ConsoleAppender

log4cplus.appender.A5=log4cplus::AsyncAppender
log4cplus.appender.A5.Appender=log4cplus::ConsoleAppender
~~~

If I change the logger name L7 to L6, I don't have an error anymore.
Actually, if I delete any configuration line, I don't have an error anymore but I noticed that the name of my logger L7 worried.

I use log4cplus 1.1.3-0.4.rc3 on centos7

**Comment by wilx** [comment]
Please try to modify the code and add `log4cplus::Logger::shutdown();` before the return statement in your `main()`.

**Comment by tatouft** [comment]
I have test with log4cplus 1.2.0 and I have the same problem.

**Comment by tatouft** [comment]
I could fix this adding one line in AsyncAppender::Close method:
if(queue_thread->isRunning())

just before join call.

**Comment by wilx** [comment]
I do no entirely understand why this is happening but adding the condition before the `close()` call seems like something that should be there anyway. This is because if for some reason the thread is shut down in `AsyncAppender::append()` then without the conditional it will access NULL pointer.

**Comment by wilx** [comment]
I have added the suggested fix to all active branches.
