### ISSUE TITLE
Cannot build on Ubuntu 16.04

### ISSUE THREAD

**Issue by malirod** [log4cplus/log4cplus#202]
`./configure` works, but after this make produces
```
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/malirod/libs/log4cplus/missing aclocal-1.14 -I m4
/home/malirod/libs/log4cplus/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:879: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127
```

v1.1.3-RC7 builds fine in the same environment

**Comment by wilx** [comment]
Are you building from Git working copy? You will need to run `./scripts/fix-timestamps.sh` after you clone or change branches.

**Comment by malirod** [comment]
Yep, I've cloned repo, created a branch from release tag and was trying to build.
So the the right way is to download release tar ball instead of direct cloning?

**Comment by wilx** [comment]
The main distribution point for releases is at SourceForge: https://sourceforge.net/projects/log4cplus/files/log4cplus-stable/.

**Comment by malirod** [comment]
Yes, this way it works. Thanks for help!

May be it worth to mention such cases as mine in readme to prevent misunderstanding? It's not clear from readme and install files, that it's expected to download releases from sourceforge.

Or at least leave some comment about `./scripts/fix-timestamps.sh ` in readme.
