### ISSUE TITLE
Branch 1.2.0 still uses auto_ptr which are depricated in c++11

### ISSUE THREAD

**Issue by malirod** [log4cplus/log4cplus#204]
GCC 5.4 uses C++11 by default and complains on auto_ptrs. With `-Wextra -Werror` project doesn't build.
It's not a problem to add `-Wno-error-deprecated-declarations` to all log4cplus sources during build, but much better to have clean output out-of-the-box

Logs attached
[g++-5.4-warnings.txt](https://github.com/log4cplus/log4cplus/files/541356/g.-5.4-warnings.txt)

**Comment by wilx** [comment]
Master branch does not use `std::auto_ptr`, it uses `std::unique_ptr`. For other branches, it is a "won't fix."

**Comment by malirod** [comment]
Current master doesn't build in my env.
```
src/global-init.cxx:35:10: fatal error: 'ThreadPool.h' file not found
#include "ThreadPool.h"
```
I'm executing the following commands after checking out master
```
./scripts/fix-timestamps.sh
./configure CXX="clang++" --disable-shared --enable-static --prefix=$PWD/build
```

**Comment by malirod** [comment]
I've found missed instruction. It's `git submodule update --init --recursive`.  With it master builds with g++
