### ISSUE TITLE
Lib setup sometimes fails in docker on Travis CI

### ISSUE THREAD

**Issue by malirod** [log4cplus/log4cplus#208]
I'm building docker image from docker file on Travis CI. Each build involves log4cplus (current master) build from the scratch. Some times lib configuration fails (quite often actually) and this fails the whole build.

Log
```
Setting top to                           : /root/project 
Setting out to                           : /root/project/build 
Checking for 'clang++' (C++ compiler)    : /usr/bin/clang++ 
+ touch aclocal.m4
+ find . -name Makefile.in -print -exec touch {} ;
./Makefile.in
./simpleserver/Makefile.in
./include/Makefile.in
+ touch configure
+ touch tests/testsuite
/bin/sh: 1: ./configure: Text file busy
Command failed with exit code 2
(complete log in /root/project/build/config.log)
./scripts/fix-timestamps.sh
./configure CXX="/usr/bin/clang++" --disable-shared --enable-static --prefix=$PWD/build
The command '/bin/sh -c ./waf configure' returned a non-zero code: 1
```

Related discussion: https://github.com/docker/docker/issues/9547

Adding `sync` worked for me (at least for now). My workaround is to patch `./scripts/fix-timestamps.sh` with the following lines:
```
sed -i "s/touch configure/touch configure && sync/" ./scripts/fix-timestamps.sh
sed -i "s/touch tests\/testsuite/touch tests\/testsuite && sync/" ./scripts/fix-timestamps.sh
```

But it's nice to have everything work out-of-the-box

**Comment by wilx** [comment]
I am sorry but this is a Docker problem. I am not going to try to work around that in log4cplus.
