### ISSUE TITLE
log4cplus 2.0-RC1 compile fail

### ISSUE THREAD

**Issue by hzhxxx** [log4cplus/log4cplus#212]
centos 7.2.1511
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

step
1. unzip log4cplus-master.zip 
2. cd log4cplus-master
3. ./configure
4. make
libtool: compile:  g++ -DHAVE_CONFIG_H -I./include -I./threadpool -I./include -I./catch/single_include -DCATCH_CONFIG_PREFIX_ALL=1 -DNDEBUG -DINSIDE_LOG4CPLUS -D_GNU_SOURCE=1 -D_REENTRANT -g -O2 -std=gnu++11 -Wall -fdiagnostics-show-caret -ftrack-macro-expansion -fdiagnostics-color=auto -Wextra -pedantic -Wstrict-aliasing -Wstrict-overflow -Woverloaded-virtual -Wold-style-cast -Wundef -Wshadow -Wformat -Wnoexcept -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wno-variadic-macros -fvisibility=hidden -pthread -MT src/liblog4cplus_la-global-init.lo -MD -MP -MF src/.deps/liblog4cplus_la-global-init.Tpo -c src/global-init.cxx  -fPIC -DPIC -o src/.libs/liblog4cplus_la-global-init.o
src/global-init.cxx:35:24: 致命错误：ThreadPool.h：没有那个文件或目录
 #include "ThreadPool.h"
                        ^
编译中断。

**Comment by wilx** [comment]
Where are you getting the file?

Just check out Git working copy including submodules and you should be OK.

**Comment by prehonor** [comment]
先用 这个 REL_1_2_0-RC6 版本吧,我用vs2015打开 就能编译了

**Comment by wilx** [comment]
[**@prehonor**](https://github.com/prehonor) commented on [4. 1. 2017 10:31 SEČ](https://github.com/log4cplus/log4cplus/issues/212#issuecomment-270329486 "2017-01-04T09:31:31Z - Replied by Github Reply Comments"):
> 先用 这个 REL_1_2_0-RC6 版本吧,我用vs2015打开 就能编译了

I do not understand Chinese. 

I am closing this on assumption that this was fixed by properly checking out all submodules.

**Comment by hzhxxx** [comment]
thanks
