### ISSUE TITLE
CMake version 2.8.10 unable to generate make project for REL_1_2_0

### ISSUE THREAD

**Issue by snikulov** [log4cplus/log4cplus#224]
Hello, 

current branch 1.2.x declares `cmake_minimum_required (VERSION 2.8.4)`
but it not able to generate build with CMake v2.8.10 with error 

`CMake Error at src/CMakeLists.txt:160 (install):
  install TARGETS given unknown argument "INCLUDES".`

because this argument not supported on CMake versions prior 2.8.12
[check documentation here](https://cmake.org/cmake/help/v2.8.11/cmake.html#command:install)

here the options

1. update cmake_minimum_required to version 2.8.12
2. remove  INCLUDES DESTINATIONS from include https://github.com/log4cplus/log4cplus/blob/1.2.x/src/CMakeLists.txt#L161

**Comment by snikulov** [comment]
I check it was already eventually fixed using alternative 1 on master with ca2e311f307714c3da6a46eeecace953649024c0
So you just need to merge it on 1.2.x release branch.

**Comment by wilx** [comment]
@snikulov I have cherry picked the change and I will be merging #225 update to 1.2.x soon
