### ISSUE TITLE
mingw32 build not working

### ISSUE THREAD

**Issue by jschewebbn** [log4cplus/log4cplus#228]
I am trying to build on mingw32 and it appears that the Fls* functions aren't available in mingw32.  Version 1.2.0 worked just fine on mingw32.

This is with version 2.0.0-rc1.

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I./include -I./threadpool -I./include -I./catch/single_include -DCATCH_CONFIG_PREFIX_ALL=1 -DNDEBUG -DINSIDE_LOG4CPLUS -D_GNU_SOURCE=1 -U__STRICT_ANSI__ -DWIN32 -D_WIN32 -DMINGW_HAS_SECURE_API=1 -D_REENTRANT -DUNICODE -D_UNICODE -std=gnu++11 -Wall -fdiagnostics-show-caret -ftrack-macro-expansion -fdiagnostics-color=auto -Wextra -pedantic -Wstrict-aliasing -Wstrict-overflow -Woverloaded-virtual -Wundef -Wshadow -Wformat -Wnoexcept -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wno-variadic-macros -O2 -fvisibility=hidden -MT src/liblog4cplus_la-appender.lo -MD -MP -MF src/.deps/liblog4cplus_la-appender.Tpo -c src/appender.cxx  -DDLL_EXPORT -DPIC -o src/.libs/liblog4cplus_la-appender.o
In file included from ./include/log4cplus/internal/internal.h:59:0,
                 from src/appender.cxx:29:
./include/log4cplus/thread/impl/tls.h: In function 'log4cplus::thread::impl::tls_key_type log4cplus::thread::impl::tls_init(log4cplus::thread::impl::tls_init_cleanup_func_type)':
./include/log4cplus/thread/impl/tls.h:119:45: error: 'FlsAlloc' was not declared in this scope
     DWORD const slot = FlsAlloc (cleanupfunc);
                                             ^
./include/log4cplus/thread/impl/tls.h: In function 'void* log4cplus::thread::impl::tls_get_value(log4cplus::thread::impl::tls_key_type)':
./include/log4cplus/thread/impl/tls.h:132:26: error: 'FlsGetValue' was not declared in this scope
     return FlsGetValue (k);
                          ^
./include/log4cplus/thread/impl/tls.h: In function 'void log4cplus::thread::impl::tls_set_value(log4cplus::thread::impl::tls_key_type, log4cplus::thread::impl::tls_value_type)':
./include/log4cplus/thread/impl/tls.h:139:26: error: 'FlsSetValue' was not declared in this scope
     FlsSetValue (k, value);
                          ^
./include/log4cplus/thread/impl/tls.h: In function 'void log4cplus::thread::impl::tls_cleanup(log4cplus::thread::impl::tls_key_type)':
./include/log4cplus/thread/impl/tls.h:146:15: error: 'FlsFree' was not declared in this scope
     FlsFree (k);
               ^
./include/log4cplus/thread/impl/tls.h: In function 'void* log4cplus::thread::impl::tls_get_value(log4cplus::thread::impl::tls_key_type)':
./include/log4cplus/thread/impl/tls.h:133:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[4]: *** [src/liblog4cplus_la-appender.lo] Error 1
make[4]: Leaving directory `/d/workspace-jnlp/workspace/grex-bps-feature-branches/label/amd64-windows/bps/extlib/source/log4cplus-2.0.0-rc1'
make[3]: *** [all-recursive] Error 1
```

**Comment by wilx** [comment]
You have to use newer MingGW version. See the README.md. It lists MinGW64 versions I have tested.

**Comment by jschewebbn** [comment]
That's most unfortunate. Switching from mingw32 to mingw64 is no small task.

**Comment by jschewebbn** [comment]
Any particular reason you're not just using the pthread implementation that's in mingw?

**Comment by wilx** [comment]
> That's most unfortunate. Switching from mingw32 to mingw64 is no small task.

That's the price for using obsolete tools. :)

**Comment by wilx** [comment]
> Any particular reason you're not just using the pthread implementation that's in mingw?

  1. That would require me to detect that it is a MinGW version using pthreads API. Or user would be forced to specify that.
  2. It is yet another configuration to test but it is for rather obsolete platform/feature combination.
  3. It is not native.

**Comment by wilx** [comment]
Why should be porting to MinGW64 be that hard?

**Comment by jschewebbn** [comment]
It's a whole new development environment to setup. It's a very different model for how the packages are distributed, so I need to figure out all of the packages that need to be installed to build the applications. There are also API differences from mingw32. I've started doing this for another project and it's taken weeks just to get the basics going. Once this is working I will need to replicate it on my build systems and all developers workstations. 

AFAIK all mingw versions support pthreads. So just checking for mingw and using pthreads would continue to support mingw32 like the version 1.2.0 version did.

**Comment by jschewebbn** [comment]
Do note that the mingw32 that I've been using is shipped with Qt, so it's much easier to install. If using mingw64, then I need my own Qt install as well.

**Comment by wilx** [comment]
> Do note that the mingw32 that I've been using is shipped with Qt, so it's much easier to install. If using mingw64, then I need my own Qt install as well.

Well, [Supported Platforms | Qt 5.8](http://doc.qt.io/qt-5/supported-platforms.html) page suggests that Qt Creator is using MinGW64 as well. 

Is your version new enough?

**Comment by jschewebbn** [comment]
Unfortunately I'm still on 5.1. 
However that page only says MinGW, not MinGW64. Note that there is a big difference between mingw32 and mingw64. 

The download page only lists a mingw 5.3.0 download. I may try that one and see if it works.

I'm also looking into patching log4cplus to use pthread on mingw32.

**Comment by wilx** [comment]
The Supported Configurations section's table has Notes column with a link to https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/5.3.0/threads-posix/dwarf/i686-5.3.0-release-posix-dwarf-rt_v4-rev0.7z/download, a link to MinGW64.

If I download that, I see the `FlsAlloc()`, etc., API is declared there.

**Comment by jschewebbn** [comment]
That's promising. Updating Qt would update my development environment at the same time. That may solve the issue as well.

I find it interesting that the mingw32 build doesn't find FlsAlloc in the windows libraries when the correct headers are included though.

**Comment by jschewebbn** [comment]
I have a small test project for testing log4cxx on multiple platforms and I tried upgrading that to Qt 5.8.0 with mingw_32 5.3.0. That gives the same errors about `FlsAlloc()`.  Here's the compiler version information. 
```
$ gcc --version
gcc.exe (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Where should I find these functions defined in the release? Perhaps it's just missing an include?
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I./include -I./threadpool -I./include -I./catch/single_include -DCATCH_CONFIG_PREFIX_ALL=1 -DNDEBUG -DINSIDE_LOG4CPLUS -D_GNU_SOURCE=1 -U__STRICT_ANSI__ -DWIN32 -D_WIN32 -DMINGW_HAS_SECURE_API=1 -D_REENTRANT -DUNICODE -D_UNICODE -std=gnu++11 -Wall -fdiagnostics-show-caret -ftrack-macro-expansion -fdiagnostics-color=auto -Wextra -pedantic -Wstrict-aliasing -Wstrict-overflow -Woverloaded-virtual -Wc++14-compat -Wundef -Wshadow -Wformat -Wnoexcept -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wno-variadic-macros -O2 -fvisibility=hidden -MT src/liblog4cplus_la-appender.lo -MD -MP -MF src/.deps/liblog4cplus_la-appender.Tpo -c src/appender.cxx  -DDLL_EXPORT -DPIC -o src/.libs/liblog4cplus_la-appender.o
In file included from ./include/log4cplus/internal/internal.h:59:0,
                 from src/appender.cxx:29:
./include/log4cplus/thread/impl/tls.h: In function 'log4cplus::thread::impl::tls_key_type log4cplus::thread::impl::tls_init(log4cplus::thread::impl::tls_init_cleanup_func_type)':
./include/log4cplus/thread/impl/tls.h:119:45: error: 'FlsAlloc' was not declared in this scope
     DWORD const slot = FlsAlloc (cleanupfunc);
                                             ^
./include/log4cplus/thread/impl/tls.h: In function 'void* log4cplus::thread::impl::tls_get_value(log4cplus::thread::impl::tls_key_type)':
./include/log4cplus/thread/impl/tls.h:132:26: error: 'FlsGetValue' was not declared in this scope
     return FlsGetValue (k);
                          ^
./include/log4cplus/thread/impl/tls.h: In function 'void log4cplus::thread::impl::tls_set_value(log4cplus::thread::impl::tls_key_type, log4cplus::thread::impl::tls_value_type)':
./include/log4cplus/thread/impl/tls.h:139:26: error: 'FlsSetValue' was not declared in this scope
     FlsSetValue (k, value);
                          ^
./include/log4cplus/thread/impl/tls.h: In function 'void log4cplus::thread::impl::tls_cleanup(log4cplus::thread::impl::tls_key_type)':
./include/log4cplus/thread/impl/tls.h:146:15: error: 'FlsFree' was not declared in this scope
     FlsFree (k);
               ^
make[4]: *** [src/liblog4cplus_la-appender.lo] Error 1
make[4]: Leaving directory `/q/log4cxx-test/log4cxx/source/log4cplus-2.0.0-rc1'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/q/log4cxx-test/log4cxx/source/log4cplus-2.0.0-rc1'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/q/log4cxx-test/log4cxx/source/log4cplus-2.0.0-rc1'
make[1]: *** [install/debug/include/log4cplus/logger.h] Error 2
make[1]: Leaving directory `/q/log4cxx-test/log4cxx'
make: *** [log4cxx] Error 2
make: Leaving directory `/q/log4cxx-test'
```

**Comment by wilx** [comment]
If you grep your MinGW installation for `FlsAlloc`, do you find it at all?

**Comment by jschewebbn** [comment]
I checked all of the mingw installation that comes with Qt 5.8.0 and didn't find any non-binary files that match.

```
jschewe@JSCHEWE-WIN7 /c/Qt/Qt5.8.0
$ grep -R FlsAlloc 5.8/mingw53_32/* Tools/mingw530_32/*
Binary file 5.8/mingw53_32/bin/licheck.exe matches
Binary file 5.8/mingw53_32/bin/opengl32sw.dll matches
Tools/mingw530_32/i686-w64-mingw32/include/fibersapi.h:  WINBASEAPI DWORD WINAPI FlsAlloc (PFLS_CALLBACK_FUNCTION lpCallback);
Binary file Tools/mingw530_32/i686-w64-mingw32/lib/libkernel32.a matches
Binary file Tools/mingw530_32/i686-w64-mingw32/lib/libmsvcr120.a matches
Binary file Tools/mingw530_32/i686-w64-mingw32/lib/libmsvcr120d.a matches
Binary file Tools/mingw530_32/i686-w64-mingw32/lib/libntdll.a matches
Binary file Tools/mingw530_32/opt/lib/python2.7/distutils/command/wininst-9.0-amd64.exe matches
Binary file Tools/mingw530_32/opt/lib/python2.7/distutils/command/wininst-9.0.exe matches
```

**Comment by wilx** [comment]
What I saw yesterday was that `fibersapi.h` is included by `winbase.h` which is included by `windows.h` which is what log4cplus includes. It seems to me it should be visible and available to the compiler.

**Comment by jschewebbn** [comment]
`FlsAlloc` is defined inside this set of ifdefs:
```
#if WINAPI_FAMILY_PARTITION (WINAPI_PARTITION_APP)
#if _WIN32_WINNT >= 0x0600
#endif
#endif
```

The first one is true, the second one is false.

**Comment by jschewebbn** [comment]
It seems that `_WIN32_WINNT` has the value of 0x502, which according to https://msdn.microsoft.com/en-us/library/6sehtctf.aspx specifies Windows server 2003. I'm running Windows 10 Pro. Interesting that the docs suggest that this define should be modified manually. That sounds like trouble.

**Comment by wilx** [comment]
The `_WIN32_WINNT` symbol and its value is provided by appropriate build system. I did not realize it earlier, but you are using an unsupported way of building log4cplus on MinGW. This is a quote from the README.md (emphasis is mine):

> When using some form of MinGW64 tool-chain, the CMake build system is considered primary and the **Autotools based build system is unsupported.** Use the MinGW Makefiles option and build with mingw-make (or similar). The MSYS Makefiles option is untested and unsupported.

**Comment by jschewebbn** [comment]
It seems the readme is inconsistent. Under compilation:
```
MinGW is supported by autotools based build system. CMake build system
is supported as well and it should be used to compile [log4cplus] with
older versions of Visual Studio or with less common compiler suites
(e.g., Embarcadero, Code::Blocks, etc.).
```

**Comment by wilx** [comment]
I cannot remember exactly why I have added the note about it not being supported. I think it has something to do with the Windows and/or MinGW configuration and detection of features being fixed in `win32.h` and based on preprocesor symbols rather than the detection that Autoconf does.

I guess I can revisit it and try to make it work. But it will take me time. In the mean time, please use CMake builds with MinGW.

**Comment by jschewebbn** [comment]
Cmake refuses to build using MinGW Makefiles under a unix-like shell, so I needed to switch to MSYS Makefiles and that fails with:
```
q:/log4cxx-test/log4cxx/source/log4cplus-2.0.0-rc1/src/socket-win32.cxx: In function 'log4cplus::helpers::SOCKET_TYPE log4cplus::helpers::connectSocket(const tstring&, short unsigned int, bool, bool, log4cplus::helpers::SocketState&)':
q:/log4cxx-test/log4cxx/source/log4cplus-2.0.0-rc1/src/socket-win32.cxx:248:32: error: 'AI_NUMERICSERV' was not declared in this scope
     addr_info_hints.ai_flags = AI_NUMERICSERV;
                                ^
```

So it seems that my build environment is incompatible with the 2.0 release of log4cplus.

**Comment by jschewebbn** [comment]
Got some progress on the WINNT_VER issue. It seems that applications are supposed to set this to the minimum version of windows that they want to support https://msdn.microsoft.com/en-us/library/6sehtctf.aspx
So I added "-D_WIN32_WINNT=0x0601" to my CXXFLAGS when I call configure using mingw 4.9.1 and got passed the FlsAlloc problem. Now I just need to get passed this AI_NUMERICSERV problem.

According to https://msdn.microsoft.com/en-us/library/windows/desktop/ms738518(v=vs.85).aspx it's supposed to be defined if I have Vista or higher, which my setting of WIN32_WINNT

**Comment by jschewebbn** [comment]
I have success. You can add this to your configurations. mingw 5.3.0 that comes with Qt 5.8.0 using autotools to build with `CXXFLAGS="-DUNICODE -D_UNICODE -D_WIN32_WINNT=0x0601"` set for configure.

Thank you for writing this great logging library!

**Comment by wilx** [comment]
Well, `0x0600` should be the value for Windows Vista and the default used by log4cplus. If the MinGW headers do not define it even when `_WIN32_WINNT=0x0600` then I guess we can make its use conditional because it is not strictly necessary.
