### ISSUE TITLE
How can I send log from log4cplus to log4j?

### ISSUE THREAD

**Issue by daomuzhiwang** [log4cplus/log4cplus#231]
I use log4cplus to manage my log. And I want sent the log to log4j based on Java. 
It didn't with "log4jUdpAppender". Is there any tip?

**Comment by wilx** [comment]
IIRC, `Log4jUdpAppender` works if you have the target host/log4j listen for XML messages UDP.

**Comment by daomuzhiwang** [comment]
Hello @wilx ,

Could you please give me an example of using "log4j" as server to listen for XML messages UDP. 
Below is my client and server code. If possible, please help me check it.

> Client code

`
append_1 = new log4cplus::Log4jUdpAppender("192.168.43.93", 20000);
Logger::getRoot().addAppender(append_1);
LOG4CPLUS_FATAL(Logger::getRoot(),logEvent); 
`

> Server code(by Java)
`
UdpSocketServer<InputStream> socketServer2 =       UdpSocketServer.createXmlSocketServer(Integer.parseInt(Constants.LOG_SOCKET_PORT));

Thread server2 = new Thread(socketServer2);
server2.start();
BufferedReader reader2 = new BufferedReader(new InputStreamReader(System.in));
while (true)
 {
	            final String line = reader2.readLine();
	            if (line == null || line.equalsIgnoreCase("Quit") || line.equalsIgnoreCase("Stop")
	                    || line.equalsIgnoreCase("Exit")) {
	                socketServer2.shutdown();
	                server2.join();
	                break;
	            }
 }
`

Thank you very much.

**Comment by wilx** [comment]
I have only ever used the Chainsaw GUI. This receiver configuration seems to still work for me:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd"> 
<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/" debug="true">    
    <plugin name="UDPReceiver" class="org.apache.log4j.net.UDPReceiver">
        <param name="Port" value="5000" />
    </plugin>    
</log4j:configuration>
```

And this is the test `log4cplus.properties` I have used:

```properties
log4cplus.logger.testlogger=TRACE, TEST

log4cplus.appender.TEST.layout=log4cplus::PatternLayout
log4cplus.appender.TEST.layout.ConversionPattern=%d{%y-%m-%d %H:%M:%S,%q} [%t] %-5p %c <%x> - %m%n
log4cplus.appender.TEST=log4cplus::Log4jUdpAppender
log4cplus.appender.TEST.host=localhost
log4cplus.appender.TEST.port=5000
```

**Comment by daomuzhiwang** [comment]
Hello @wilx ,

What's the version of log4j do you use ? 
We have just checked log4j1.x and log4j2, and didn't find "org.apache.log4j.net.UDPReceiver".

Best Wishes

**Comment by wilx** [comment]
[**@daomuzhiwang**](https://github.com/daomuzhiwang) commented on [28. 3. 2017 8:17 SELČ](https://github.com/log4cplus/log4cplus/issues/231#issuecomment-289674226 "2017-03-28T06:17:48Z - Replied by Github Reply Comments"):
> Hello @wilx ,
> 
> What's the version of log4j do you use ? 
> We have just checked log4j1.x and log4j2, and didn't find "org.apache.log4j.net.UDPReceiver".

It is probably in the extras package: http://search.maven.org/#artifactdetails%7Clog4j%7Capache-log4j-extras%7C1.2.17%7Cbundle

**Comment by daomuzhiwang** [comment]
Thanks @wilx ,

We will try to use extras to receive log from log4cplus.
