### ISSUE TITLE
Question: AsyncAppender - cache to disk ?

### ISSUE THREAD

**Issue by gadh** [log4cplus/log4cplus#232]
is there any option in this appender (or a combination of them) to cache to disk when the queue is full, then regularly pull from disk to queue when the queue can recv new events ? then send to syslog for example

**Comment by wilx** [comment]
There is no such option.

**Comment by gadh** [comment]
will you consider adding such an option ?

**Comment by wilx** [comment]
I might consider reasonable patches. But doing something like this is rather complex and, I think, out of the scope of the library. If you need guaranteed delivery then I suggest you build your own appender that, say, delivers to local ActiveMQ instance which would then transport your messages to your destination.
