### ISSUE TITLE
log4cplus keeping application from exiting with 2.0.0-rc1

### ISSUE THREAD

**Issue by jschewebbn** [log4cplus/log4cplus#233]
I have a test application that I use to check compilation of log4cplus on multiple platforms. That application is below. When I build on MSYS2 either 32-bit or 64-bit I have found that the application doesn't exit. I'm building using the autotools build and specifying the following flags for configure "-DUNICODE -D_UNICODE -D_WIN32_WINNT=0x0601". If I build this application and open a MSYS2 terminal and run the application there, the application exits as expected. However if I open a Windows Command prompt and do the following it doesn't exit. I get the last logging statement that the application is exiting, but control the application is still running. It's as if there is a thread running that hasn't exited yet.
```
set PATH=c:\msys64\usr\bin;q:\msys64\usr\bin;d:\msys64\usr\bin

set CHERE_INVOKING=enabled_from_arguments
set MSYSTEM=MINGW32
bash.exe --login -c "logging.exe"
```

This should be the same as running the MSYS2 command script without opening a new terminal, which is what I need to do when running inside Jenkins (which I use for testing).

If I use version 1.2.0-rc6, then the test works fine.

```c++

// include log4cplus header files.
#include <log4cplus/logger.h>
#include <log4cplus/configurator.h>
#include <log4cplus/loggingmacros.h>

#include <string>
#include <exception>
#include <logging/A.hpp>

using namespace log4cplus;
using namespace log4cplus::helpers;

Logger logger = Logger::getInstance(LOG4CPLUS_TEXT("main"));

int main(int /*argc*/, char **/*argv*/)
{
  int result = 0;
  try
    {
      // Set up a simple configuration that logs on the console.
      BasicConfigurator config;
      config.configure();
      //std::string logConfig = "log4j.xml";
      //log4cplus::xml::DOMConfigurator::configure(logConfig);

      LOG4CPLUS_INFO(logger, "Entering application.");
      A a;
      a.doIt(10);
      a.doIt(20);
      LOG4CPLUS_INFO(logger, "Exiting application.");
    }
  catch(std::exception&)
    {
      result = -1;
    }

  return result;
}
```

**Comment by wilx** [comment]
Add `Logger::shutdown()` right before the return statement.

**Comment by jschewebbn** [comment]
Some more information. I added some printfs to your code and found that sometimes the application hangs and sometimes it doesn't. I also added the call to `log4cplus::Logger::shutdown()` right before my return statement and a printf before and after that call. Below is the output and it hangs here.

```
Top of ThreadPool constructor nthreads: 8
INFO - Entering application.
INFO - inside doit: 10
A qdebug line with more text
INFO - inside doit: 20
A qdebug line with more text
INFO - Exiting application.
In main before calling shutdown
Top of waitUntilEmptyThreadPoolQueue
Top of wait_until_empty()
Waiting for tasks: 0
Bottom of wait_until_empty()
Bottom of waitUntilEmptyThreadPoolQueue
In main after shutdown before return
Top ThreadPool destructor
Bottom ThreadPool destructor
```

**Comment by wilx** [comment]
Sorry, I got confused. If you are using 1.2.x then `Logger::shutdown()` before exiting `main()` should be enough. If you are however using 2.x then you should use the `Initializer` class. See [example on wiki](https://sourceforge.net/p/log4cplus/wiki/CodeExamples/#initialization). With 2.x, put `log4cplus::Initializer initializer;` on the top of your `main()`.

**Comment by jschewebbn** [comment]
No problem, I am working on upgrading from 1.2.x so trying both versions here for comparisons.

That works great!
