### ISSUE TITLE
SocketBuffer error

### ISSUE THREAD

**Issue by flyish** [log4cplus/log4cplus#242]
at windows, write log to RemoteServer happen the following error:
log4cplus:WARN readFromBuffer() received socket message with an invalid version
log4cplus:ERROR SocketBuffer::readString()- Attempt to read beyond end of buffer
log4cplus:ERROR SocketBuffer::readString()- Invalid sizeOfChar!!!!
log4cplus:ERROR SocketBuffer::readString()- Attempt to read beyond end of buffer
log4cplus:ERROR SocketBuffer::readString()- Invalid sizeOfChar!!!!
log4cplus:ERROR SocketBuffer::readString()- Attempt to read beyond end of buffer
log4cplus:ERROR SocketBuffer::readString()- Invalid sizeOfChar!!!!
log4cplus:ERROR SocketBuffer::readString()- Attempt to read beyond end of buffer
log4cplus:ERROR SocketBuffer::readString()- Invalid sizeOfChar!!!!
log4cplus:ERROR SocketBuffer::readString()- Attempt to read beyond end of buffer
log4cplus:ERROR SocketBuffer::readString()- Invalid sizeOfChar!!!!
log4cplus:ERROR SocketBuffer::readString()- Attempt to read beyond end of buffer
log4cplus:ERROR SocketBuffer::readString()- Invalid sizeOfChar!!!!
log4cplus:ERROR SocketBuffer::readString()- Attempt to read beyond end of buffer
log4cplus:ERROR SocketBuffer::readString()- Invalid sizeOfChar!!!!

**Comment by flyish** [comment]
vesion:1.2.0  env：Windows 2012 cloud server

**Comment by wilx** [comment]
Could you please provide the SocketAppender settings that you have used? Are both sides of the connection using the same version?

**Comment by flyish** [comment]
yes, the client and server are using 1.2.0 version, client configuration is very simple:
log4cplus.logger.ANA=TRACE,RemoteServer
log4cplus.appender.RemoteServer=log4cplus::SocketAppender  
log4cplus.appender.RemoteServer.host=localhost
log4cplus.appender.RemoteServer.port=9000

server.properties:
log4cplus.logger.ANA=TRACE,ONE
log4cplus.appender.ONE=log4cplus::DailyRollingFileAppender
log4cplus.appender.ONE.File=analytics/analytics.log
log4cplus.appender.ONE.Append=true
log4cplus.appender.ONE.Schedule=HOURLY
log4cplus.appender.ONE.layout=log4cplus::PatternLayout
log4cplus.appender.ONE.layout.ConversionPattern=%m
log4cplus.appender.ONE.LogLevelMin=DEBUG
log4cplus.appender.ONE.LogLevelMax=INFO
log4cplus.appender.ONE.CreateDirs=true
log4cplus.appender.ONE.Local=zh_CH.UTF-8
log4cplus.appender.ONE.ImmediateFlush=false

**Comment by flyish** [comment]
sorry!!, May I have found the reason, It's illegal external connection to the server and send messages

**Comment by wilx** [comment]
> log4cplus.appender.ONE.Local=zh_CH.UTF-8

BTW, @flyish, this property should be `Locale`. You are missing the last `e`.

**Comment by flyish** [comment]
Well, but I don't seem to have found any errors. The generated file is utf8 without BOM
