### ISSUE TITLE
Single-threaded build with CMake on Windows with Visual Studio is not single-threaded.

### ISSUE THREAD

**Issue by JanPlitzkow** [log4cplus/log4cplus#243]
Hi,

I'm using VS2015 with Win7/10 as build & target platform. I'm using cmake with the following parameters to configure the log4cplus project:

> cmake -DBUILD_SHARED_LIBS:BOOL=TRUE  -DWITH_UNIT_TESTS=OFF -DLOG4CPLUS_BUILD_TESTING=OFF -DUNICODE=OFF -DLOG4CPLUS_BUILD_LOGGINGSERVER=OFF -DLOG4CPLUS_SINGLE_THREADED=ON

Despite LOG4CPLUS_SINGLE_THREADED being set explicitly, I noticed, that a multithread-version is running. I figured that the following snippet from config.hxx is responsible:

```
#if defined (_WIN32)
#  include <log4cplus/config/win32.h>
#elif (defined(__MWERKS__) && defined(__MACOS__))
#  include <log4cplus/config/macosx.h>
#else
#  include <log4cplus/config/defines.hxx>
#endif
```

But why is the defines.hxx ignored on windows platform after being generated by cmake?
Is singlethreaded version not supported for windows?
What would be the cleanest / intended way to get a project with my given options? Obviously I could manually modify the checked-in VS-projects, but using cmake seems more appropriate in my project team, because we're using log4cplus on multiple platforms...

Best regards
Jan

Edit: I'm using version 2.0.0-RC1

**Comment by wilx** [comment]
It seems there is no support in `CMakeLists.txt` for `LOG4CPLUS_SINGLE_THREADED` at all. I'll try to add it.
