### ISSUE TITLE
memleak of per_thread_data in multithreaded application on windows

### ISSUE THREAD

**Issue by raphaelmarcucci** [log4cplus/log4cplus#244]
Hi,

A memory leak of objects "per_thread_data" occurred on one application of ours, running on Windows.
This application creates several threads when incoming traffic is high and they stop themselves when traffic gets low again.

In one thread's life:
 - at the first call to log4cplus:
The thread creates an object of type "per_thread_data" (see method alloc_ptd : it uses "new per_thread_data"), stores its void* pointer into its own FLS.
 - at each next call to log4cplus:
The thread gets its "per_thread_data" pointer through the FLS, and uses it as long as the thread lives (see method get_ptd).
 - when the thread terminates:
FLS will free the void* pointer. But, no "delete" of the per_thread_data pointer is done.

In our kind of app (which creates many threads that are bound to terminate), this caused a memory leak.

A fix on my side was:
 - create an internal method that retrieves the pointer from FLS (with method get_ptd), and deletes it.
 - make the method usable from outside log4cplus with a macro.
 - add the call to this macro at the end of each thread of our application.
 - surround everything with lots of comments (to prevent another coder from logging afterwards in the thread).

It works, we leak no more, but, this is most probably feasible in a better way.

Note:
There would be actions to take on the caller code instead of log4cplus.
For instance, we could use and re-use the same threads with a threadpool instead of having our machinery for creating new threads: this would conceal the leak.
I just focus the question here on log4cplus's side.

Question:
At the end of the thread, is there a way to always delete its per_thread_data without having to manually add a call in the caller code ?

Thanks!

**Comment by wilx** [comment]
> FLS will free the void* pointer. But, no "delete" of the per_thread_data pointer is done.

The deletion of the memory allocated for per-thread data should be handled either by `DllMain()` callback or similar callback through MSVCRT. If neither is called (it might happen if you are using statically linked log4cplus with statically linked MSVCRT), try calling `log4cplus::threadCleanup()` at the end of your thread.

**Comment by wilx** [comment]
Is this still a problem? What branch was this?

**Comment by raphaelmarcucci** [comment]
Hi,
Sorry for not having replied earlier.
Yes, calling threadCleanup() (or equivalent) at the end of our thread does the trick.
I think we can close this issue.
Thanks!
