### ISSUE TITLE
Segmentation faults with LOG4CPLUS_SINGLE_THREADED

### ISSUE THREAD

**Issue by JanPlitzkow** [log4cplus/log4cplus#246]
Hi,

I'm using version 2.0.0-RC1 and building for a linux target. It's an distribution for an embedded system which is built via bitbake from yocto poky (https://www.yoctoproject.org/tools-resources/projects/poky). For building of log4cplus I use cmake with the parameters:
```
EXTRA_OECMAKE += "-DBUILD_SHARED_LIBS:BOOL=TRUE"
EXTRA_OECMAKE += "-DWITH_UNIT_TESTS=OFF"
EXTRA_OECMAKE += "-DLOG4CPLUS_BUILD_TESTING=OFF"
EXTRA_OECMAKE += "-DUNICODE=OFF"
EXTRA_OECMAKE += "-DLOG4CPLUS_BUILD_LOGGINGSERVER=OFF"
EXTRA_OECMAKE += "-DLOG4CPLUS_SINGLE_THREADED=ON"
```
The important one seems to be the LOG4CPLUS_SINGLE_THREADED. If I turn it off, I won't get the following errors.

When running the software using the log4cplus-dynamic-library, I get segmentation / access faults. Depending on loglevels and "environment factors" they occur at various locations, but always look like this:
- When running release: 
> terminate called after throwing an instance of 'std::length_error'
>   what():  basic_string::_S_create
> Aborted
- When running debugger attached via tcf:
```
*** Error in `./Program.elf': double free or corruption (fasttop): 0x71d01f50 ***
Aborted
```
with this call stack:
![grafik](https://cloud.githubusercontent.com/assets/7890485/26051317/1f1e92d8-3962-11e7-80d6-483e83dc0705.png)

Are there any differences in usage for the single-threaded version, that I'm not aware of?
Do I need the multithread version if I want to log from different threads in my application?
For now I will use the multithread version, but I think single threaded would be better performance on the embedded system. Any hints / ideas?

Best regards,
Jan

**Comment by wilx** [comment]
> Do I need the multithread version if I want to log from different threads in my application?

Yes.

**Comment by DeadMG** [comment]
What the fuck, you were trying to use the single-threaded version in a non-single-threaded way? How was this not stupendously obviously dumb?
