### ISSUE TITLE
can i change the loggerlevel when program runing

### ISSUE THREAD

**Issue by Hvinix** [log4cplus/log4cplus#248]
i can find any function to change the logger config.
should i need create my function to use this?

**Comment by Hvinix** [comment]
sorry, I mean i only need to create a new thread to use reconfigure() to change loggerlevel?

**Comment by wilx** [comment]
You do not need to reconfigure the whole hierarchy just to change log level. See [`setLogLevel()`](http://log4cplus.sourceforge.net/docs/html/classlog4cplus_1_1Logger.html#ac83b8006bcb44874eb2003b3757a7fdb).

**Comment by Hvinix** [comment]
thanks, i find an interesting function. i can use it to solve my problem
