### ISSUE TITLE
I have a  question about time zone

### ISSUE THREAD

**Issue by Hvinix** [log4cplus/log4cplus#249]
when i use log4cplus in window , i find zhe time zone is error
it always less 8 hours . i cant find optional about time zone
what should i do?

**Comment by Hvinix** [comment]
i use the log4cplus version is 1.2.1-rc1

**Comment by wilx** [comment]
What layout are you using? What is your actual time zone and what do you see in the logs instead?

**Comment by Hvinix** [comment]
this is my config
**
log4cplus.appender.R=log4cplus::RollingFileAppender
log4cplus.appender.R.File=..\\log\\DateBaseLog.log
log4cplus.appender.R.MaxFileSize=1200KB
log4cplus.appender.R.MaxBackupIndex=3
log4cplus.appender.R.layout=log4cplus::PatternLayout
log4cplus.appender.R.layout.ConversionPattern=%d{%m/%d/%y %H:%M:%S:%q} [%t] %-5p %c{2} [%F] - %m %n
**
when i test to get time zone, i get some  messy code.
what did i do wrong?

**Comment by wilx** [comment]
> `%d{%m/%d/%y %H:%M:%S:%q}`

The `%d` specifies that the time will be in UTC. If you want local time then you should use `%D` instead. See also [PatternLayout documentation](http://log4cplus.sourceforge.net/docs/html/classlog4cplus_1_1PatternLayout.html).

**Comment by Hvinix** [comment]
oh ! thanks. i only see at layout.h f
