### ISSUE TITLE
License file with no extention not accepted by WIX

### ISSUE THREAD

**Issue by magno86** [log4cplus/log4cplus#250]
Dear all,
I have just tried to package log4cplus-REL_2_0_0-RC1 using CPACK and WIX.
It fails as it does not accept a license file with no extension. Simply copying LICENSE to LICENSE.txt and adding the .txt extention in Log4CPlusCPack.cmake line 4 makes it work and successfully build an msi.

Cheers,

**Comment by wilx** [comment]
Thank you for the report. Can you please test if changing the extension to `.md` works as well?

**Comment by magno86** [comment]
No,


it does not... you will get the following error if you try:

21>EXEC : CPack error : unsupported WiX License file extension '.md'


Cheers,

Stefano

________________________________

**Comment by wilx** [comment]
Can we find a way to add the necessary copying step to the CPack invocation if the target installer is WIX based?
