### ISSUE TITLE
[log4cplus-2.0.0-rc1] Crash on exit. The solving of issue

### ISSUE THREAD

**Issue by abronix** [log4cplus/log4cplus#251]
Hello! This change was introduced by issue https://github.com/log4cplus/log4cplus/issues/245
to solve a specific problem. What do you think about this way?

See a original file **src/global-init.cxx**:

I added **ThreadPoolDeleter** and changed definition **thread_pool** a litle bit:
```

  struct ThreadPoolDeleter
  {
    void operator () (progschj::ThreadPool* handle)
    {
        delete handle;
        is_pool_alive = false;
    }

    volatile bool is_pool_alive = true;
  };

  //! Default context.
  struct DefaultContext
  {
    log4cplus::thread::Mutex console_mutex;
    helpers::LogLog loglog;
    LogLevelManager log_level_manager;
    helpers::Time TTCCLayout_time_base;
    NDC ndc;
    MDC mdc;
    Hierarchy hierarchy;
    spi::AppenderFactoryRegistry appender_factory_registry;
    spi::LayoutFactoryRegistry layout_factory_registry;
    spi::FilterFactoryRegistry filter_factory_registry;
    spi::LocaleFactoryRegistry locale_factory_registry;
  #if ! defined (LOG4CPLUS_SINGLE_THREADED)
    std::unique_ptr<progschj::ThreadPool, ThreadPoolDeleter> thread_pool{ new progschj::ThreadPool };
  #endif
  };

```

and changed a "if" condition for wait-function:

```
void
waitUntilEmptyThreadPoolQueue ()
{
#if ! defined (LOG4CPLUS_SINGLE_THREADED)
    DefaultContext * const dc = get_dc ();
    if (dc->thread_pool.get_deleter().is_pool_alive)
    {
        dc->thread_pool->wait_until_empty ();
        dc->thread_pool->wait_until_nothing_in_flight ();
    }
#endif
}
```

I tested this solution for Win10x64 and Centos7x64 (with dynamic and static linkage).
It works fine. You can run tests for logger. If they passed
could you add a fix to the next release?

Best regards
Yuri

**Comment by wilx** [comment]
I have just merge recent changes to 2.0.x branch that might fix it. Please try the branch.

**Comment by abronix** [comment]
Yes. You moved 'hierarchy' member, it placed after 'thread_pool' now.
Perhaps, It can help. Now the object 'hierarchy' will not access to the destroyed 'thread_pool'
Well, I'll test '2.0.x' branch (for my issue) tomorrow.

Thanks.
Best regards
Yuri

**Comment by abronix** [comment]
Hello! The logger from 2.0.x branch stops without any crashes. When will be new release which will be based on 2.0.x branch?

**Comment by wilx** [comment]
I will try to release new RC this weekend.

**Comment by wilx** [comment]
I am closing this as fixed. This the change moving the `hierarchy` member is in dedbec44.

**Comment by lightning-li** [comment]
@abronix when I run your example in centos with log4cplus 2.0.1 release version, I got crash.
