### ISSUE TITLE
issue with 1.2.x branch with c++11

### ISSUE THREAD

**Issue by snikulov** [log4cplus/log4cplus#254]
Linux 3.10.0-514.26.1.el7.x86_64 / gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

Build and install 1.2.x branch using CMake and try using this library with a project which is used c++11

The installation contains headers depending on the run-time check and tries to use c++11 features which are disabled because the library was built without c++11 enabled features.

Error looks like

> CMakeFiles/main.dir/src/main.cpp.o: In function `log4cplus::detail::macros_get_logger(log4cplus::Logger&&)':
> main.cpp:(.text._ZN9log4cplus6detail17macros_get_loggerEONS_6LoggerE[_ZN9log4cplus6detail17macros_get_loggerEONS_6LoggerE]+0x2a): undefined reference to `log4cplus::Logger::Logger(log4cplus::Logger&&)'
> collect2: error: ld returned 1 exit status
> make[2]: *** [main] Error 1
> make[1]: *** [CMakeFiles/main.dir/all] Error 2

Here is following options
- not use c++11 features on 1.2.x branch
- enforce building of library with c++11 using option, for ex. -DLOG4CPLUS_BUILD_CXX11=ON/OFF . This will allow control library containment.
- not use runtime checks for C++ features in config.hxx - it should contain frozen value for LOG4CPLUS_HAVE_CXX11_SUPPORT calculated during library configuration.
```
#if (defined (_MSC_VER) && _MSC_VER >= 1600) \
    || defined (__GXX_EXPERIMENTAL_CXX0X__) \
    || __cplusplus >= 201103L
#  define LOG4CPLUS_HAVE_CXX11_SUPPORT
#endif
```

**Comment by wilx** [comment]
This is a job for distribution packager to decide. what way they want the library to be built. IIRC, other distributions have recently been opting for the C++11.

**Comment by snikulov** [comment]
@wilx No matter what packager decide - now we can get headers and binaries from 1.2.x, which can be inconsistent.
So headers should be less intelligent about enabled options, and reflect actual configuration for the produced library.
IMO, the possible solution is adding an option, and update config for example as follows.

```
#define LOG4CPLUS_HAVE_CXX11_SUPPORT  1

// above define should be generated depending on log4cplus build options
// or #undef LOG4CPLUS_HAVE_CXX11_SUPPORT

#if defined(LOG4CPLUS_HAVE_CXX11_SUPPORT) && ((defined (_MSC_VER) && _MSC_VER < 1600)      \ 
||  __cplusplus < 201103L)
#error "Log4cplus was built with C++11 enabled. You require C++11 compiler to use it"
#endif
```

**Comment by wilx** [comment]
You can patch the headers you distribute. But I do not think log4cplus' build system is the right place to do this.

**Comment by snikulov** [comment]
@wilx you the boss :)

**Comment by snikulov** [comment]
@wilx BTW, the same issue with LOG4CPLUS_WITH_UNIT_TESTS which also leaked into config.hxx (install command on 2.0.x.)
If it passes to the library (enabled by default) this produce segfault in a dependent project in case of Catch UT.
