### ISSUE TITLE
does the configuration file support external appenders ?

### ISSUE THREAD

**Issue by gadh** [log4cplus/log4cplus#267]
can i use external appender from the configuration file or i have to initialize it explicitly in my code ? when i try to use it from the conf file it displays error of "cannot find appenderfactory log4cplus:<my appender>" - but i linked my appender DLL to the app.

**Comment by wilx** [comment]
You can have external appenders. You would have to create a factory class and register it with the system. See, e.g., how [`Qt5DebugAppender`](https://github.com/log4cplus/log4cplus/blob/1.2.x/qt5debugappender/qt5debugappender.cxx#L98-L104) does it.
