### ISSUE TITLE
High system cpu usage when testing asyncappender

### ISSUE THREAD

**Issue by nonly** [log4cplus/log4cplus#270]
Hi, I have some problems with my test;

# **my testing environment** :
2.6.32 linux kernel/ 
centos 6.5 / 
cpu: eight nuclear  && each 2194.916 MHZ /
mem: 4G 

# **my testing method:** 
Asyncappender is used to wrap one rollfileappender, and queue length is 100;
I create four test threads (produce threads) and in fact each thread put logEvets into the queue  in  one loop;

**test code is :**[Omit a lot of details]
```

void* test(void * arg){
....
   Logger::init();
   ....
    for (int i = 0; i < 1000000; ++i){ LOG_INFO(....); pthread_exit(NULL);} 
}

int main(){
   for( int i = 0; i < 4; ++i )
      {
         ret = pthread_create( &tids[i], NULL, test, NULL );
     }
....
  for( int i = 0; i < 4; ++I ){
       pthread_join(...);
   }
 Logger::shutdown();
}

```
# **test results:**
logs can be flushed into disk normally.
but I saw high system cpu usage.
the test process includes five threads: one consumer thread and four producer threads.
consume thread cpu usage is :  95%'
each produce thread cpu usage is : 50%

system call : lseek() and write() are included in consume thread;
system call : futex() is included in produce thread;

that means lots of system call raise high cpu usage??

### # and how can I avoid high system cpu usage?

thank you!

**Comment by wilx** [comment]
Well, both the consumer and producer threads will have to do a lot of work and that means CPU usage.

**Comment by nonly** [comment]
OK, understand.
