### ISSUE TITLE
question: how to print int/long type var in log4cplus 

### ISSUE THREAD

**Issue by nonly** [log4cplus/log4cplus#275]
hi, i find LOG4CPLUS_INFO() or forcedLog() can only support string or const char* variable , how to print int/long variable?

I must transfer those vars to string/char * first?

**Comment by wilx** [comment]
`LOG4CPLUS_INFO()` internally uses a C++ stream, so you can write `double x = 1; LOG4CPLUS_INFO("value::" << x)` or similar. There is also `LOG4CPLUS_INFO_STR()` which takes just a single string and `LOG4CPLUS_INFO_FMT()` which implements `printf` like interface.
