### ISSUE TITLE
memory "leak"

### ISSUE THREAD

**Issue by Oodini** [log4cplus/log4cplus#279]
Hello,  I just arrived on a big project, and I am supposed to resolve a memory problem related to log4cplus. Each time an event is logged, the RAM raises, the message is logged, but the RAM doesn't lower afterwards. So, after some time, the system RAM is exhausted. But when I stop the app, the memory is released.  

It is not easy at all to investigate : the project is huge, and the build complex. I found the guilty instruction (a wrapped call to log4cplus), but I didn't succeed to go farther. I even tried a call to threadCleanup().  

What could explain a such behavior ? Log4cplus is statically linked. By investigating in the code of log4cplus, I saw how the messages are added to the appenders, but I don't see where they are consumed, in order to check if the memory which has been assigned for them is actually freed.  

Thanks for help.

**Comment by wilx** [comment]
It depends on how your application is using log4cplus. If it is using logging macros, the `InternalLoggingEvent` instances are in thread-local storage. If you are using log4cplus as a static library on Windows, you might need to call `threadCleanup()` at the end of your thread's life to free the thread-local storage.

**Comment by Oodini** [comment]
Log4cplus is used as a static library, but in Linux (https://buildroot.org/).  

What is called is :  
void log(spi::InternalLoggingEvent const &) const;

I don't want to clean at the end of my thread. I want to clean regularly during the life of my thread.

Do you confirm that log4cplus doesn't desallocate after the appenders wrote to their stream, except at the end of the thread ?

**Comment by wilx** [comment]
What version of log4cplus?

On *NIX OSes the cleanup should be automatic through callback given to [pthread\_key\_create(3)](https://linux.die.net/man/3/pthread_key_create).

There is currently no way to cleanup the thread-local storage during thread's life. Are you logging some huge amounts of output through a single event instance? That could blow up the thread-local storage memory footprint an it would only be freed on thread's exit.

**Comment by wilx** [comment]
Hmm, technically, calling `threadCleanup()` should free the storage at any point and not just at thread's end of life.

**Comment by Oodini** [comment]
2.0.0 RC1

I log maaaaaaaaaany things, at a fast pace, but each InternalLoggingEvent has a normal size.

Just to be clear : from the user point of view, in a simple sample code, you're talking about the main() thread, right ?

**Comment by Oodini** [comment]
```
void Log4CplusLoggerProcessor::Execute()
{
    // InternalLoggingWrapperEvent is a class derived from log4cplus::spi::InternalLoggingEvent,
    // with just an extra function to format string
    std::vector<InternalLoggingWrapperEvent> eventsToLog;

    // _mustStop is to allow abrupt termination
    while (!_mustStop)
    {
        // _events is an intermediate queue to regulate queue push/pop pace
        while (!_events.empty())
        {
            // Here, we pop 10 items (or less, if queue is smaller)
            _events.pop_front_<10>("Log4CplusLoggerProcessor::Execute()", eventsToLog);
            for (const auto& eventToLog : eventsToLog)
                _logger.log(eventToLog);    //  *** If I comment this line, no problem ! ***

            eventsToLog.clear();
        }

        if (_events.empty())
        {
            // Try to empty thread heap when no events to treat
            log4cplus::threadCleanup();
        }

        std::this_thread::sleep_for(std::chrono::milliseconds(10));
    }
}
```

**Comment by wilx** [comment]
Why do you need a queue to log the events?

Since you are running this on Linux, could you do a test run with Valgring to see where is it actually leaking?

**Comment by Oodini** [comment]
**Answer 1 :** 
It has been to to me it was because the huge quantity of logs didn't allow to satisfy real-time requirements. I have to believe it, for now.

**Answer 2 :**  
I did it. Valgrind told me that the InternalLoggingWrapperEvent allocated in the queue were never deallocated.
But at this time, the pops weren't done in"clusters", and there was only this instruction :

```cplusplus
_logger.log(_events.pop_front());
```
But this Valgind analysis let me puzzled.

The fact is :  
If I comment the call to log4cplus, my memory problem disappears.

**Comment by wilx** [comment]
> It has been told to me it was because the huge quantity of logs didn't allow to satisfy real-time requirements. So the logs had to be buffered. I have to believe it, for now.

Version 2.0.x has pool of threads and can log asynchronously. You just have to add `AsyncAppend=true` property to the appender that you want to log into asynchronously.

> `eventsToLog.clear();`

This does not size down the vector's buffer. It just marks the memory unused and destroys the instances in vector's storage.

**Comment by wilx** [comment]
Also, there is the old `AsyncAppender` that basically does what you do in separate thread.
