### ISSUE TITLE
Does PatternLayout support "generic" conversion identifiers?

### ISSUE THREAD

**Issue by DavidDaabul** [log4cplus/log4cplus#280]
Hi,

I'm trying to use the PatternLayout and attach it to a different pattern string at each appender. The problem I face is that as far as I understand, it doesn't support "generic" identifiers, such %d , %f and %s of printf() function. If I'm wrong, I'll be very happy to get a short explanation \ code example that illustrates how it can be done. If not, it seems to be that I need to extend the code of PattrnConverter class, or InternalLoggingEvent class. I'm not sure whether this is the right way to do it, so if I really need to extend the code and it is possible to get an initial information of what is needed to be extended and how it should be done, I'll be very happy to get this information.

Thanks in advance,
David

**Comment by wilx** [comment]
Conversion specifiers are described in [`PatternLayout`](http://log4cplus.sourceforge.net/docs/html/classlog4cplus_1_1PatternLayout.html) documentation. Generic printf style format specifiers do not make much sense. All of the information the pattern layout has is stored in `InternalLoggingEvent` instance and in the environment (date, time).

The string that you are logging can be formatted in whatever way you want. For convenience, there are macros in `log4cplus/loggingmacros.h` like `LOG4CPLUS_INFO_FMT(logger, ...)`. You can use it as if it was `printf()`: `LOG4CPLUS_INFO_FMT(logger, "%s %d", c_str, 1234);`.

**Comment by DavidDaabul** [comment]
Well, it seems to be that I didn't explain myself clearly enough. I'll try to be more accurate by using an example. 
The codeI need the log for activates several channels in parallel. Each channel gets, among others, name and id, which are set at a configuration file. Whenever I write a message in the context of a specific channel, I need the message to be prefixed by a formatted text, that will contain, for instance, the channel id and the channel name: Suppose the user needs to log the message "This is a test logging message", the message should be logged in the following format: "Test channel | 12 | This is a test logging message" , where "Test channel" and "12" are the channel name and channel id, respectively. These values should be read from the application's configuration (xml) file. Is there a way to do it? how can it be done? 

Thank you very much for your fast response. I really appreciate it.

David

**Comment by wilx** [comment]
There is away to do this with MDC. MDC is per thread, so you either can set it up only once, if your channels are pre thread as well, or you will have to change the values each time you are working with different channel. 

You would add something like `%X{channelName} %X{channelId}` to the `PatternLayout` pattern. Then you would have to set the values into MDC:

```cpp
log4cplus::MDC & mdc = log4cplus::getMDC();
mdc.put(LOG4CPLUS_TEXT("channelName"), someStringVariable);
mdc.put(LOG4CPLUS_TEXT("channelId"), channeldAsString);
```

MDC is available since 1.2.x.

**Comment by DavidDaabul** [comment]
Thank you very much, it works perfectly! 
One more small issue: is it possible to set the width of the field, something similar to the following code:
int i;
cout << setw(10) << i; //or printf ("%10d", i);  

Thanks, 
David

**Comment by DavidDaabul** [comment]
I realized that setting the minimum width of a filed is done  in a similar manner to printf()'s style. Thanks anyway.
