### ISSUE TITLE
question about log4cplus::Logger::shutdown()

### ISSUE THREAD

**Issue by nonly** [log4cplus/log4cplus#281]
my Application scenarios are as follows:
      I Encapsulates a log SDK based on log4cplus. i use asyncappender. my SDK is named A;

      B_SDK will use my A_SDK to print log,  
      Project C will use  B_SDK and also use A_SDK to print log.
      if shutdown is called by B_SDK, after that, Project C will not print all logs . 
      I know if  shutdown() is only called by Project C before C exit, whole log will be printed. 

      so I have two questions:
1)what will it do when calling shutdown()?
 it just erase all appenders from appenderList?

2)is it a must to call shutdown() before the progress exit?

thank you

**Comment by wilx** [comment]
You should call `shutdown()`. The thread that is waiting on internal event queue in `AsyncAppender` will drain the queue before it exits. All enqueued logging messages should be handled before it exits.
