### ISSUE TITLE
Android toolchain files in log4cplus are obsolete

### ISSUE THREAD

**Issue by maichaell** [log4cplus/log4cplus#283]
I'm trying to build log4cplus for Android. It would be really great to make it easy to build for Android too because this is the best logging library there is..

I'm working with Linux environment and I've read instruction from /android/android.toolchain.cmake

```

michael@michael-VirtualBox:~/Downloads/log4cplus-1.2.1-rc2/build$ export ANDROID_NDK=~/Downloads/android-ndk-r15c 

michael@michael-VirtualBox:~/Downloads/log4cplus-1.2.1-rc2/build$ cmake -DCMAKE_TOOLCHAIN_FILE=../android/android.toolchain.cmake ..


CMake Error: Could not find cmake module file: /home/michael/Downloads/log4cplus-1.2.1-rc2/build/CMakeFiles/3.0.2/CMakeCXXCompiler.cmake
CMake Error at CMakeLists.txt:14 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_C_COMPILER to the full path to the compiler, or to the compiler name
  if it is in the PATH.


CMake Error at CMakeLists.txt:14 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_CXX_COMPILER to the full path to the compiler, or to the compiler
  name if it is in the PATH.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
michael@michael-VirtualBox:~/Downloads/log4cplus-1.2.1-rc2/build$ 
```

**Comment by wilx** [comment]
There is a directory `android\scripts` with a bunch of shell scripts that should facilitate compilation with CMake for Android.

**Comment by maichaell** [comment]
Thanks, I'll check that.

**Comment by maichaell** [comment]
No, I got almost same errors when running the script. I did define ANDROID_NDK. But it seems something is still missing. It does not work out-of-the box. I'll try to investigate this.

I wonder if you could try this in Linux at some point ? It's only one script

**Comment by maichaell** [comment]
I updated clang from 3.0 to 3.9 but still errors:

```
michael@michael-VirtualBox:~/Downloads/log4cplus-1.2.1-rc2/android/build_armeabi$ /opt/cmake/bin/cmake -DANDROID_NATIVE_API_LEVEL=android-9 -DANDROID_ABI=armeabi -DCMAKE_TOOLCHAIN_FILE=/home/michael/android-ndk-r15c/build/cmake/android.toolchain.cmake $@ ../..
-- Android: Targeting API '9' with architecture 'arm', ABI 'armeabi', and processor 'armv5te'
-- Android: Selected Clang toolchain 'arm-linux-androideabi-clang' with GCC toolchain 'arm-linux-androideabi-4.9'
CMake Error at CMakeLists.txt:14 (project):
  The CMAKE_C_COMPILER:

    /home/michael/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86/bin/clang

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:14 (project):
  The CMAKE_CXX_COMPILER:

    /home/michael/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86/bin/clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/michael/Downloads/log4cplus-1.2.1-rc2/android/build_armeabi/CMakeFiles/CMakeOutput.log".

```

**Comment by maichaell** [comment]
Looks like cmake has capability to build for Android: https://cmake.org/cmake/help/v3.7/manual/cmake-toolchains.7.html#cross-compiling-for-android

**Comment by maichaell** [comment]
Ok, I have succeeded in compiling with latest NDK-r15c. The toolchain in log4cplus/android directory supports only NDK up to r10. That's why I get strange errors.

For newer NDK simply use toolchain file from NDK like this. You also need cmake version >= 3.6

`michael@michael-VirtualBox:~/Downloads/log4cplus-1.2.1-rc2$ ~/cmake/bin/cmake -DCMAKE_TOOLCHAIN_FILE=/home/michael/android-ndk/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-9
`

... produces this kind of compiler flags:

`-- Compiler flags: -isystem /home/michael/android-ndk/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=9 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  `

if you want more options for Android build you can check them from toolchain file.

**Comment by wilx** [comment]
Is the CMake toolchain file for Android now obsolete since Android ships its own variant of it? If it is, we could document this fact and add a note for older Android users that they still can use the one we ship on their platforms.

**Comment by maichaell** [comment]
Yes, it seems so. You have to find older android sdk to make it build with what is currently included here in log4cplus.

**Comment by wilx** [comment]
So, what do we do about this?

**Comment by wilx** [comment]
Ping.

**Comment by wilx** [comment]
I have removed the entire directory. I assume anyone interested in building log4cplus for Android know what he is doing.
