### ISSUE TITLE
Visual Studio 2017 build fails with missing headers (CMake and converted msvc14 project)

### ISSUE THREAD

**Issue by aaltman** [log4cplus/log4cplus#284]
Hi.  Thanks for your hard work maintaining this.  

I'm on a project that is looking at upgrading our compiler toolchains for modern C++ support.  Moving to the newest Visual Studio on Windows would be nice so that we can get full C++14 support.  

We would probably prefer a CMake build with NMake but may be able to work with a provided Visual Studio solution file.

In 2.0.0-rc2, when I compile from the VS2017 GUI using a converted version of the solution in log4cplus/msvc14, I get:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'ThreadPool.h': No such file or directory	log4cplus	C:\Users\Administrator\Desktop\repos\log4cplus\src\global-init.cxx	35	
Error	C1083	Cannot open include file: 'catch.hpp': No such file or directory	log4cplus	C:\Users\Administrator\Desktop\repos\log4cplus\src\mdc.cxx	28	
Error	C1083	Cannot open include file: 'catch.hpp': No such file or directory	log4cplus	C:\Users\Administrator\Desktop\repos\log4cplus\src\ndc.cxx	27	
Error	C1083	Cannot open include file: 'catch.hpp': No such file or directory	log4cplus	C:\Users\Administrator\Desktop\repos\log4cplus\src\filter.cxx	30	
Error	C1083	Cannot open include file: 'catch.hpp': No such file or directory	log4cplus	C:\Users\Administrator\Desktop\repos\log4cplus\src\property.cxx	46	
Error	C1083	Cannot open include file: 'catch.hpp': No such file or directory	log4cplus	C:\Users\Administrator\Desktop\repos\log4cplus\src\snprintf.cxx	43	
Error	C1083	Cannot open include file: 'catch.hpp': No such file or directory	log4cplus	C:\Users\Administrator\Desktop\repos\log4cplus\src\socketbuffer.cxx	41	
Error	C1083	Cannot open include file: 'catch.hpp': No such file or directory	log4cplus	C:\Users\Administrator\Desktop\repos\log4cplus\src\stringhelper.cxx	34	

Similarly, from a developer command prompt, after a successful CMake build targeting "NMake Makefiles", I get:

C:\Users\Administrator\Desktop\repos\log4cplus\build>nmake

Microsoft (R) Program Maintenance Utility Version 14.11.25508.2
Copyright (C) Microsoft Corporation.  All rights reserved.

[  1%] Building CXX object src/CMakeFiles/log4cplusU.dir/filter.cxx.obj
filter.cxx
C:\Users\Administrator\Desktop\repos\log4cplus\src\filter.cxx(30): fatal error C
1083: Cannot open include file: 'catch.hpp': No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\141
1~1.255\bin\Hostx86\x86\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017
\Professional\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\nmake.exe"' : return cod
e '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017
\Professional\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\nmake.exe"' : return cod
e '0x2'
Stop.

Is this a known issue or is this toolchain not yet supported?

**Comment by wilx** [comment]
Log4cplus Git repository uses submodules. You have to clone it with the submodules as well.
