### ISSUE TITLE
Conan package for log4cplus

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [log4cplus/log4cplus#286]
Hello,
Do you know about Conan package manager? Can you add Conan package for the library and maintain it? Here you can find example of my conan recipe for spdlog: https://github.com/bincrafters/conan-spdlog

**Comment by wilx** [comment]
I am willing to accept reasonable patches that add or modify configuration files necessary for Conan but I am not going to do this myself. I have no use for that myself and I would not be able to test it properly.

**Comment by ZaMaZaN4iK** [comment]
@malirod Yep, i know :-) Will be good, if log4plus's authors will update this recipe every log4plus release.

**Comment by solvingj** [comment]
Bincrafters package for 1.2.1 is currently done, and working.  We have no issue maintaining this one, as the recipe seems ok.  

https://bintray.com/bincrafters/public-conan/log4cplus%3Abincrafters

Feel free to close.
