### ISSUE TITLE
1.2.1 release

### ISSUE THREAD

**Issue by headupinclouds** [log4cplus/log4cplus#289]
The latest release 1.2.1-rc2 is presumably a release candidate.  Are there plans to tag a 1.2.1 release, or is this a stable build?

https://github.com/log4cplus/log4cplus/releases/tag/REL_1_2_1-RC2

**Comment by solvingj** [comment]
Same question. We're currently packaging log4cplus for Conan.io, and 1.2.0 seems to need some patching.  Would prefer to package 1.2.1, but would also prefer it without the RC attached. We have the same question for 2.0.0.  If the timeline is undetermined, or more than a week, may will likely choose to package both RC's for now, and just not package 1.2.0.

**Comment by wilx** [comment]
I have released 1.2.1 few weeks ago. I just forgot to push the tags to repository. It is pushed now.

**Comment by solvingj** [comment]
HA!  Amazing! Thank you.  How about 2.0.0 ?

**Comment by solvingj** [comment]
1.2.1 works great for us btw. thanks again.

**Comment by solvingj** [comment]
This can probably be closed.
