### ISSUE TITLE
Automotive GenIVI DLT appender

### ISSUE THREAD

**Issue by alexandrzvezdin** [log4cplus/log4cplus#290]
Hi,
I am planning to implement GenIVI DLT logging appender for log4cplus. It is popular automotive specific logging infrastructure. Are anybody interested in me to upstream such a specific appender?

**Comment by wilx** [comment]
I think this depends on how complex it is and how many, if any, external libraries it needs to work. If you want to put it into log4cplus repository, then it should be a separate library/binary from the core appenders, unless it is not very complex to implement. If it requires external libraries then it should probably be a separate project repository. I wouldn't be able to test it so maintenance burden would be on you.

**Comment by alexandrzvezdin** [comment]
Ok, thank you. It will require an external library libdlt.so and also a daemon where all log messages are aggregated. Seems better to have a separate repository for that.

**Comment by rpannek** [comment]
Would it still be possible to build it together and have log4cplus as a git submodule for the other repo? Or would the integration be so interwined with the original code that the only way to integrate DLT would be forking the project?

**Comment by wilx** [comment]
[**@rpannek**](https://github.com/rpannek) commented on [Feb 5, 2018, 5:29 PM GMT+1](https://github.com/log4cplus/log4cplus/issues/290#issuecomment-363138702 "2018-02-05T16:29:49Z - Replied by Github Reply Comments"):
> Would it still be possible to build it together and have log4cplus as a git submodule for the other repo? Or would the integration be so interwined with the original code that the only way to integrate DLT would be forking the project?

Personally, it is fine with me. IANAL but I do not see a problem either.

**Comment by rpannek** [comment]
Sorry for not being clear, I didn't mean from a license perspective, the Apache / BSD license makes a fork possible. I just had a quick look at the code structure, etc. and it didn't look to me that one could easily add a new appender from a different git-repo without rewriting parts of this one (there seems not to be any plugin API implemented or something like that), so I wanted to know if you had some tips on how to do that. Forking would be the last resort because it has so many drawbacks.

**Comment by wilx** [comment]
@rpannek See https://github.com/log4cplus/log4cplus/blob/master/qt5debugappender/qt5debugappender.cxx#L103 It shows how you invoke `LOG4CPLUS_REG_APPENDER()` macro to register appender. See https://github.com/log4cplus/log4cplus/blob/master/src/factory.cxx for some more details.

**Comment by rpannek** [comment]
Great! Thanks a lot!
