### ISSUE TITLE
LOG4CPLUS_BUILD_TESTING = 'Off' still requires catch.hpp - on 2.0.0-RC2

### ISSUE THREAD

**Issue by solvingj** [log4cplus/log4cplus#291]
Maybe there's a reason for this, but it's counter-intuitive.  When I tried to run cmake with `LOG4CPLUS_BUILD_TESTING = 'Off'` I get errors including: 

```
     3>C:\.conan\s67xbw\1\source_subfolder\src\filter.cxx(30): fatal error C1083: Cannot open include file: 'catch.hpp'
       : No such file or directory 
```

In theory, would only need the catch submodule if running tests.  Maybe it's not worth all the conditionals it would take to make it that way though.

**Comment by wilx** [comment]
There are tests in `tests/` directory and then there are unit tests that live inside the individual `.cxx` files. To disable the unit tests use `WITH_UNIT_TESTS=Off`. I can see this is not very intuitive.

**Comment by solvingj** [comment]
Ahh, that did the trick. Works for me!
