### ISSUE TITLE
2.0.0-rc2 new threadpool.h dependency

### ISSUE THREAD

**Issue by solvingj** [log4cplus/log4cplus#293]
Since 2.0.0 is still in RC2 and not yet officially released, I wanted to raise this issue to share my opinion about that this particular dependency and give you an opportunity to reconsider it before release.  My feeling is that this dependency is somewhat undesirable, and that you may want to seek an alternative threadpool implementation which is more actively maintained.   Full disclosure, I have the perspective of a downstream packager and not a consumer of the library (yet).  Therefor, my opinion is certainly not the most important, but I also thought that some consumers might have similar feelings about it. 

The `threadpool.h` header seems to be a nice and simple API , and I can understand why you're using a threadpool.  git-submodules are commonplace in OSS dependencies, and we have reasonable ways of working with that.  In most cases, we just package up the submodule from it's upstream repository, and then depend on it in the package manager.  However, in this case, the original library seems to be unmaintained, and very incomplete.  So, you heavily altered the library to shore up bugs, and now you're taking a git-submodule dependency on your own permafork.  This is the undesirable part. 

For our packages, we do https download of your release tarball (as many will do), so `git clone recursive` doesn't get it.   We can't just package up the original threadpool from the author because it's incomplete and unmaintained, and we really don't like to package up permaforks unless they're an officially maintained fork and have clearly become the favored implementation.   Our best option here is to download your permafork of `threadpool.h` from github with the zip download feature within the `log4cplus` build process/download step, and copy it into place. Again, it's totally workable, just messy and undesirable, and I thought you might benefit from hearing a downstream perspective.

**Comment by wilx** [comment]
Well, while you can download zips from GitHub, they are not the mode of distribution of the source that log4cplus uses. They are just a side effect of GitHub use. The actual release tarballs are provided at https://sourceforge.net/projects/log4cplus/files/log4cplus-stable/, including all submodules.

**Comment by solvingj** [comment]
Ok, will use.

**Comment by solvingj** [comment]
Worked thanks very much ! 

I'm not sure if I posted it before, but here's our current version of the package. We will be submitting to "Conan Center" , the moderated public repository for review after a bit of field testing.  If you have an ETA for 2.0.0-rc2 to be official, maybe we can wait for that. 

https://bintray.com/bincrafters/public-conan/log4cplus%3Abincrafters
