### ISSUE TITLE
Version 2.0,How to log Text of Chinese

### ISSUE THREAD

**Issue by zyylvs** [log4cplus/log4cplus#297]
Hi, My log4cplus Version is 2.0,
When I log message like this：
```cpp
LOG4CPLUS_WARN(logger, _T("Hello log4cplus!"));
```
It works OK.
But I also want to log message in Chinese,like this:
```cpp
LOG4CPLUS_WARN(logger, _T("你好 log4cplus!"));
```
It makes error,the Chinese character not display well. 

How can I display message in Chinese?

**Comment by wilx** [comment]
This is rather platform/OS specific. What compiler, what version on what OS are you running this? You have to make sure that the compiler can understand the encoding of the source where your string literal has the Chinese characters. Then you have to make sure that your terminal can output them, etc.

**Comment by wilx** [comment]
Also, what code page are you targeting?

**Comment by zyylvs** [comment]
oh, sorry
OS:Windows 64bit Simplified Chinese;
compiler:VS 2015(msvc14); 
 compiler can understand the Chinese characters. 
my terminal is STDOUT(cmd line) and file.log, they both can output Chinese characters.
encoding of source is UTF-8,

**Comment by zyylvs** [comment]
o,I solve it.
because not set local:
Use this code:
`std::locale::global(std::locale(""));`
`std::wcout.imbue(std::locale(""));`

And the Chinsese log message display will be normal.

@wilx  Thanks a lot.

**Comment by zyylvs** [comment]
Another Problem:
if I make log config by log:
`	//log config by code.

	log4cplus::SharedAppenderPtr _appendCode(new log4cplus::RollingFileAppender(_T("fileRolling.log"), 201 * 1024, 15));
	_appendCode->setName(_T("append for test 5"));
	log4cplus::tstring  patternCode = _T("[%D{%m/%d/%y %H:%M:%S:%q}][%c{2}][%p][%t] %m [%b:%L]%n");
	log4cplus::Layout * _layoutCode = new log4cplus::PatternLayout(patternCode);
	_appendCode->setLayout(std::unique_ptr<log4cplus::Layout>(_layoutCode));
	log4cplus::Logger _loggerCode = log4cplus::Logger::getInstance(_T("test_logger5"));
	_loggerCode.addAppender(_appendCode);
	LOG4CPLUS_WARN(_loggerCode, _T("Testing....你好!"));
	
	//output:
	[02/27/18 12:45:57:547][test_logger5][WARN][6,216] Testing....你好! [main.cxx:73]`

this output correct.

but if config use log4cplus.properties:
`	//log config by log4cplus.properties
	        ConfigureAndWatchThread configureThread(
            getPropertiesFileArgument (argc, argv), 5 * 1000);

		LOG4CPLUS_WARN(log_1, "Testing....你好!");
	
	//output
	02/27/18 13:35:12:769 [11,536] WARN  test.log_1 %% - Testing.... [main.cxx:81]`

this output not correct, Chinese characters not output.

I think this is very strange...

**Comment by wilx** [comment]
The `ConfigureAndWatchThread` waits a bit before it tries to read the file and to configure. Also, it configures only if the file gets modified *after* it has been constructed. Use the `PropertyConfigurator` for initial configuration from file first.

**Comment by zyylvs** [comment]
```PropertyConfigurator``` only load config file at first time. 
If I also want to Use ```ConfigureAndWatchThread``` , What should I do?
