### ISSUE TITLE
Can I log Async and redirect output to a remote machine ?

### ISSUE THREAD

**Issue by RenathoAzevedo** [log4cplus/log4cplus#298]

**Comment by wilx** [comment]
Asynchronous logging is possible. Redirecting to remote machine is possible too but it is a bit complicated. What kind of target/sink for your logs do you envision? 

For asynchronous logging in 2.x there is an `AsyncAppend` property on each appender that, if set to true, will make logging through given appender asynchronous by offloading the logging to a pool of threads.

For older versions there is `AsyncAppender` class that can have other appenders attached and handles all appends through those appenders in separate dedicated thread.

**Comment by RenathoAzevedo** [comment]
It should send log to a remote pc when told to. Can I change config file to apply changes at runtime without having to stop my application ?

**Comment by wilx** [comment]
If you are using `LOG4CPLUS_*()` macros for logging then you will have to provide a formatted string yourself. There is no innate support for QT types in log4cplus.

The `Qt5DebugAppender` is a separate library/DLL. You have to link with it.

**Comment by RenathoAzevedo** [comment]
I couldn't find Qt5DebugerAppender:
`liblog4cplus-1.2.so.5                       liblog4cplusqt4debugappenderU.la
liblog4cplus-1.2.so.5.1.6                   liblog4cplusqt4debugappenderU.so
liblog4cplus-2.0.so.3                       liblog4cplus.so
liblog4cplus-2.0.so.3.1.2                   liblog4cplusU-2.0.so.3
liblog4cplus.la                             liblog4cplusU-2.0.so.3.1.2
liblog4cplusqt4debugappender-1.2.so.5       liblog4cplusU.la
liblog4cplusqt4debugappender-1.2.so.5.1.6   liblog4cplusU.so
liblog4cplusqt4debugappender-2.0.so.3       node_modules
liblog4cplusqt4debugappender-2.0.so.3.1.2   pkgconfig
liblog4cplusqt4debugappender.la             python2.7
liblog4cplusqt4debugappender.so             python3.5
liblog4cplusqt4debugappenderU-2.0.so.3      python3.6
liblog4cplusqt4debugappenderU-2.0.so.3.1.2
`
Could you help me ?
How should I link it?

I'm doing like this on QT : LIBS += -L/usr/local/lib -llog4cplus

One more question, is there no way to log qt types string, date, int ?

**Comment by wilx** [comment]
Give the `configure` script a `--with-qt5` parameter.

**Comment by RenathoAzevedo** [comment]
```
checking for QT5... no
configure: error: Package requirements (Qt5Core >= 5.0.0) were not met:

No package 'Qt5Core' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables QT5_CFLAGS
and QT5_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

Sorry but, How can I fix it?, my Qt is installed at /opt/Qt/5.10.1/gcc_64

**Comment by RenathoAzevedo** [comment]
I got it, So how it work?  I did : 

```
    log4cplus::Initializer initializer;
    log4cplus::PropertyConfigurator::doConfigure("Log4cplusConfig.properties.in");
    log4cplus::Qt5DebugAppender::registerAppender();

   LOG4CPLUS_INFO(loggerMain, "Iniciando");
    qInfo() << "Teste";

```
 it should go to my logfile , isn't it ?

**Comment by wilx** [comment]
You are misunderstanding the purpose of the Qt appenders. They write using Qt's logging and not the other way around.

**Comment by RenathoAzevedo** [comment]
I got it, @wilx is there any example using async logging?, that I Could run, to test and see how it works

**Comment by wilx** [comment]
The [`thread_test`](https://github.com/log4cplus/log4cplus/blob/master/tests/thread_test/main.cxx#L98) shows how to set up the new asynchronous logging that is using internal pool of threads.

The [`performance_test`](https://github.com/log4cplus/log4cplus/blob/master/tests/performance_test/log4cplus.properties.in#L14) shows how to use properties file to set up `AsyncAppender`.
