### ISSUE TITLE
Undefined reference to `log4cplus::Initializer::Initializer()' on Windows

### ISSUE THREAD

**Issue by MSanchesG** [log4cplus/log4cplus#299]
I'm using Windows 10, with MSVS2015 to build log4cplus sln. 

I only opened the SLN in VS and did the build like Release Win32 (I tried Release Unicode too).

I'm trying to use Qt with log4cplus, i configured it like this:
```
win32{
    INCLUDEPATH += ..\log4cplus\include
    LIBS += -L..\log4cplus\msvc14\Win32\bin.Release  -llog4cplus
   #LIBS += -L..\log4cplus\msvc14\Win32\bin.Release_Unicode  -llog4cplusU (Not work too)
}

```
The include paths are all available on the IDE and i can compile my application with the log4cplus headers. But if a try to use any method available in log4cplus i got the "undefined reference" error, below a example calling the Initializer method:

```
release/main.o:main.cpp:(.text+0xd): undefined reference to `log4cplus::Initializer::Initializer()'
release/main.o:main.cpp:(.text+0x24b): undefined reference to `log4cplus::Initializer::~Initializer()'
release/main.o:main.cpp:(.text+0x32b): undefined reference to `log4cplus::Initializer::~Initializer()'
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [release/NewPDV.exe] Error 1
mingw32-make: *** [release] Error 2
```

PS: I forgot to mention that I'm using the version "log4cplus-2.0.0-rc2"

**Comment by wilx** [comment]
Have you been able to fix this issue?
