### ISSUE TITLE
How can I create a custom logger?

### ISSUE THREAD

**Issue by thespykat** [log4cplus/log4cplus#308]
Hello,
I am trying to customize logging functionality in order to implement log level control prior to the actual logging. My system is configured to store the log level threshold in shared memory and I need to read it from there every time something is going to be logged. My first idea was to override LoggerImpl::log function. I tried to use LoggerFactory to create a logger that will use my own LoggerImpl. However, I was able to compile my code only when patching Logger by making my LoggerFactory subclass friend of Logger. And I am not really in favor of the patching option, if possible...
https://github.com/thespykat/log4cplus/commit/bd58b004c940b2af544de2d024901de506f71a14
Am I on the right path? Is there any other way to create a custom logger? Or is there another way to apply log level control at runtime?
Thank you

**Comment by wilx** [comment]
What constitutes the "actual logging" prior to which you want to check log level?

There are at least three places where you can check log level and filter out messages.

1. There is a threshold on Logger itself.
2. There is log level threshold on each Appender and then there are also filters on Appenders that can filter according to log level.
3. And there is also a third threshold on the whole Hierarchy that is checked before Logger's chained log level is determined and checked against Logger's own threshold.

(3) and (1) are checked here:

```cpp
bool
LoggerImpl::isEnabledFor(LogLevel loglevel) const
{
    if(hierarchy.disableValue >= loglevel) {
        return false;
    }
    return loglevel >= getChainedLogLevel();
}
```

(2) is checked in `Appender::isAsSevereAsThreshold()` called from `Appender::syncDoAppend()`.

**Comment by wilx** [comment]
As for creating custom Logger implementations, I think it should be doable. The historical code before my time at least seemed it wanted to support that... Or maybe even does, as I am looking into the code right now. However, I have never tested it. It seems you would have to either use `Hierarchy::getInstance(const tstring& name, spi::LoggerFactory& factory)` manually or you would have to change the default Logger factory by calling `Hierarchy::setLoggerFactory()` with your own `spi::LoggerFactory` instance.

**Comment by wilx** [comment]
As for the run time log level changes, it is possible to change logger log level at run time by calling `setLogLevel()`. The Hierarchy wide threshold can be set using `Hierarchy::disable()`. Changing Appender's threshold is also possible at run time using `Appender::setThreshold()` but Appender instances are not easily accessible at run time.

**Comment by thespykat** [comment]
Thank you for you comments. "actual logging" refers to every time an application prints its logs using the library. 
My problem with LoggerFactory is that if my factory is not a friend of Logger, I get stuck at Logger's private constructor: https://github.com/log4cplus/log4cplus/blob/5aef420f5e59b72702a2e3121f45e547f6f51ff4/include/log4cplus/logger.h#L298
Is this constructor private for a reason? Could it be made public? Or is there any other way I could make my LoggerFactory friend of Logger without having to patch the code?

**Comment by wilx** [comment]
@thespykat Does the change work for you?

**Comment by thespykat** [comment]
It works, thanks a lot for your help! Are you going to merge these changes?

**Comment by wilx** [comment]
Merged.

**Comment by thespykat** [comment]
Thanks a lot! One last question, do you have any estimation for the next log4cplus release?

**Comment by wilx** [comment]
@thespykat I do not have a plan currently. But I guess I could spin one this week for this change.
