### ISSUE TITLE
Where is ThreadPool.h ?

### ISSUE THREAD

**Issue by hgfernan** [log4cplus/log4cplus#311]
Dear all, 

**log4cplus** looks like a great library, that looks simple and easy to use. Unfortunately, I'm facing some problems with its compilation.  And Ubuntu package is too old. 

I'm using an Ubuntu box under Windows 10, and the latest log4cplus won't compile, even after a successful configure. 

After several compilations, it stops complaining about a missing `ThreadPool.h`:
 
`src/global-init.cxx:35:24: fatal error: ThreadPool.h: No such file or directory`

The directory `threadpool` where that file could possibly live, is empty.

Any suggestions ?

**Comment by wilx** [comment]
Dne út 8. 5. 2018 23:42 uživatel hgfernan <notifications@github.com> napsal:

> Dear all,
>
> *log4cplus* looks like a great library, that looks simple and easy to
> use. Unfortunately, I'm facing some problems with its compilation. And
> Ubuntu package is too old.
>
> I'm using an Ubuntu box under Windows 10, and the latest log4cplus won't
> compile, even after a successful configure.
>
> After several compilations, it stops complaining about a missing
> ThreadPool.h:
>
> src/global-init.cxx:35:24: fatal error: ThreadPool.h: No such file or
> directory
>
> The directory threadpool where that file could possibly live, is empty.
>
> Any suggestions ?
>
>
It is a Git submodule. You have to clone and initialize submodules.

>
>

**Comment by hgfernan** [comment]
Thank you, @wilx ! 

I found out your `ThreadPool` version at 
[https://github.com/log4cplus/ThreadPool](https://github.com/log4cplus/ThreadPool)
and was going to update this issue. 

Unfortunately, I'm facing other problems, that maybe are due to my use of an Ubuntu environment in a Windows 10 box. I will try to do the same things at home, in my Debian box, and will get back to you, once the problem is better defined. 

Have a nice 2nd half of the week.
