### ISSUE TITLE
Default context uses default thread value for ThreadPool

### ISSUE THREAD

**Issue by jgornowich** [log4cplus/log4cplus#315]
I am trying to utilize log4cplus for a project that has several running processes under a linux environment and noticed that these tasks are using a large number of threads due to the way the DefaultContext for the library initializes the ThreadPool.  In this application this is not desirable, but these are mutli-threaded applications so using the LOG4CPLUS_SINGLE_THREADED options is not going to work either.  

It looks like the ThreadPool implementation can support configuring this.  Is there a way to configure the size of the ThreadPool that is used by log4cplus?  If there is not would you be open to a PR some kind of AlternateContext that could be used to configure this?

**Comment by wilx** [comment]
Please try and test with log4cplus built from this branch: https://github.com/wilx/log4cplus/tree/master. I have implemented `log4cplus::setThreadPoolSize (std::size_t pool_size)` there.

**Comment by jgornowich** [comment]
I have tried the updates linked in a smaller unit test case, not the actual processes where I first noticed this behavior yet.  In that scope the solution appears to be operating as expected, the ThreadPool size is correctly reduced to the specified values after initially being allocated to the default size.  Before I continued testing these changes, I had a couple follow up questions.  

The threads don't appear to be guaranteed to exit before logging statements can start being processed, I was just concerned there could be a condition where logging statements could be lost?  I did not test that this was possible, you would have better insight into this behavior.

Is it possible to set the size prior to the ThreadPool being created or somehow combined with the `log4cplus::Initializer` call?  This way there is not potentially dozens of threads being created and destroyed during the lifetime.

This is more a question for the ThreadPool library, but do you know why a default value of `std::thread::hardware_concurrency() * 2` was selected?  I want to make sure I am understanding this before I start setting thread sizes that could cause other ramifications.  Mostly I am wondering why it was chosen to double the value?

**Comment by wilx** [comment]
[**@jgornowich**](https://github.com/jgornowich) commented on [Jun 13, 2018, 8:40 PM GMT+2](https://github.com/log4cplus/log4cplus/issues/315#issuecomment-397043184 "2018-06-13T18:40:35Z - Replied by Github Reply Comments"):
> Thanks for the quick feedback!  I have tried the updates linked in a smaller unit test case, not the actual processes where I first noticed this behavior yet.  In that scope the solution appears to be operating as expected, the ThreadPool size is correctly reduced to the specified values after initially being allocated to the default size.  Before I continued testing these changes, I had a couple follow up questions.  
> 
> The threads don't appear to be guaranteed to exit before logging statements can start being processed, I was just concerned there could be a condition where logging statements could be lost?  I did not test that this was possible, you would have better insight into this behavior.

Whatever gets into the thread pool's queue before `stop` is set to `true` will get drained from the queue first before any thread will try to exit. 

> 
> Is it possible to set the size prior to the ThreadPool being created or somehow combined with the `log4cplus::Initializer` call?  This way there is not potentially dozens of threads being created and destroyed during the lifetime.

The best I can offer is implementing override of the initial value using environment variable that you could define prior to starting your process. This is because currently the default context is being initialized by static variable initializer at startup.

However, I could implement configuration file setting/property so that you could have log4cplus configure the thread pool size from `log4cplus.properties` file instead of a direct function call.

> 
> This is more a question for the ThreadPool library, but do you know why a default value of `std::thread::hardware_concurrency() * 2` was selected?  I want to make sure I am understanding this before I start setting thread sizes that could cause other ramifications.  Mostly I am wondering why it was chosen to double the value?

Well, this was implemented when 16 thread CPUs were a lot less common. I guess it is time to re-evaluate the default.

**Comment by jgornowich** [comment]
Sorry for the delayed response.  I was thinking the answer would be that no log statements would be dropped but just did not know for sure.  

I think that both options you offered for dealing with the initial threads are effective solutions.  I think for my particular use case having the ability to set the thread pool size form the `log4cplus.properties` file would be more ideal.

**Comment by jgornowich** [comment]
I noticed that there were some changes for this on commit https://github.com/wilx/log4cplus/commit/224768da37fe2e26eae17ece409930f3f2354c45  
I will give them a try and provide some additional feedback.  Thanks!

**Comment by wilx** [comment]
I think this is now fixed by just released version 2.0.2.
