### ISSUE TITLE
Build in Cygwin

### ISSUE THREAD

**Issue by mallali** [log4cplus/log4cplus#319]
Hi,
I've been struggling  with a build error.  The build breaks during the linking,  at 57%.
Pease help me  build log4cplus on a Cygwin environment. I hope the following info will ring a bell.

```
[ 57%] Linking CXX shared library ../bin/cyglog4cplus-0.dll
CMakeFiles/log4cplus.dir/appender.cxx.o:appender.cxx:(.text$_ZTWN9log4cplus8internal3ptdE[_ZTWN9log4cplus8internal3ptdE]+0x15): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `TLS init function for log4cplus::internal::ptd'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/log4cplus.dir/build.make:1370: bin/cyglog4cplus-0.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: src/CMakeFiles/log4cplus.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

Environment:
- Windows 10
- Cygwin version 2.891
- CMake version 3.6.2
- gcc version 7.3.0 (GCC)
- Log4cplus Latest commit 9362135.

Any help is appreciated.

Kind regards,
Allali

**Comment by wilx** [comment]
Please try [2.0.x-cygwin-cmake-tls-disable](https://github.com/wilx/log4cplus/tree/2.0.x-cygwin-cmake-tls-disable) branch. I have already disable language level TLS for Cygwin some time ago in Autotools build but apparently forgot to do the same for CMake build.
