### ISSUE TITLE
Fails to build on Windows with vs2015

### ISSUE THREAD

**Issue by logieestrada** [log4cplus/log4cplus#324]
Source from master fails to build on Windows with vs2015
Something about missing files
catch.hpp
ThreadPool.h

////
1>------ Rebuild All started: Project: log4cplus, Configuration: Debug Win32 ------
2>------ Rebuild All started: Project: log4cplusS, Configuration: Debug Win32 ------
1>  appender.cxx
1>  callbackappender.cxx
1>  clogger.cxx
1>  configurator.cxx
2>  appender.cxx
2>  clogger.cxx
2>  configurator.cxx
2>  connectorthread.cxx
2>  fileinfo.cxx
1>  connectorthread.cxx
2>  global-init.cxx
1>  fileinfo.cxx
2>  hierarchy.cxx
1>  global-init.cxx
2>  hierarchylocker.cxx
1>  hierarchy.cxx
2>  layout.cxx
2>..\src\global-init.cxx(35): fatal error C1083: Cannot open include file: 'ThreadPool.h': No such file or directory
2>  lockfile.cxx
1>  hierarchylocker.cxx
1>  layout.cxx
1>..\src\global-init.cxx(35): fatal error C1083: Cannot open include file: 'ThreadPool.h': No such file or directory
1>  lockfile.cxx
2>  log4judpappender.cxx
2>  logger.cxx
2>  loggingevent.cxx
2>  loggingmacros.cxx
1>  log4judpappender.cxx
1>  logger.cxx
1>  loggingevent.cxx
1>  loggingmacros.cxx
1>  mdc.cxx
2>  mdc.cxx
1>  ndc.cxx
1>  patternlayout.cxx
2>  ndc.cxx
1>  version.cxx
2>  patternlayout.cxx
1>  asyncappender.cxx
2>  property.cxx
1>..\src\mdc.cxx(28): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
1>  consoleappender.cxx
2>..\src\ndc.cxx(27): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
1>..\src\ndc.cxx(27): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
2>  version.cxx
1>  fileappender.cxx
2>  asyncappender.cxx
1>  nteventlogappender.cxx
2>  consoleappender.cxx
1>  nullappender.cxx
2>..\src\property.cxx(46): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
1>  socketappender.cxx
2>  fileappender.cxx
1>  syslogappender.cxx
2>..\src\mdc.cxx(28): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
1>  win32consoleappender.cxx
2>  nteventlogappender.cxx
1>  win32debugappender.cxx
2>  nullappender.cxx
1>  env.cxx
2>  socketappender.cxx
1>  factory.cxx
2>  syslogappender.cxx
1>  filter.cxx
2>  win32consoleappender.cxx
1>  loggerimpl.cxx
1>  loglevel.cxx
2>  win32debugappender.cxx
1>..\src\filter.cxx(30): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
1>  objectregistry.cxx
1>  rootlogger.cxx
1>  syncprims.cxx
1>  threads.cxx
1>  tls.cxx
1>  appenderattachableimpl.cxx
1>  loglog.cxx
1>  pointer.cxx
1>  property.cxx
1>  queue.cxx
1>  snprintf.cxx
1>  socket-win32.cxx
1>..\src\property.cxx(46): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
1>  socket.cxx
1>..\src\snprintf.cxx(43): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
1>  socketbuffer.cxx
1>  stringhelper-clocale.cxx
1>  stringhelper-cxxlocale.cxx
1>..\src\socketbuffer.cxx(41): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
1>  stringhelper-iconv.cxx
1>  stringhelper.cxx
1>  timehelper.cxx
1>..\src\stringhelper.cxx(34): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
2>  env.cxx
2>  appenderattachableimpl.cxx
2>  loglog.cxx
3>------ Rebuild All started: Project: appender_test, Configuration: Debug Win32 ------
4>------ Rebuild All started: Project: fileappender_test, Configuration: Debug Win32 ------
5>------ Rebuild All started: Project: filter_test, Configuration: Debug Win32 ------
2>  pointer.cxx
2>  queue.cxx
3>  main.cxx
4>  main.cxx
2>  snprintf.cxx
2>  socket-win32.cxx
2>  socket.cxx
2>  socketbuffer.cxx
2>..\src\snprintf.cxx(43): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
2>  stringhelper-clocale.cxx
3>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
6>------ Rebuild All started: Project: hierarchy_test, Configuration: Debug Win32 ------
4>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
7>------ Rebuild All started: Project: loggingserver, Configuration: Debug Win32 ------
2>  stringhelper-cxxlocale.cxx
2>..\src\socketbuffer.cxx(41): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
2>  stringhelper-iconv.cxx
6>  main.cxx
6>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
8>------ Rebuild All started: Project: loglog_test, Configuration: Debug Win32 ------
2>  stringhelper.cxx
7>  loggingserver.cxx
2>  timehelper.cxx
2>  factory.cxx
2>  filter.cxx
8>  main.cxx
2>..\src\stringhelper.cxx(34): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
2>  loggerimpl.cxx
2>..\src\filter.cxx(30): fatal error C1083: Cannot open include file: 'catch.hpp': No such file or directory
2>  loglevel.cxx
7>LINK : fatal error LNK1104: cannot open file 'log4cplusD.lib'
9>------ Rebuild All started: Project: ndc_test, Configuration: Debug Win32 ------
5>  main.cxx
8>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
10>------ Rebuild All started: Project: performance_test, Configuration: Debug Win32 ------
9>  main.cxx
2>  objectregistry.cxx
10>  main.cxx
2>  rootlogger.cxx
9>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
11>------ Rebuild All started: Project: configandwatch_test, Configuration: Debug Win32 ------
5>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
12>------ Rebuild All started: Project: customloglevel_test, Configuration: Debug Win32 ------
11>  main.cxx
10>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
13>------ Rebuild All started: Project: ostream_test, Configuration: Debug Win32 ------
12>  main.cxx
13>  main.cxx
2>  syncprims.cxx
12>  func.cxx
2>  threads.cxx
11>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
14>------ Rebuild All started: Project: priority_test, Configuration: Debug Win32 ------
2>  tls.cxx
12>  customloglevel.cxx
12>  Generating Code...
12>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
15>------ Rebuild All started: Project: socket_test, Configuration: Debug Win32 ------
15>  main.cxx
14>  main.cxx
14>  func.cxx
14>  Generating Code...
13>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
16>------ Rebuild All started: Project: thread_test, Configuration: Debug Win32 ------
14>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
17>------ Rebuild All started: Project: timeformat_test, Configuration: Debug Win32 ------
16>  main.cxx
17>  main.cxx
18>------ Rebuild All started: Project: patternlayout_test, Configuration: Debug Win32 ------
15>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
19>------ Rebuild All started: Project: CLFSAppender, Configuration: Debug Win32 ------
19>  clfsappender.cxx
18>  main.cxx
17>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
20>------ Rebuild All started: Project: Qt4DebugAppender, Configuration: Debug Win32 ------
18>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
21>------ Rebuild All started: Project: MSTTSAppender, Configuration: Debug Win32 ------
20>  qt4debugappender.cxx
21>  msttsappender.cxx
16>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
22>------ Rebuild All started: Project: propertyconfig_test, Configuration: Debug Win32 ------
19>LINK : fatal error LNK1104: cannot open file 'C:\Users\eedwi\projects\oneapp-libraries\log4cplus\msvc14\Win32\bin.Debug\log4cplusD.lib'
23>------ Rebuild All started: Project: Qt5DebugAppender, Configuration: Debug Win32 ------
20>..\qt4debugappender\qt4debugappender.cxx(38): fatal error C1083: Cannot open include file: 'QtGlobal': No such file or directory
22>  main.cxx
23>  qt5debugappender.cxx
23>..\qt5debugappender\qt5debugappender.cxx(38): fatal error C1083: Cannot open include file: 'QtGlobal': No such file or directory
24>------ Rebuild All started: Project: appender_testS, Configuration: Debug Win32 ------
22>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
21>LINK : fatal error LNK1104: cannot open file 'C:\Users\eedwi\projects\oneapp-libraries\log4cplus\msvc14\Win32\bin.Debug\log4cplusD.lib'
25>------ Rebuild All started: Project: configandwatch_testS, Configuration: Debug Win32 ------
26>------ Rebuild All started: Project: customloglevel_testS, Configuration: Debug Win32 ------
27>------ Rebuild All started: Project: fileappender_testS, Configuration: Debug Win32 ------
24>  main.cxx
25>  main.cxx
26>  main.cxx
24>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
28>------ Rebuild All started: Project: filter_testS, Configuration: Debug Win32 ------
27>  main.cxx
26>  func.cxx
25>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
29>------ Rebuild All started: Project: hierarchy_testS, Configuration: Debug Win32 ------
27>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
30>------ Rebuild All started: Project: loglog_testS, Configuration: Debug Win32 ------
29>  main.cxx
26>  customloglevel.cxx
30>  main.cxx
31>------ Rebuild All started: Project: ndc_testS, Configuration: Debug Win32 ------
26>  Generating Code...
31>  main.cxx
29>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
32>------ Rebuild All started: Project: ostream_testS, Configuration: Debug Win32 ------
30>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
33>------ Rebuild All started: Project: patternlayout_testS, Configuration: Debug Win32 ------
32>  main.cxx
33>  main.cxx
26>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
34>------ Rebuild All started: Project: performance_testS, Configuration: Debug Win32 ------
31>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
35>------ Rebuild All started: Project: priority_testS, Configuration: Debug Win32 ------
34>  main.cxx
33>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
36>------ Rebuild All started: Project: propertyconfig_testS, Configuration: Debug Win32 ------
36>  main.cxx
32>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
37>------ Rebuild All started: Project: socket_testS, Configuration: Debug Win32 ------
34>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
38>------ Rebuild All started: Project: thread_testS, Configuration: Debug Win32 ------
37>  main.cxx
38>  main.cxx
36>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
39>------ Rebuild All started: Project: timeformat_testS, Configuration: Debug Win32 ------
39>  main.cxx
38>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
40>------ Rebuild All started: Project: unit_tests, Configuration: Debug Win32 ------
41>------ Rebuild All started: Project: unit_testsS, Configuration: Debug Win32 ------
37>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
40>  unit_tests.cxx
41>  unit_tests.cxx
40>LINK : fatal error LNK1104: cannot open file 'log4cplusd.lib'
39>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
41>LINK : fatal error LNK1104: cannot open file 'log4cplusSd.lib'
========== Rebuild All: 0 succeeded, 41 failed, 0 skipped ==========

**Comment by wilx** [comment]
Have you cloned with `--recurse-submodules`?

**Comment by logieestrada** [comment]
That worked.    Thanks!

**Comment by fmercier** [comment]
Hello,
I just noticed even with 
git clone --recurse-submodules https://github.com/log4cplus/log4cplus
I have to specify the version of Catch.
git checkout Catch1.x

Francois
PS: Thanks for your great job.

**Comment by wilx** [comment]
@fmercier Works for me. I copy-pasted the command from your post above into a command line and this is what I see:

```
~> git clone --recurse-submodules https://github.com/log4cplus/log4cplus
Cloning into 'log4cplus'...
remote: Enumerating objects: 25529, done.
remote: Total 25529 (delta 0), reused 0 (delta 0), pack-reused 25529
Receiving objects: 100% (25529/25529), 22.38 MiB | 17.13 MiB/s, done.
Resolving deltas: 100% (18632/18632), done.
Submodule 'catch' (https://github.com/philsquared/Catch.git) registered for path 'catch'
Submodule 'threadpool' (https://github.com/log4cplus/ThreadPool.git) registered for path 'threadpool'
Cloning into '/$HOME/log4cplus/catch'...
remote: Enumerating objects: 1, done.        
remote: Counting objects: 100% (1/1), done.        
remote: Total 21438 (delta 0), reused 0 (delta 0), pack-reused 21437        
Receiving objects: 100% (21438/21438), 11.54 MiB | 11.16 MiB/s, done.
Resolving deltas: 100% (14623/14623), done.
Cloning into '/$HOME/log4cplus/threadpool'...
remote: Enumerating objects: 170, done.        
remote: Total 170 (delta 0), reused 0 (delta 0), pack-reused 170        
Receiving objects: 100% (170/170), 31.61 KiB | 980.00 KiB/s, done.
Resolving deltas: 100% (85/85), done.
Submodule path 'catch': checked out '15cf3caaceb21172ea42a24e595a2eb58c3ec960'
Submodule path 'threadpool': checked out 'cc0b6371d3963f7028c2da5fc007733f9f3bf205'

~> git --version
git version 2.19.1
```

**Comment by wilx** [comment]
OK. I see what is going on with MSVC...
