### ISSUE TITLE
maybe it's a bug about log4cplus threads

### ISSUE THREAD

**Issue by dingyandangtong** [log4cplus/log4cplus#333]
once it runs "log4cplus::PropertyConfigurator::doConfigure()", many threads (32 threads) will be created, i don't know why, but I tried many times and many solutions, it still creats so many threads.

I used log4cpp before, that's ok, and I want to change to log4cplus recently, but this problem confused me

**Comment by dingyandangtong** [comment]
oh, it's a good news, looking forward......

**Comment by wilx** [comment]
I am closing this as I have released 2.0.2 which should fix the issue.
