### ISSUE TITLE
static library is too bigger

### ISSUE THREAD

**Issue by MasterXiaoPan** [log4cplus/log4cplus#334]
when i use vs2015 to build log4cplusS project, i got debug static unicode version  log4cplusSUD.lib and it‘s size is 35M，release static unicode version log4cplusSU.lib and it’s size is 117M。
  how can i reduce the size of static library size？

**Comment by wilx** [comment]
That is probably because it contains all of the debugging information. Its size does not matter, your linked executable will not have all of it in it.

**Comment by MasterXiaoPan** [comment]
thanks for answer
