### ISSUE TITLE
Output German special characters (non ASCII characters)

### ISSUE THREAD

**Issue by LinaSchad** [log4cplus/log4cplus#335]
Hi there,

I read Issue #306 already, but I don't really get what I have to do to make it work, that non-ASCII characters are being printed correctly. 

I just call: `PropertyConfigurator::doConfigure(LOG4CPLUS_TEXT("log4cplus_configure.ini"));` in my main and the configuration file contains this:

```
log4cplus.logger.hooks = DEBUG, totalLog
log4cplus.logger.events=INFO, totalLog

log4cplus.appender.totalLog=log4cplus::RollingFileAppender
log4cplus.appender.totalLog.MaxFileSize=5MB
log4cplus.appender.totalLog.MaxBackupIndex=5
log4cplus.appender.totalLog.layout=log4cplus::PatternLayout
log4cplus.appender.totalLog.File=total.log
log4cplus.appender.totalLog.layout.ConversionPattern=%d %-5p: %m%n
log4cplus.appender.totalLog.Locale=de-DE
```

Everything works pretty well, just not the representation of non-ASCII characters, but with German using some of them quite often I really need that support. I would appreciate it very much, if you could point me to the solution of my problem :)

Thanks in advance!

**Comment by wilx** [comment]
This is rather highly OS and situation specific, I think. If you are using Visual Studio, you will want to make sure that your [`/source-charset`](https://msdn.microsoft.com/en-us/library/mt708819.aspx) and [`https://msdn.microsoft.com/en-us/library/mt708818.aspx`](https://msdn.microsoft.com/en-us/library/mt708818.aspx) is set to something known and that your source code matches that. You might have to imbue the file appender with specific locale possibly with modified `codecvt` facet that works with the execution encoding.

**Comment by wilx** [comment]
GCC has similar set of flags [`-finput-charset`](https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/Preprocessor-Options.html#index-finput-charset) for source encoding and [`-fexec-charset`](https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/Preprocessor-Options.html#index-fexec-charset) for execution encoding.

**Comment by LinaSchad** [comment]
Awesome, thank you, I didn't know that I could tell Visual Studio to use the right charset. I thought it would be something that has to be defined for the framework :) Thanks a lot!
