### ISSUE TITLE
may i have one question? could log4cplus supports this feature? (descripted detail inside)

### ISSUE THREAD

**Issue by dingyandangtong** [log4cplus/log4cplus#336]
when i use log4cplus, i want the log  rolling based both date and filesize, but it seems these two feature can not be supported simultaneous.

i tried add maxFileSize attribute to DailyRollingFileAppender in configure file, obviously, it does not work.

i found RollingFileAppender and DailyRollingFileAppender class in Fileappender.h, RollingFileAppender class has maxFileSize attribute but DailyRollingFileAppender does not.

so, is it possible supported in future?

**Comment by dingyandangtong** [comment]
sorry, i should type "may i have one MORE question" instead of "may i have one question" : )

**Comment by wilx** [comment]
You are right that combination of time based and size based rolling of log files is not supported. It is not likely it will ever be supported.
