### ISSUE TITLE
ThreadPool deadlock when destructor

### ISSUE THREAD

**Issue by MasterXiaoPan** [log4cplus/log4cplus#338]
- version: 2.0.1
 - environment:  win7， vs2015
 - qt5.10.0

i'm using log4cplus2.0.1 as dynamic link library（dll） in my Qt gui project，
but when i close window（and exit programe），the log4cplus is blocked at threadpool destructor 
`condition_consumers.notify_all();`
and the only way to exit is call TerminateProcess(GetCurrentProcess(), 0);

**Comment by wilx** [comment]
Make sure that you create instance of `log4cplus::Initializer` before you start logging, e.g., as automatic variable, and have it destroyed before your exit `main()`.

**Comment by wilx** [comment]
[**@ReidZheng**](https://github.com/ReidZheng) commented on [6 Sep 2018, 14:20 CEST](https://github.com/log4cplus/log4cplus/issues/338#issuecomment-419072908 "2018-09-06T12:20:04Z - Replied by Github Reply Comments"):
> When I use it on win10 or windows server 2016, it seems all right but when use it on win7, the same problem happened.

Are you using the `log4cplus::Initializer`?

**Comment by ReidZheng** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
Yes，adn I use it as a ptr member variable
 


    On 9/6/2018 20:26，Václav Haisman<notifications@github.com> wrote： 


@ReidZheng commented on 6 Sep 2018, 14:20 CEST:

When I use it on win10 or windows server 2016, it seems all right but when use it on win7, the same problem happened.

Are you using the log4cplus::Initializer?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }

        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }

**Comment by ReidZheng** [comment]
@wilx 

> Are you using the log4cplus::Initializer?

Yes,and I use it as a member ptr variable, delete it  in deconstructor.

**Comment by wilx** [comment]
[**@ReidZheng**](https://github.com/ReidZheng) commented on [Sep 6, 2018, 3:15 PM GMT+2](https://github.com/log4cplus/log4cplus/issues/338#issuecomment-419088808 "2018-09-06T13:15:55Z - Replied by Github Reply Comments"):
> @wilx 
> 
> > Are you using the log4cplus::Initializer?
> 
> Yes,and I use it as a member ptr variable, delete it  in deconstructor.

So, single compiled binary works on Windows 2016 Server but does not on Windows 7?

**Comment by ReidZheng** [comment]
@wilx 

Yes, and if don't use the Initializer.it's deconstructor works rightly on win10 or winserver 2016

**Comment by ReidZheng** [comment]
@wilx 
I wrap the log4cplus in a class without using log4cplus::Initializer,it  works wright on win10/windows server2016, and has the same problem on win7, at last i add a member variable of  log4cplus::Initializer in this class,finally it works right on win7,
Thanks for your help!
