### ISSUE TITLE
NDCMatchFilter - Suggestion

### ISSUE THREAD

**Issue by francky06l** [log4cplus/log4cplus#342]
Hi All,

I needed an NDC matching filter and I created one. Here is the code,  maybe than can be useful for others (maybe as builtin filter) ?

A quick question about the branch 2.0.x, does it matches 2.0.2  and always the latest of 2.0.x series ? 

Thanks
F.
spi/filter.h

```
        class LOG4CPLUS_EXPORT NDCMatchFilter : public Filter
        {
            public:
              // ctors
                NDCMatchFilter();
                NDCMatchFilter(const log4cplus::helpers::Properties& p);

                /**
                 * Returns {@link #NEUTRAL} is there is no string match.
                 */
                virtual FilterResult decide(const InternalLoggingEvent& event) const;

            private:
              // Methods
                LOG4CPLUS_PRIVATE void init();

              // Data
                /** Do we return ACCEPT when a match occurs. Default is <code>true</code>. */
                bool acceptOnMatch;
                /** return NEUTRAL if NDC::get() is empty or ndcToMatch is empty. Default is <code>true</code>. */
                bool neutralOnEmpty;
                log4cplus::tstring ndcToMatch;
        };
```

filter/cxx

>         NDCMatchFilter::NDCMatchFilter()
>         {
>             init();
>         }
> 
>         NDCMatchFilter::NDCMatchFilter(const helpers::Properties& properties)
>         {
>             init();
> 
>             properties.getBool (acceptOnMatch,LOG4CPLUS_TEXT("AcceptOnMatch"));
>             properties.getBool (neutralOnEmpty,LOG4CPLUS_TEXT("NeutralOnEmpty"));
>             ndcToMatch = properties.getProperty(LOG4CPLUS_TEXT("NDCToMatch"));
>         }
> 
> 
>         void NDCMatchFilter::init()
>         {
>             acceptOnMatch = true;
>             neutralOnEmpty = true;
>         }
> 
> 
>         FilterResult NDCMatchFilter::decide(const InternalLoggingEvent& event) const
>         {
>             const tstring& ndcStr = event.getNDC();
> 
>             if(neutralOnEmpty && (ndcToMatch.empty () || ndcStr.empty()))
>             {
>                 return NEUTRAL;
>             }
> 
>             if(ndcStr.compare(ndcToMatch) == 0)
>                 return (acceptOnMatch ? ACCEPT : DENY);
> 
>             return (acceptOnMatch ? DENY : ACCEPT);
>         }
> 

factory.cxx
`    LOG4CPLUS_REG_FILTER (reg3, NDCMatchFilter);
`

**Comment by wilx** [comment]
Done by 28c49089e987eb5c1b24aca7a0b0152ea7e7690c.
