### ISSUE TITLE
Calling the log output function in multithreading environment causes the calling thread to suspend.

### ISSUE THREAD

**Issue by ljx0305** [log4cplus/log4cplus#358]
version: liblog4cplus-1-2-1
operating system: window10 x64
Compiling environment: msys + mingw 4.4
Compliing cmd: $ ./configure --enable-threads=yes

issues:
Compiling the multi-threaded version of the library by Mingw under Windows 10 platform, it is found that calling log output functions such as LOG4CPLUS_TRACE_FMT will cause the calling thread to hang up (similar to the phenomenon of unlocking after locking in threads and re-locking after forgetting to release the lock).

**Comment by wilx** [comment]
I am afraid this is not enough information. Can you get a call stacks of all the threads?
