### ISSUE TITLE
Error Compiling "Log level"-Example in VS2015 with Dynamically Linked Library

### ISSUE THREAD

**Issue by jjochum-ELT** [log4cplus/log4cplus#361]
# Problem Description

I created a new, empty project in Visual Studio 2015 to compile the ["Log Level" example](https://sourceforge.net/p/log4cplus/wiki/CodeExamples/#log-level) mentioned in the documentation.

When using the **statically** linked library by having the following line of code in the source file
`#pragma comment(lib, "log4cplusSUD.lib")`
everything works fine.

Using the **dynamically** linked library by having the following line of code in the source file
`#pragma comment(lib, "log4cplusUD.lib")`
causes an error in the linker:

`Error LNK2001: unresolved external symbol "class std::basic_ostream<wchar_t,struct std::char_traits<wchar_t> > & log4cplus::tcout" (?tcout@log4cplus@@3AAV?$basic_ostream@_WU?$char_traits@_W@std@@@std@@A)`

## Workaround

A workaround to the linker problem is exchanging all occurrences of `log4cplus::tcout` with `std::wcout`, or using the statically bound library.

## Half-Baked Idea of Permanent Solution

I was thinking about somehow redefining `tcout` in one of my header files:

```
#if UNICODE
#include <iostream>

namespace log4cplus
{
	using tcout = std::wcout;
}
#else
#include <iostream>

namespace log4cplus
{
	using tcout = std::cout;
}
#endif
```

but that doesn't work :(:

## Further Information

Development Environment:

 - version: lib4cplus REL_2_0_2 (82de91e0f32e4d)
 - operating system, CPU, bitness: WIN7, x64-CPU? 
 - compiler and its version: Visual Studio Professional 2015 v14.0.25431.01 Update 3
 - log4cplus compiled with profile *Debug_Unicode*
 - My application is using unicode/wchar_t.
 - The error appears when trying to compile a x86 or a x64 application.

**Comment by wilx** [comment]
This should just work. The [`log4cplus::tcout`](https://github.com/log4cplus/log4cplus/blob/2.0.x/include/log4cplus/streams.h#L44) is declared in `streams.h` and defined in [`global-init.cxx`](https://github.com/log4cplus/log4cplus/blob/2.0.x/src/global-init.cxx#L51).

**Comment by jjochum-ELT** [comment]
It does not work for me. Have you tried it on your machine?

**Comment by wilx** [comment]
There are tests project as well. Those, or some of them, use `log4cplus::tcout`, do those compile for you?

**Comment by jjochum-ELT** [comment]
Yes. I can compile all projects in the `log4cplus.sln` provided by your sources, but I don't seem to be able to use your library in a separate solution with a separate project.

I appended a few [images (log4cplus_problem.zip)](https://github.com/log4cplus/log4cplus/files/2585765/log4cplus_problem.zip) showing how I create a new solution with an empty project in **Visual Studio 2015**, add the path to your header and the one of the compiled library files. 
They also show how my test application is compiling and running fine when I add the `log4cplusSUD.lib` dependency and the error thrown when I add the `log4cplusUD.lib` dependency.

Does it work, if you perform theses steps on your PC?

I also added a new project to your `log4cplus.sln` solution for testing purposes. The layout of your solution is completely different to the default layout **Microsoft Visual Studio** is creating. 
I compared the properties of my newly created _MyTestApplication.vcxproj_ and the existing _appender_test.vcxproj_ in **VS2015** and changed all the values in my project to be similar to the _appender_test.vcxproj_. I left the source files in `log4cplus\tests\MyTestApplication` and moved the three project files `MyTestApplication.vcxproj`, `MyTestApplication.vcxproj.filters` and `MyTestApplication.vcxproj.user` to the path `log4cplus\msvc14\tests`, similar to your projects.
I couldn't compile the `main.cxx` that i copied from the _appender_test_ project, even though I added a reference to the `log4cplus` project.
Out of curiousity I opened both `*.vcxproj` files in **Notepad++** with the compare plugin and copied a lot of content from the _appender_test.vcxproj_, until it worked in the end. 

But that can't be the way to do it, or is it!? Did you edit your `*.vcxproj` files manually to get the layout?

**Comment by wilx** [comment]
OK, try defining preprocessor symbol `LOG4CPLUS_BUILD_DLL` in your client application. Looking into `config/win32.h`, that might be the missing piece.

**Comment by wilx** [comment]
@sfzhang See above.

**Comment by sfzhang** [comment]
It works fine after add `LOG4CPLUS_BUILD_DLL`. The macro is not required in gcc.

**Comment by wilx** [comment]
I think this can be closed now.
