### ISSUE TITLE
log4cplus not supporting forking

### ISSUE THREAD

**Issue by LenDJ** [log4cplus/log4cplus#365]
I am trying to use log4cplus in an application (on Linux) that forks a process, only once during startup.  The child process should then use log4cplus. This should technically be possible to do it in a safe way without needing to call exec for the application to work correctly, given that the parent process didn't create any threads beforehand. 
It is however not possible as log4cplus is automatically initialized during loading of the library ( _log4cplus_initializer_func ()) and also because of static initialization of a global _static_log4cplus_initializer variable, which initializes log4cplus and leads to the creation of threads.
This means the initial main process will always be multi-threaded and thus forking without exec is not safe.
This is not good and makes the library not usable for such applications. Is there a real need for this automatic initialization during loading and the static initializer in global-init.cxx? Is it possible to make this optional through a macro?

**Comment by wilx** [comment]
I have merged changes that allow to disable implicit initialization.
