### ISSUE TITLE
Definition of  LOG4CPLUS_CALLER_* does not compile with NVCC in CUDACC mode

### ISSUE THREAD

**Issue by dubvulture** [log4cplus/log4cplus#375]
If I'm correct since version 1.1/1.2 there has been the introduction of `LOG4CPLUS_CALLER_FILE`, `LOG4CPLUS_CALLER_LINE` and `LOG4CPLUS_CALLER_FUNCTION` replacing the standard preprocessor macros `__FILE__`, `__LINE__` and `__FUNCTION__`.

What I find strange is that their current [definition](https://github.com/log4cplus/log4cplus/blob/master/include/log4cplus/config.hxx#L116) relies on gcc>=4.8 and its builtin functions (which should return the same thing afaik).

Is there any motivation behind this?

I'm asking this because including log4cplus inside `.cu` files and compiling with nvcc (8.0.33) + gcc>=4.8 as host compiler leads to undefined `__builtin_*` identifiers

**Comment by wilx** [comment]
The difference between the built-in macros and the built-in functions is that I can use the built-in functions as default arguments of functions. See where the CALLER macros are used. Whereas `__FILE__` would expand to `"logger.h"`, the `__builtin_FILE()` function will return string with, say, `myapp.cpp`.

However, I understand that this might not be supported in NVCC. Maybe something like this would do?

```diff
--- a/include/log4cplus/config.hxx
+++ b/include/log4cplus/config.hxx
@@ -112,7 +112,8 @@
 
 #if defined (__GNUC__) \
     && (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 8)) \
-    && ! defined (__INTEL_COMPILER)
+    && ! defined (__INTEL_COMPILER) \
+    && ! defined (__NVCC__)
 #  define LOG4CPLUS_CALLER_FILE() __builtin_FILE ()
 #  define LOG4CPLUS_CALLER_LINE() __builtin_LINE ()
 #  define LOG4CPLUS_CALLER_FUNCTION() __builtin_FUNCTION ()
```

The [`__NVCC__`](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#nvcc-identification-macro) preprocessor symbol is NVCC compiler identification as per documentation.

**Comment by dubvulture** [comment]
Thanks for the explaination.

Your solution does work indeed but I suggest  instead checking for the `__CUDACC__` symbol since compiling  `.cpp` files with `nvcc`  does not exhibit this problem.

**Comment by wilx** [comment]
> Your solution does work indeed but I suggest instead checking for the __CUDACC__ symbol since compiling .cpp files with nvcc does not exhibit this problem.

OK.
