### ISSUE TITLE
 “catch.hpp”: No such file or directory

### ISSUE THREAD

**Issue by stevenmi** [log4cplus/log4cplus#379]
Describe your problem here.
Visual Studio 2017 build fails with missing headers , “catch.hpp”: No such file or directory
git clone --recurse https://github.com/log4cplus/log4cplus.git
and set che language c++ 17
debug_unicode x64

Also, provide the following information:

 - version: *version of log4cplus that manifest your problem*
the latest

**Comment by fmercier** [comment]
See my comments in https://github.com/log4cplus/log4cplus/issues/324#issuecomment-445845340

**Comment by wilx** [comment]
[**@stevenmi**](https://github.com/stevenmi) commented on [Jan 6, 2019, 9:45 AM GMT+1](https://github.com/log4cplus/log4cplus/issues/379#issue-396240048 "2019-01-06T08:45:00Z - Replied by Github Reply Comments"):
> Describe your problem here.
> Visual Studio 2017 build fails with missing headers , “catch.hpp”: No such file or directory
> git clone --recurse https://github.com/log4cplus/log4cplus.git
> and set che language c++ 17
> debug_unicode x64
> 
> Also, provide the following information:
> 
>  - version: *version of log4cplus that manifest your problem*
> the latest

@stevenmi, @fmercier Try the referenced pull request/patch.
