### ISSUE TITLE
Possible to specify multiple properies file locations

### ISSUE THREAD

**Issue by jgornowich** [log4cplus/log4cplus#382]
Right now I use the log4cplus::ConfigureAndWatchThread to setup logging properties file and watch for changes on some interval.  Is there any existing capability or future feature that would be useful to have a capability of provide a list of files or paths to the watcher to check to be used?

For example, if an application is running with the log4cplus configuration watcher pointed to RO file somewhere and we want to get some extra log level statistics from that instance by turning up the debug we could put a temporary file in some locally accessible place like `/tmp` without have to disturb that RO file that may be shared across instances.

**Comment by wilx** [comment]
No. This is currently not support. Also, the reconfiguration resets the existing configuration. Try setting it up to watch for specific file, it may not exist. Once it pops into existence, it will reconfigure the logging. You would have to copy the RO logging configuration, adjust the logging as you wish and copy it over for the watch dog to pick it up.

**Comment by jgornowich** [comment]
I just want to make sure I understand correctly.  You are saying initially configure the logger with the RO properties file and then setup a ConfigureAndWatchThread thread on the /tmp/ version that may or may not exist?  What happens to the configuration when the /tmp/ configuration file is removed and the original RO should be fallen back to? 

Is it possible to have more than one ConfigureAndWatchThread in an application?

**Comment by wilx** [comment]
[**@jgornowich**](https://github.com/jgornowich) commented on [Jan 31, 2019, 2:38 PM GMT+1](https://github.com/log4cplus/log4cplus/issues/382#issuecomment-459346575 "2019-01-31T13:38:01Z - Replied by Github Reply Comments"):
> I just want to make sure I understand correctly.  You are saying initially configure the logger with the RO properties file and then setup a ConfigureAndWatchThread thread on the /tmp/ version that may or may not exist?
Yes.

>  What happens to the configuration when the /tmp/ configuration file is removed and the original RO should be fallen back to? 

Nothing. You would have to copy the original RO configuration to the /tmp/ and it would get picked up by the watcher thread.

> 
> Is it possible to have more than one ConfigureAndWatchThread in an application?

You can have multiple watchers but they do not combine in any meaningful way. They just reconfigure the entire configuration each.

**Comment by jgornowich** [comment]
I know this has been a couple of months.  But if I provided an PR to change or add a way to input to the `ConfigurationWatchDogThread` a way to supply a `vector<tstring>` of files that would be check in the order provided for existence and then modification would you be interested in it?

**Comment by wilx** [comment]
@jgornowich Well, let's see the patch. Keep the interfaces, only add methods, etc.

**Comment by jgornowich** [comment]
Ok, I will see what I can do in the next few days.  thx

**Comment by jgornowich** [comment]
After looking at the code some more, I don't actually think that this is something to pursue any further.  There are other solutions that can be applied without requiring the log4cplus to do something different.  Suggest just closing this issue.
