### ISSUE TITLE
Compile Error '_get_heap_handle' was not declared in this scope

### ISSUE THREAD

**Issue by ljx0305** [log4cplus/log4cplus#383]
version: log4cplus version 1.2.x branch
operation system: window 10 64bit
CMake Config: default
compiler Info:
Using built-in specs.
Target: mingw32
Configured with: `../gcc-4.4.0/configure --enable-languages=c,ada,c++,fortran,java,objc,obj-c++ --disable-sjlj-exceptions --enable-shared --enable-libgcj --enable-libgomp --with-dwarf2 --disable-win32-registry --enable-libstdcxx-debug --enable-version-specific-runtime-libs --prefix=/mingw --with-gmp=/mingw/src/gmp/root --with-mpfr=/mingw/src/mpfr/root --build=mingw32`
Thread model: win32
gcc version 4.4.0 (GCC) 

issues: 
```
E:\log4cplus-1.2.x\src\global-init.cxx: In function 'void log4cplus::threadCleanup()':
E:\log4cplus-1.2.x\src\global-init.cxx:407: error: '_get_heap_handle' was not declared in this scope
mingw32-make[2]: *** [src/CMakeFiles/log4cplusU.dir/global-init.cxx.obj] Error 1
mingw32-make[1]: *** [src/CMakeFiles/log4cplusU.dir/all] Error 2
mingw32-make: *** [all] Error 2
```

**Comment by wilx** [comment]
This looks like a very old version of original [MinGW](http://mingw.org/), i.e., not [MinGW 64](https://mingw-w64.org/doku.php). I suggest that you use MinGW 64 instead and a recent one.
