### ISSUE TITLE
delete a appender got a segmentation error.

### ISSUE THREAD

**Issue by yinyuhang** [log4cplus/log4cplus#389]
Describe your problem here.

Here's my code that got a segementation error

```cpp
PatternLayout * pLayout = new PatternLayout(LOG4CPLUS_TEXT("%d{%m/%d/%y %H:%M:%S} - %m [%l]%n"));
RollingFileAppender * pAppender = new RollingFileAppender(file, 204800, 10, true);
auto_ptr<Layout> layoutPtr(pLayout);
SharedAppenderPtr appenderPtr(pAppender);
// ........ log code

// After I delete the following two lines, the program works fine.
delete pAppender;
delete pLayout;
```

Is this the design feature of log4cplus or what other causes?

Also, provide the following information:

 - version: *v1.2.2*
 - operating system, CPU, bitness: *Cetnos7.3, 4  Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, and en_US utf-8*
 - `configure` script, or CMake, etc., flags and settings: *default*
 - flags and settings used by your application: *default*
 - compiler and its version: *gcc-c++ v 4.8.5*

**Comment by wilx** [comment]
That is expected. The lifetime of the memory is managed by the `SharedAppenderPtr` and `auto_ptr<>`. You do not need your own `delete`.
