### ISSUE TITLE
access to log4cplus::tstring internal::empty_str causes crash during initialization

### ISSUE THREAD

**Issue by greatgwen** [log4cplus/log4cplus#393]
there are some situations at global initialization that causes a program crash when accessing the empty_str from stringhelper.cxx : log4cplus::tstring const empty_str; 
The global variable empty_str is yet not initialized.
Example locations:
* constructor of Appender
* rolloverFiles in fileappender.cxx
* loggingmacros.cxx: clear_tostringstream (tostringstream & os)
* Properties::get_property_worker (StringType const & key) const

**Comment by greatgwen** [comment]
- version: log4cplus 2.0.3
- operating system: CentOS 7.4, 64 bit
- compiler and its version: gcc (GCC) 7.3.1

**Comment by wilx** [comment]
What's the call stack of such crash? You are not supposed to use log4cplus API before `main()`.
