### ISSUE TITLE
access to static strings in loglevel.cxx causes crash during initialization

### ISSUE THREAD

**Issue by greatgwen** [log4cplus/log4cplus#394]
there are some situations at global initialization that causes a program crash when accessing the static strings described below:
The following static variables are yet not initialized when calling defaultLogLevelToStringMethod, defaultStringToLogLevelMethod and LogLevelManager::toString:

static tstring const ALL_STRING (LOG4CPLUS_TEXT("ALL"));
static tstring const TRACE_STRING (LOG4CPLUS_TEXT("TRACE"));
static tstring const DEBUG_STRING (LOG4CPLUS_TEXT("DEBUG"));
static tstring const INFO_STRING (LOG4CPLUS_TEXT("INFO"));
static tstring const WARN_STRING (LOG4CPLUS_TEXT("WARN"));
static tstring const ERROR_STRING (LOG4CPLUS_TEXT("ERROR"));
static tstring const FATAL_STRING (LOG4CPLUS_TEXT("FATAL"));
static tstring const OFF_STRING (LOG4CPLUS_TEXT("OFF"));
static tstring const NOTSET_STRING (LOG4CPLUS_TEXT("NOTSET"));
static tstring const UNKNOWN_STRING (LOG4CPLUS_TEXT("UNKNOWN"));

- version: log4cplus 2.0.3
- operating system: CentOS 7.4, 64 bit
- compiler and its version: gcc (GCC) 7.3.1

**Comment by wilx** [comment]
What's the call stack of such crash? You are not supposed to use log4cplus API before main().

**Comment by wilx** [comment]
Ping.
