### ISSUE TITLE
No Example for syslogappender in tests folder

### ISSUE THREAD

**Issue by mrunmayi29** [log4cplus/log4cplus#395]
Describe your problem here.

Also, provide the following information:

 - version: *version of log4cplus that manifest your problem*
 - operating system, CPU, bitness: *what are your environement's OS, CPU's, and platform's characteristics*
 - `configure` script, or CMake, etc., flags and settings: *what setting have you used to compile log4cplus outside of defaults*
 - flags and settings used by your application: *what are the settings and comipler flags used by your application, are they compatible with those used for log4cplus compilation*
 - compiler and its version: *what compiler and what versions are you using to compile log4cplus and your application*

I am using log4cplus-1.2.1, I need to use SyslogAppender class to send logs to remote syslog.
I did not find any example for SyslogAppender in tests folder.  Can you please tell me if there is any example? Or how can I use this class for remote logging? I need to create a new class, inside that class I need to initialize syslogAppender, store hostname and then create a new function to send the logs.

**Comment by wilx** [comment]
See the header. It is pretty self-explanatory. You can configure log4cplus with properties or manually add all the appenders.

**Comment by mrunmayi29** [comment]
yes, I am trying that. I am using visual studio 2017, it gives errors when I build log4cplus project using "Release x64". Is there any way I can build this library and use it in my application?
