### ISSUE TITLE
Using logging macro with FMT variant and passing va_list as argument

### ISSUE THREAD

**Issue by thorodi** [log4cplus/log4cplus#397]
Hello,

I'm using log4cplus version 2.03. This is from the version.h file:

```cpp
//! This is log4cplus version number as a string.
#define LOG4CPLUS_VERSION_STR LOG4CPLUS_MAKE_VERSION_STR(2, 0, 3)
```

I have created a wrapper to the log4cplus class and I want to allow printing log messages with arguments ( something like printf). I tried to pass the list of arguments to the log4cplus FMT variant macros (for example LOG4CPLUS_INFO_FMT) using va_list type but get invalid data printed.

Is this the right way to pass arguments to the logger?

This is the code I'm using:

```cpp
void printmessage(const char* msg, ...) {
        va_list arg;
	va_start(arg, msg);
	LOG4CPLUS_INFO_FMT(*logger_, msg.c_str(), arg);
        va_end(arg);
}
```

I would appreciate your help.

Thank you and best regards,
Tali

**Comment by wilx** [comment]
The macro is intended to be used directly with formatting string and arguments. If you have your own variadic function, you don't need the macro.

**Comment by thorodi** [comment]
Thank you for the quick response.
Could you point me then to the right log4cplus api which I can use that will work with va_list arguments?
I need to implement in my wrapper class the function LogMessage which can be used as follows:
logger->LogMessage(INFO, "fooManager function %s return value is %d ", "func", 3);

Thanks,
Tali

**Comment by wilx** [comment]
There is no such API on `Logger`. You could re-use the `snprintf_buf` for formatting. You can then use `Logger::log()` to log that formatted string.

**Comment by thorodi** [comment]
Thanks.
Actually I'm really new at this.
Could you send me some code sample as a reference to what I need?

Thank you,
Tali

**Comment by wilx** [comment]
See how `snprintf_buf` does it.
