### ISSUE TITLE
How to actively close the specified logger object in the program

### ISSUE THREAD

**Issue by ljx0305** [log4cplus/log4cplus#398]
I want to close the useless logger object manually in the program, but there is no corresponding method in the library.

**Comment by wilx** [comment]
There is no point doing that. The idea is that the set of loggers is finite so there is no need to "close" them.

**Comment by ljx0305** [comment]
Now I'm making a network communication software, which needs to store the content of communication interaction for each network connection. For example, after the socket connection is closed, its corresponding logger object also needs to be released and always exists. Will it cause memory or file descriptor to be occupied all the time?

**Comment by wilx** [comment]
You are doing it wrong. You should not have separate logger for each connection. There are other ways how to add information to log to distinguish individual connections. You can use [MDC](https://log4cplus.sourceforge.io/docs/html/classlog4cplus_1_1MDC.html) or [NDC](https://log4cplus.sourceforge.io/docs/html/classlog4cplus_1_1NDC.html) facilities. Use appropriate placeholder in [layout pattern](https://log4cplus.sourceforge.io/docs/html/classlog4cplus_1_1PatternLayout.html).

**Comment by ljx0305** [comment]
I want to save a separate log file for every link on the server side, while MDC and NDC store all link log files in a log file, which is not convenient for viewing log information.

**Comment by wilx** [comment]
I am afraid that's outside the scope of what log4cplus can do.
