### ISSUE TITLE
Question regarding programmatically create loggers

### ISSUE THREAD

**Issue by cumafo** [log4cplus/log4cplus#400]
As an example I need two loggers, one logging only to console and one logging to both console and a file.
Is the following a correct way to programmatically achieve that?
- create two logger instances, “log_console” and “log_all”
- create one console appender and add it to both loggers.
- create one file appender and add it only to the “log_all” logger.
Thx
Curt

**Comment by wilx** [comment]
I am assuming those loggers are not in parent-child relationship. Using only one console appender and adding it to both loggers is good practice.

**Comment by cumafo** [comment]
OK.
Is it then also possible to create a logger with some appenders, then derive a new logger from that and add another appender to the latter? How do I do that?

**Comment by wilx** [comment]
I am not sure what you mean by "derive". The loggers form a hierarchy similarly to how directories work and, unless you turn it off, they are additive. This means that if you log something in logger "A.B.C" then attempts are made to use any appenders in "A.B.C", in "A.B", in "A", and in root logger.

**Comment by cumafo** [comment]
what I mean is having a logger(1) with appenders ABC, how then create a logger(2) that "inherits" (1) and adding an D appender to (2). 
Logging to (1)  goes to appenders ABC, while logging to (2) goes to ABCD.
As I understand it, I can create two independent loggers and add (same) appender instances to both, but is there a more elegant/efficient way of achieving the same result?

**Comment by wilx** [comment]
I do not understand what "inherits" means to you. Attempt is made to use any appender on any logger on path from the logger to root logger, as I have described previously.

**Comment by cumafo** [comment]
I'm sorry not being able to explain, but how do I create a path (hierarchy) of loggers?
As in your first reply: "I am assuming those loggers are not in parent-child relationship"

**Comment by wilx** [comment]
You simply use the logger by name with dot separated names. E.g., "com.github.log4cplus" could be a logger name.
