### ISSUE TITLE
armhf (v6) / armv7 fails test 58 in v2.0.4

### ISSUE THREAD

**Issue by tcely** [log4cplus/log4cplus#407]
armhf and armv7 CI builds failed.

The build logs (and testsuite.log output) can be found at:

https://cloud.drone.io/alpinelinux/aports/1346/4/1

Also, provide the following information:

 - version: 2.0.4
 - operating system, CPU, bitness: AlpineLinux armhf / armv7
 - `configure` script, or CMake, etc., flags and settings: https://github.com/alpinelinux/aports/blob/a8151b0138a1bc6c3584ad29754342a1fabc2dfc/testing/log4cplus/APKBUILD
 - compiler and its version: gcc (Alpine 8.3.0) 8.3.0

**Comment by wilx** [comment]
I am sorry but I cannot help much with that. I do not have access to those platforms and other platforms seem to work just fine.

**Comment by wilx** [comment]
The current APKBUILD builds all architectures. I am closing this.
