### ISSUE TITLE
Using log4cplus in debug x64 mode, some linker error happens, but library configuration in vs2017 is good.

### ISSUE THREAD

**Issue by jozhuzhu** [log4cplus/log4cplus#409]
Recently, I wanna use log4cplus project within my project. Here comes the background
1. The target is to generate a dll using log4cplus.dll
2. I tried to use log4cplus.dll (which is compiled in Release x64 mode), but when the program load the dll, the whole program halt for a long time. It seemed that the dll corrupted when it was loaded. But the dll generation process is good.
3. I tried to use log4cplusD.dll (which is compiled in Debug x64 mode), but surprisely, vs2017 gave me some linker error as following:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "class std::basic_ostringstream<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > & __cdecl log4cplus::detail::get_macro_body_oss(void)" (?get_macro_body_oss@detail@log4cplus@@YAAEAV?$basic_ostringstream@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@XZ) referenced in function "public: void __cdecl AiLog::debuglog(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?debuglog@AiLog@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	DLLPlace	D:\gitwork\C++\DLLPlace\DLLPlace\ailog.obj	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "void __cdecl log4cplus::detail::macro_forced_log(class log4cplus::Logger const &,int,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,char const *,int,char const *)" (?macro_forced_log@detail@log4cplus@@YAXAEBVLogger@2@HAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@PEBDH2@Z) referenced in function "public: void __cdecl AiLog::debuglog(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?debuglog@AiLog@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	DLLPlace	D:\gitwork\C++\DLLPlace\DLLPlace\ailog.obj	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: static void __cdecl log4cplus::PropertyConfigurator::doConfigure(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class log4cplus::Hierarchy &,unsigned int)" (?doConfigure@PropertyConfigurator@log4cplus@@SAXAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@AEAVHierarchy@2@I@Z) referenced in function "private: __cdecl AiLog::AiLog(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (??0AiLog@@AEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	DLLPlace	D:\gitwork\C++\DLLPlace\DLLPlace\ailog.obj	1	
```
I feld confused, I used to have an exe project in vs2017. With the help of the log4cplus.dll (which is compiled in Release x64 mode), I can achieve my logging module. 
#### The same program worked well with log4cplus.dll in exe project, but failed with log4cplusD.dll, telling me the same error as above.

Therefore, I doubt that the error in Debug mode could possibly cause the corruption of dll loading with log4cplus.dll

Grateful for any suggestion~

 - version: log4cplus 2.0.3
 - operating system, CPU, bitness: WINDOWS 10 64bits, CPU: Intel i5-8250U
 - `configure` script, or CMake, etc., flags and settings: 
 - flags and settings used by your application: /std:c++17
 - compiler and its version: using vs2017

**Comment by wilx** [comment]
This looks like a confusion between non-Unicode and Unicode variants. Generally, new projects in Visual Studio define the `UNICODE` and `_UNICODE` preprocessor macros. Log4cplus uses that to switch the headers to declare APIs with `wchar_t` strings. Try using the `log4cplusDU` or `log4cplusU` DLLs.

**Comment by jozhuzhu** [comment]
i see. It is the reason why log4cplus.dll can work but log4cplusD.dll can't.
However, I found the program keeps halting if i use my logging module which will use log4cplus.dll or log4cplusD.dll. I tried to remove logging module from my project, it can continue.
Could you do me a favor?

**Comment by wilx** [comment]
I don't do favours. If you have a stuck process, you will have to run it under debugger and obtain a call stack. There is nothing I can do from here.

**Comment by jozhuzhu** [comment]
OK, thanks a lot for the quick reply
