### ISSUE TITLE
%i => syscall(SYS_gettid)

### ISSUE THREAD

**Issue by BrentHuang** [log4cplus/log4cplus#410]
I found %i is getpid() on Linux in multi-threads process. They are the same value for all threads, so 
it's inconvenient to distinguish them refer to the 'top' command.

![Selection_006](https://user-images.githubusercontent.com/2862064/56200810-1e283300-6072-11e9-83a9-36755e3418df.png)

 - version: 2.0.2

I think it might be syscall(SYS_gettid).

**Comment by wilx** [comment]
The `%i` is process ID. If you want thread ID, use either `%t` or `%T`. You probably want `%T`.

**Comment by BrentHuang** [comment]
yes, I test %T is right.

thank you very much~

Also, I think the thread id of %t output should be hexadecimal， just like gdb 'info threads' command.
in file log4cplus-2.0.2/src/threads.cxx, change the line
        tmp << impl::getCurrentThreadId (); 
to    tmp << std::hex << std::showbase << impl::getCurrentThreadId ();

I think that will be better.
