### ISSUE TITLE
log4cplus:ERROR Failed to create locale DEFAULT

### ISSUE THREAD

**Issue by izzyreal** [log4cplus/log4cplus#412]
version: 2.0.0 (via [this conan package](https://github.com/bincrafters/conan-log4cplus))
Windows 10, English
Character set: unicode

I have application `A` depending on static library `B`, both are my own projects. When including log4cplus with `A`, I can instantiate log4cplus without problems like this:
```
	log4cplus::Initializer initializer;
	log4cplus::BasicConfigurator config;
	config.configure();
	logger = log4cplus::Logger::getRoot();
```
I'm trying to get `B` to also include log4cplus, but when I run the same code block in one of `B`'s class constructors, I get:
```
log4cplus:ERROR Failed to create locale DEFAULT
```
I also tried running only the `getRoot()` line, but I get the same error.

How should I include log4cplus in both `A` and `B`? What am I missing here? I don't understand the locale thing, as I haven't explicitly set up anything locale-related for `A` and it just worked. Is there a different way to setup log4cplus within a static library?

**Comment by wilx** [comment]
The static library should not be trying to set up log4cplus. Only the application should. Don't try to use log4cplus before you enter `main()`.

When log4cplus is initialized, it also initializes a registries of objects, one of which is the locale registry. See [`initializeLog4cplus()`](https://github.com/log4cplus/log4cplus/blob/a492be2318ccacf84eeaa9d6b5d0f7ede9d0d6ea/src/global-init.cxx#L522) and [`initializeFactoryRegistry()`](https://github.com/log4cplus/log4cplus/blob/2.0.x/src/factory.cxx#L170).

The error message seems to come from [`fileappender.cxx`](https://github.com/log4cplus/log4cplus/blob/0abd281c7c9492ff0f4f5d66185dff2532173a7e/src/fileappender.cxx#L212). For some reason we do not print the exception message there. Maybe we should. Try to edit the code to print it or use a debugger to find out what is the exception.

**Comment by izzyreal** [comment]
Many thanks @wilx, I'll follow your suggestions and report back here.

**Comment by izzyreal** [comment]
Sorry, completely lousy analysis on my side, jumped the gun there. The locale error came from instantiating `FileAppender` before running:
```	log4cplus::Initializer initializer;
	log4cplus::BasicConfigurator config;
	config.configure();
	auto logger = log4cplus::Logger::getRoot();
```
