### ISSUE TITLE
Documentation for configure --enable-threads seems to be wrong

### ISSUE THREAD

**Issue by neundorf-sr** [log4cplus/log4cplus#413]
Hi,

the help for the --enable-threads option of the configure script seems to be wrong:

```
--enable-threads        Use this option to create a singled-threaded version
                          of this library [default=yes]
```

I think it is just the other way round.
If I use --enable-threads=yes (which is indeed the default), I get:

```
configure: Creating a multi-threaded library.
configure: Threads support:
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
```

If I use --enable-threads=no, I get:
```
configure: Creating a single-threaded library
checking for gmtime_r... yes

```

**Comment by wilx** [comment]
I agree that the description text could be reworded to be less confusing and maybe should explicit mention `--disable-threads`.

**Comment by neundorf-sr** [comment]
I think for --enable-threads it should say "create a thread-safe version" or "create a multi-threaded version" or "create a version to be used in multi-threaded code" version of log4cplus.
Actually I'm not quite sure what the switch does exactly.

**Comment by wilx** [comment]
It is supposed to avoid linking in thread support library, avoid trying to create any threads, and avoid locking primitives. It is a little bit useful if you just want to use it in your simple single-threaded command-line tool.
