### ISSUE TITLE
No effect of log4cplus.threadPoolSize on Linux 

### ISSUE THREAD

**Issue by fmercier** [log4cplus/log4cplus#420]
Hello,
When a program using log4cplus is executed, 32 threads are used for ThreadPool even when in the configuration file the value thread pool is set to 2.

The configuration file contains:
 `log4cplus.threadPoolSize=2`
And if I observe the process I can see
`pstack <pid>| grep -c "wait<progschj::ThreadPool::emplace_back_worker"`
32

for a total of 35 threads (+ main)
`pstree -p <pid>| wc -l`
35

Do I miss use the configuration ?

 - version: 2.0.2
 - operating system, CPU, bitness: Linux REHL 7.3 /32 CPU Little Endian/Intel Xeon/Hyperthreads 2

**Comment by wilx** [comment]
It should just work as far as I can see: https://github.com/log4cplus/log4cplus/commit/224768da37fe2e26eae17ece409930f3f2354c45

The workers are created but they should exit when you configure log4cplus.

**Comment by fmercier** [comment]
So 2 questions:
* How these worker should exit to use corectlly the configuration of log4cplus ?
* Why not specifying a smaller value e.g ` std::unique_ptr<progschj::ThreadPool> thread_pool {new progschj::ThreadPool(2)}; ` instead of using std::thread::hardware_concurrency which use half of the processor on large CPU configuration ?

**Comment by wilx** [comment]
I have merged a change to 2.0.x branch which sets the starting thread pool size to 4.
