### ISSUE TITLE
The latest version need C++17 supported 

### ISSUE THREAD

**Issue by wlhj131** [log4cplus/log4cplus#427]
refer to the title.
Latest commit 4b774f5  
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

**Comment by wilx** [comment]
I am sorry but I do not understand what is this issue about. Yes, master branch is C++17 based. What about it?

**Comment by wilx** [comment]
I am closing this as for no response.

**Comment by wlhj131** [comment]
I'm sorry that I missed the email. My question is the README file of version 4b774f5 don't mention C++17, but actually it need this feature. I see the README was updated recently, so there is no problem now. Thanks!

**Comment by wilx** [comment]
It says so at the top of the README.md:

> log4cplus is a simple to use C++17 logging API providing thread--safe, flexible, and arbitrarily granular control over log management and configuration. It is modeled after the Java log4j API.
