### ISSUE TITLE
PGP signing key not available

### ISSUE THREAD

**Issue by echarlie** [log4cplus/log4cplus#430]
Releases for 2.0.4 as hosted on github are signed with PGP key of type EDDSA 0x892D26B9E52B9D86ACAB4CA67A58D93704D5CB06. I cannot find this key on the public sks keyserver pool (not that many of them work anyway) or keys.openpgp.org, or anywhere in the wiki or release notes.

This key should be widely publicised if you're going to bother signing releases at all! Also, EDDSA is a not-great choice of key algorithm over RSA4096, since neither Cent/RHEL 6 or 7, nor Debian 8 (as far as I know) support ECC keys.

 - version: 2.0.4
 - operating system, CPU, bitness: *Cent6 amd64*
 - `configure` script, or CMake, etc., flags and settings: *N/A*
 - flags and settings used by your application: *N/A*
 - compiler and its version: *N/A*

**Comment by wilx** [comment]
I had issues finding working key servers last few years. I did not even know keys.openpgp.org existed. I have uploaded my key there (https://keys.openpgp.org/search?q=0x892D26B9E52B9D86ACAB4CA67A58D93704D5CB06). Please try to download it again.

As for the change of the signing key, I am disinclined to change the type. The support for ECC keys is in GnuPG since circa 2014.

**Comment by wilx** [comment]
Weird. I tried to verify locally from downloaded files and do not seem to have the public key either. That's odd.

**Comment by wilx** [comment]
Never mind. I thought `gpgv` was the thing to use to verify the signature but that does not seem to work for me. Only if I do `gpg --verify` it works for me.

**Comment by echarlie** [comment]
The caveat of keys.openpgp.org is that it does user ID redaction by default, which breaks gnupg (it cannot import the key into it's keyring. c.f. https://dev.gnupg.org/T4393). Thus you need to verify your key's email using their upload tool (e.g. `gpg --export $KEYID |  curl -T - https://keys.openpgp.org`, follow the link, and validate the UID emails that you want to publish), otherwise people will be able to *update* your key, but not import it if they don't already have it.

https://keys.openpgp.org/debug?q=892D26B9E52B9D86ACAB4CA67A58D93704D5CB06 shows what info they publish, compare to my own pgp key: https://keys.openpgp.org/debug?q=B2F41D360340F41AE0B2841773AC5687477EB9EE

**Comment by wilx** [comment]
I see. Well, what do you think would be the best approach. Add the public key to the GitHub wiki page?

**Comment by wilx** [comment]
I forgot I have already done that. See <https://github.com/log4cplus/log4cplus/wiki>.

**Comment by echarlie** [comment]
As long as it's clearly stated in the release notes or README or wherever that the key is there, I think that's sufficient. `keys.opepgp.org` is nice-to-have, but isn't what people should rely on (same with keyservers).

As a side-note, I imported that key and was able to verify a copy of the tarball I have sitting around, so the main text of the issue is definitely satisfied.
