### ISSUE TITLE
StringMatchFilter doesn't seem to work for AIX 7.2

### ISSUE THREAD

**Issue by NogaAv** [log4cplus/log4cplus#432]
I am running my application that uses the **Log4cplus-1.2.1** on **AIX 7.2 XLC 13.x compiler**.
I configured the logger to send logs to SYSLOG appender with the filter option to filter log messages by a specific string, using the following configuration:

**log4cplus.appender.SYSLOG.filters.1=log4cplus::spi::StringMatchFilter
log4cplus.appender.SYSLOG.filters.1.StringToMatch= MyString
log4cplus.appender.SYSLOG.filters.1.AcceptOnMatch=true
log4cplus.appender.SYSLOG.filters.2=log4cplus::spi::DenyAllFilter**

But this filter does not filter the log messages that contain the string, and instead the log file displays all log messages sent by my application.

When using that same configuration on Windows O.S , the filter works fine and only log messages containing my chosen string are displayed.

I wish to understand why the filter doesn't work for AIX compiler?
Is there something wrong with my configuration? or does the Log4cplus code should be compiled in a certain way to adjust it to AIX compiler?

**Comment by wilx** [comment]
I am afraid I do not know what is going on. Is it possible that the C++ standard library used by XLC is significantly different or incompatible? The filter itself is fairly trivial:

```cpp
FilterResult
StringMatchFilter::decide(const InternalLoggingEvent& event) const
{
    const tstring& message = event.getMessage();

    if(stringToMatch.empty () || message.empty ()) {
        return NEUTRAL;
    }

    if(message.find(stringToMatch) == tstring::npos) {
        return NEUTRAL;
    }
    else {  // we've got a match
        return (acceptOnMatch ? ACCEPT : DENY);
    }
}
```

I don't see why it should not work on AIX. I am afraid you will have to try and debug this yourself.

**Comment by wilx** [comment]
@NogaAv Have you managed to find out what was the issue?

**Comment by NogaAv** [comment]
The specific configuration I used for the SYSLOG appender on my AIX machine was with the 'Async' version of the appender, and as I mentioned- the appender did not filter the log messages that contained the string to filter.
When I converted the appender to a Sync appender (removed the Async addition from the configuration) then the filter did work as expected.
