### ISSUE TITLE
autotools generated files should not be included in the repository

### ISSUE THREAD

**Issue by keithmendozasr** [log4cplus/log4cplus#436]
While compiling log4cplus on an Ubuntu 18.04 environment I got an error about autotools-1.16; hinting at autotools-generated files are included in the repo. Here's the output of `git status` after I ran `autoreconf -f -i -s` (-s forced symlinking installed files triggering the "typechange" to identify most--if not all--the autotools files):

```
modified:   Makefile.in
modified:   aclocal.m4
typechange: ar-lib
typechange: compile
typechange: config.guess
typechange: config.sub
modified:   configure
typechange: depcomp
modified:   include/Makefile.in
modified:   include/log4cplus/config.h.in
typechange: install-sh
typechange: ltmain.sh
typechange: m4/libtool.m4
typechange: m4/ltoptions.m4
typechange: m4/ltsugar.m4
typechange: m4/ltversion.m4
typechange: m4/lt~obsolete.m4
typechange: missing
typechange: mkinstalldirs
typechange: py-compile
```

Also, provide the following information:

 - version: git tag REL_2_0_4
 - operating system, CPU, bitness: Ubuntu 18.04.3 Intel x64
 - `configure` script, or CMake, etc., flags and settings: Just autoreconf as shown above
 - flags and settings used by your application: *what are the settings and comipler flags used by your application, are they compatible with those used for log4cplus compilation*
 - compiler and its version: g++ 7.4.0

**Comment by wilx** [comment]
There is a script [`scripts/fix-timestamps.sh`](https://github.com/log4cplus/log4cplus/blob/master/scripts/fix-timestamps.sh) which makes sure you can build the checked out sources.

**Comment by keithmendozasr** [comment]
I saw scripts/fix-timestamps.sh; however, that means that log4cplus is not being built with whatever code/commands/functions/features are available from the autotools version that's available in the environment it's being built on. Now, I will admit that I've yet to encounter a breaking change between autotools version that would absolutely require autoreconf before a software can be rebuilt.

**Comment by wilx** [comment]
Any maintainer/packager for specific OS can always figure out how to regenerate the configuration. There is even the `doautoreconf.sh` script which allows you to override the specific tools.
