### ISSUE TITLE
[error: undefined reference to `log4cplus::Logger::getDefaultHierarchy()'] When use with Qt

### ISSUE THREAD

**Issue by Judy166** [log4cplus/log4cplus#449]
The IDEs I used are 
- Microsoft Visual Studio Community 2019(used to create .lib)
- Qt Creator 4.10.0 ( based on Qt 5.13.1 (MSVC 2017, 32bit) (use the .lib)

I have tried every group that I can think of, just as bellow

> VS: Debug+Win32   ----------------  Qt: Desktop MinGW 32bit
> VS: Debug_Unicode+Win32   ------  Qt: Desktop MinGW 32bit
> VS: Debug+x64   --------------------  Qt: Desktop MinGW 64bit
> VS: Debug_Unicode+x64  -----------  Qt: Desktop MinGW 64bit

meanwhile I have tried the bellow all two projects
![image](https://user-images.githubusercontent.com/53285041/67076220-4c243680-f1bf-11e9-928d-f99f196ddcc9.png)

most of the groups show warnings and errors as bellow(when used with Qt)

![image](https://user-images.githubusercontent.com/53285041/67076811-7de9cd00-f1c0-11e9-971e-e256f6292fc9.png)

![image](https://user-images.githubusercontent.com/53285041/67076884-a70a5d80-f1c0-11e9-95e6-7e836b891301.png)

the code as bellow
![image](https://user-images.githubusercontent.com/53285041/67076682-3cf1b880-f1c0-11e9-8b65-9c3ca3966196.png)
![image](https://user-images.githubusercontent.com/53285041/67076718-4d099800-f1c0-11e9-8b13-50a12d37d3c6.png)

**Comment by Judy166** [comment]
I could use log4cplusSUD.lib  with VS projects successful.
The IDE i really use with work is Qt, i cannot use  log4cplusSUD.lib successful with Qt
I have tried two different versions of Qt. The warnings and errors just as the same

**Comment by wilx** [comment]
You need to use the same compiler for both your application and log4cplus.

Dne pá 18. 10. 2019 10:07 uživatel Judy166 <notifications@github.com>
napsal:

**Comment by Judy166** [comment]
how to compiler log4cplus by Qt

**Comment by wilx** [comment]
Doesn't Visual Studio 2019 support multiple toolsets? You might be able to use existing log4cplus Visual Studio projects but with changes toolset. You would have to do that manually. Alternatively, you should be able to use CMake build with whatever Visual Studio compiler you need.

**Comment by Judy166** [comment]
Very Thanks for your reply.


I will study multiple toolsets right away.
I have study how to use log4cplus with qt for nearly one week.
today i just begin learn CMake.
But it is really one newthing for me just as multiple toolsets.
The information I could found on internet looks not very use for me.
I will specifically appreciate you if you&nbsp;could say more about how to complile with multiple toolsets.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Václav Haisman"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 下午2:42
收件人:&nbsp;"log4cplus/log4cplus"<log4cplus@noreply.github.com&gt;;
抄送:&nbsp;"moainei"<811023965@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [log4cplus/log4cplus] [error: undefined reference to `log4cplus::Logger::getDefaultHierarchy()'] When use with Qt (#449)




Doesn't Visual Studio 2019 support multiple toolsets? You might be able to use existing log4cplus Visual Studio projects but with changes toolset. You would have to do that manually. Alternatively, you should be able to use CMake build with whatever Visual Studio compiler you need.
