### ISSUE TITLE
Openbsd build

### ISSUE THREAD

**Issue by dohnuts** [log4cplus/log4cplus#451]
Which library

ThreadPool.h

is supposed to come from ?

`libtool: compile:  /usr/bin/c++ -DHAVE_CONFIG_H -I./include -I./threadpool -I./include -I./catch/single_include/catch2 -DCATCH_CONFIG_PREFIX_ALL=1 -DNDEBUG -DINSIDE_LOG4CPLUS -D_GNU_SOURCE=1 -D_REENTRANT -g -O2 -Wall -fdiagnostics-color=auto -Wextra -pedantic -Wstrict-aliasing -Wstrict-overflow -Woverloaded-virtual -Wold-style-cast -Wc++14-compat -Wundef -Wshadow -Wformat -Wno-variadic-macros -fvisibility=hidden -MT src/liblog4cplus_la-global-init.lo -MD -MP -MF src/.deps/liblog4cplus_la-global-init.Tpo -c src/global-init.cxx  -fPIC -DPIC -o src/.libs/liblog4cplus_la-global-init.o
src/global-init.cxx:44:10: fatal error: 'ThreadPool.h' file not found
#include "ThreadPool.h"
         ^~~~~~~~~~~~~~
1 error generated.
`

https://github.com/vit-vit/ctpl ?
https://courses.cs.washington.edu/courses/cse333/11sp/sections/section09_files/ThreadPool.h.html ?
Boost maybe ?

**Comment by wilx** [comment]
There are Git submodules in the log4cplus repository. You have to clone with `--recursive` or initialize the submodules some other way.

**Comment by dohnuts** [comment]
thank you.
maybe put a note in INSTALL instead of the README ?
