### ISSUE TITLE
error LNK2001: unresolved external symbol "public: __cdecl log4cplus::CallbackAppender::CallbackAppender

### ISSUE THREAD

**Issue by icegull** [log4cplus/log4cplus#455]
Describe your problem here.

1. Pull the code from:
SHA-1: fe3d648e1bc553b51b752707000ff74fb9bf4969
* Merge pull request #450 from solicomo/=-in-sub-ini-file-path
Support "=" in sub-config file path

2. Use VS2019 16.4 to open the solution, update the whole project to VS2019

3. Change the C++ language to ISO C++17 Standard (std:c++17) in VS2019

4. compile the static lib "log4cplusS"

5. after I use it in an vs2019 test demo, I have this error:
error LNK2001: unresolved external symbol "public: __cdecl log4cplus::CallbackAppender::CallbackAppender(void (__cdecl*)(void *,wchar_t const *,wchar_t const *,int,wchar_t const *,wchar_t const *,unsigned __int64,unsigned long,wchar_t const *,wchar_t const *,int),void *)" 
(??0CallbackAppender@log4cplus@@QEAA@P6AXPEAXPEB_W1H11_KK11H@Z0@Z)

The code of 2.0.4 works good without this issue. Could you help me to solve it so I can update my project. Thank you very much.

Also, provide the following information:

 - version: the code from:
SHA-1: fe3d648e1bc553b51b752707000ff74fb9bf4969
* Merge pull request #450 from solicomo/=-in-sub-ini-file-path
Support "=" in sub-config file path

 - operating system, CPU, bitness: Win10 1909, AMD Ryzen 1950X

 - `configure` script, or CMake, etc., flags and settings: VS2019 16.4 compile the static lib "log4cplusS"
 - flags and settings used by your application: None
 - compiler and its version:  VS2019 16.4

**Comment by wilx** [comment]
The name `log4cplusS` suggests that you are trying to use the non-UNICODE build of log4cplus but your demo application build is defining the `UNICODE` (or `_UNICODE`) preprocessor symbol which changes the declarations to use `wchar_t`. Please build with configuration with `Unicode` in their name and use `log4cplusUS` library to link to.

**Comment by icegull** [comment]
I do built log4cplusS with "Release_Unicode", and I link the "log4cplusSU.lib" to my test project which in "Release" with unicode enabled too. But link failed...
So I guess I miss something? Thanks for your reply.

**Comment by icegull** [comment]
@wilx Hello? Could you help to solve this issue please? Thank you very much.

**Comment by wilx** [comment]
The issue was that the source file was missing from the log4cplusS Visual Studio project. I will wait for the pull request to build on Appveyor before merging this.

**Comment by wilx** [comment]
Please check out 2.0.x branch and rebuild. This should fix your issue.

**Comment by icegull** [comment]
@wilx Thanks for your work. It works.
