### ISSUE TITLE
use log4cplus::Layout.  attempting to reference a deleted function

### ISSUE THREAD

**Issue by solowolf** [log4cplus/log4cplus#462]
appender->setLayout(std::unique_ptr<log4cplus::Layout>(new log4cplus::SimpleLayout));

=> build error.

“std::unique_ptr<log4cplus::Layout,std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)”: attempting to reference a deleted function

**Comment by solowolf** [comment]
env: vs2015 x64

**Comment by solowolf** [comment]
need static function.

**Comment by solowolf** [comment]
There are many problems in upgrading from 1.2

**Comment by wilx** [comment]
I am reading https://en.cppreference.com/w/cpp/memory/unique_ptr/unique_ptr and I don't see why it shouldn't work. Do you have any idea?

**Comment by wilx** [comment]
Oh, I think I see it. Well, you need to create `unique_ptr` and give it to the `setLayout()` method:

```cpp
virtual void setLayout(std::unique_ptr<Layout> layout);
```

**Comment by dongnong** [comment]
use std::move() like std::move(std::unique_ptr<log4cplus::Layout>(new   log4cplus::SimpleLayout()))  can solve it
