### ISSUE TITLE
RollingFileAppender recreating deleted files

### ISSUE THREAD

**Issue by WeiYan-Lynn** [log4cplus/log4cplus#467]
- version: 2.0.4
The log4cplus used in my project is configured with the rollingfileappender method to write logs. 
In this way, the log will be generated by scrolling, and the current log will be the same as my configured name. In this case, if I delete the log with suffix (old log), the business function will not be affected, but if I delete the log currently in use, it is expected that a new current log will be generated and the content to be written will be written, but in fact, a new current log will not be generated, except that the size has exceeded the configured maximum threshold.
So, Is there any way to recreate the file and keep writing the logs into the log file without affecting current business？

Best regards

**Comment by wilx** [comment]
The log file is kept open. If you delete the file the file handle will still be kept open but there will just be no directory entry for the file, effectively keeping the file hidden. For your use case to work we would have to close&re-open the log file for each logging event. That seems excessive. Or, we could try to `stat(2)`  the file and re-open the file if it cannot be found. 

In any case, your use case is not implemented and would require changes.

**Comment by WeiYan-Lynn** [comment]
Thank you for your reply. 
I hope later versions can support this function.
I will close the issue. Thanks again
