### ISSUE TITLE
Compile log4cplusS error in VS2019 16.5.4 in Debug_Unicode mode

### ISSUE THREAD

**Issue by icegull** [log4cplus/log4cplus#468]
Describe your problem here.
Compile log4cplusS error in VS2019 16.5.4 in Debug_Unicode mode, but compile success in Release_Unicode.

The compile error msg is:
log4cplus\threadpool\ThreadPool.h(116,1): error C4996: 'std::result_of<log4cplus::enqueueAsyncDoAppend::<lambda_8f3be6c1acd39b2f3ef78a727d87fbc7> (void)>': warning STL4014: std::result_of and std::result_of_t are deprecated in C++17. They are superseded by std::invoke_result and std::invoke_result_t. You can define _SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning. (compiling source file ..\src\global-init.cxx)

Also, provide the following information:

 - version: *version of log4cplus that manifest your problem*
Revision: 3b9d98fb5fd72298745cf21620ace8f2b6d770ad
Author: Václav Haisman <vhaisman@gmail.com>
Date: 2019/12/19 9:51:21
Message:
Merge pull request #459 from wilx/pseiderer-ps-devel-fix-check-for-libaries-001

 - operating system, CPU, bitness: *what are your environement's OS, CPU's, and platform's characteristics*
Win10 with VS2019 16.5.4 

 - `configure` script, or CMake, etc., flags and settings: *what setting have you used to compile log4cplus outside of defaults*
VS2019 16.5.4 
 - flags and settings used by your application: *what are the settings and comipler flags used by your application, are they compatible with those used for log4cplus compilation*
None
 - compiler and its version: *what compiler and what versions are you using to compile log4cplus and your application*
VS2019 16.5.4

**Comment by camnv93** [comment]
Hi bro. Can you build this project on visual studio 2019 and windows 10 ?

**Comment by icegull** [comment]
> Hi bro. Can you build this project on visual studio 2019 and windows 10 ?

I'm already on it. Windows 10+ VS2019 16.5.4

**Comment by camnv93** [comment]
> 
> 
> > Hi bro. Can you build this project on visual studio 2019 and windows 10 ?
> 
> I'm already on it. Windows 10+ VS2019 16.5.4

Thank bro. I have successfully build on version log4cplus-2.0.5

**Comment by wilx** [comment]
I think this was fixed by recent update of Catch testing framework. Please test with 2.0.6. I will close this issue but feel free to reopen it if it is still reproducible.

**Comment by wilx** [comment]
I initially misunderstood the issue you were reporting. I think this finally gets fixed by #499.

**Comment by icegull** [comment]
@wilx Thanks for the fixing. Cheers.
