### ISSUE TITLE
Proper error-handling on log4cplus initialization  

### ISSUE THREAD

**Issue by atari83** [log4cplus/log4cplus#469]
Hello there,
What is proper way for error handling in log4cplus initializing process ? (for example to make sure if config file is accessible and its content could be parse with no issue)

Currently I used this:
    try {
        ::log4cplus::initialize();
        ::log4cplus::PropertyConfigurator::doConfigure(g_OCSApp_conf->log_cfg);
        logger_ = log4cplus::Logger::getInstance(LOG4CPLUS_TEXT("OCSApp"));
    } catch (...){
        fprintf( stderr, "Error on loading Log-config file: %s", g_OCSApp_conf->log_cfg );
        return -1;
    }

Please let me know your inputs. 
Thanks.

 - version: 2.0.4
 - operating system, CPU, bitness: FreeBSD 12.1 amd64
 - compiler and its version: Clang++ 10

**Comment by Crisliu7** [comment]
have the same problem, even though the doConfigure() throws a std::runtime_error, it cannot be caught correctly

**Comment by wilx** [comment]
> have the same problem, even though the doConfigure() throws a std::runtime_error, it cannot be caught correctly

Why can't it be caught correctly?

**Comment by Crisliu7** [comment]
> > have the same problem, even though the doConfigure() throws a std::runtime_error, it cannot be caught correctly
> 
> Why can't it be caught correctly?

see my problem here https://github.com/log4cplus/log4cplus/issues/553

**Comment by wilx** [comment]
Fixed in 2.1.0.
