### ISSUE TITLE
Using log4cplus without macros

### ISSUE THREAD

**Issue by sthlm58** [log4cplus/log4cplus#471]
Can log4cplus be used directly through the functions exposed from the library (instead of macros)?

In our project we have our own logging macros defined. They are invoking some custom logging functions of our own. Now, we would like to implement our functions in terms of e.g. `log4cplus::detail::macro_forced_log(...)`, but that's the thing... it is a `detail`. 

I'd like the ask about the recommendation of *how* to do it? Can I use the `detail`? Is there any plan to provide a public functions instead of just macros?

I understand that for ABI stability reasons the only option would to potentially add new functions without modifying existing ones (at least for 2.x)?

**Comment by wilx** [comment]
The macros are only a convenience. You can use the `Logger` directly and implement your own logging on top of that.

The functions used by the macros should be pretty stable API. The macros aren't going to disappear and neither will the supporting functions. Worst case (which is extremely unlikely) you can implement their function yourself and use them in your own macros.

**Comment by sthlm58** [comment]
Okay, got it. I'll use the `Logger`. 

Thanks!
