### ISSUE TITLE
File appender without a configuration file

### ISSUE THREAD

**Issue by guteksan** [log4cplus/log4cplus#474]
How can I configure ```log4cplus``` to log to a file, but without providing configuration INI file?

I tried this:
```cpp
log4cplus::Initializer initializer;
log4cplus::helpers::Properties props;
props.setProperty("log4cplus.rootLogger", "ALL,MyAppender");
props.setProperty("log4cplus.appender.MyAppender", "log4cplus::FileAppender");
props.setProperty("log4cplus.appender.MyAppender.File", "test_output.log");
log4cplus::PropertyConfigurator conf(props);
conf.configure();
```
but when I run my application, I always get:
```
log4cplus:ERROR No appenders could be found for logger (Provider).
log4cplus:ERROR Please initialize the log4cplus system properly.
```

**Comment by wilx** [comment]
This should work. Are you trying to call it from context where it is called before your do your initialization?

**Comment by guteksan** [comment]
Problem solved. My Initializer and PropertyConfigurator were inside a constructor of a test Fixture in boost tests, so it was destroyed.
