### ISSUE TITLE
Documentation for users needs to be prioritied much higher

### ISSUE THREAD

**Issue by sldr** [log4cplus/log4cplus#475]
Its great that you use Doxygen but you need to do something for the users of your API and for the end users that will want to configure the logging (that don't know how to read code to get the answer).

Please consider adding more detailed help with more examples for properties files. What I find at https://log4cplus.sourceforge.io/docs/html/classlog4cplus_1_1PropertyConfigurator.html#a21e8e6b1440cc7a8a47b8fd14c54b239 states "Refer to the setOption method in each Appender and Layout for class specific options.". Guess what their is no setOption method! In the Doxygen for RollingFileAppender their is no help. OK, lets try Doxygen for FileAppender, or FileAppenderBase again their is no help. Lets get current stable (2.0.5). You have added some help to FileAppenderBase but not about properties files.

While I can go read the code and figure it out because I am a developer I can't tell my users to "go read the code" so I am left with having to write my own documentation, tell my users not to use it and it becomes a tool that only I (or other developers) can use, or just pull log4cplus out.

Please consider adding more detailed help with more examples. The properties file is a great way to configure log4cplus and I am using it but it would be so much nicer if it was documented better. I hate having to search the web for other properties file examples to find help and then resorting to reading the code if I can't find it on the web.

 - version: 1.2.0 (what I am on), 2.0.5 (what I also checked for more help and doc)
 - operating system, CPU, bitness: Windows 64bit, Linux 64bit, Mac 64bit
 - `configure` script, or CMake, etc., flags and settings: VS2019 to DLL for Windows
 - flags and settings used by your application: Properties files for configuration
 - compiler and its version: VS2019 for Windows, don't know for Linux, & Mac

**Comment by Const-me** [comment]
@wilx Right now, no documentation is available whatsoever. These links are all HTTP 404. Even worse, someone disabled access by archive.org robot, so there’re no saved copies.

**Comment by wilx** [comment]
I am moving the documentation from SF to GitHub Pages. See https://log4cplus.github.io/log4cplus/
