### ISSUE TITLE
Make error on windows MSYS2

### ISSUE THREAD

**Issue by BlueClouDragon** [log4cplus/log4cplus#476]
I am using msys2 on windows and need to install this log4cplus package.
I downloaded the git repository and run following command

./configure
make

![image](https://user-images.githubusercontent.com/37393004/87161919-c66d8b80-c2f7-11ea-8328-6c15926e442c.png)

I got this error. I tried many times, but the same issue
I tried to clone with --recurse-submodules and ./configure CXXFLAGS="-std=c++17". but same error on make command

Thanks to your attention and please inform me of the solution for this error.

**Comment by wilx** [comment]
Using `./configure` on Windows with MinGW is not supported. This is in README.md:

> On Windows, it depends on compiler and tool-chain that you want to use. When using Visual Studio, use Visual Studio solution and project files. However, CMake build system should still work and produce useful results. **When using some form of MinGW64 tool-chain, the CMake build system is considered primary and the Autotools based build system is unsupported. Use the MinGW Makefiles option and build with mingw-make (or similar). The MSYS Makefiles option is untested and unsupported.**

**Comment by BlueClouDragon** [comment]
Thanks for your reply. So I can't use log4cplus on msys2?

**Comment by wilx** [comment]
You can use it but you just have compile it with CMake with MinGW Makefiles instead of with the MSYS Makefiles option.

**Comment by BlueClouDragon** [comment]
thanks. I will try with mingw64 shell
