### ISSUE TITLE
RollingFileAppender linux inode reuse

### ISSUE THREAD

**Issue by qinzhenyi1314** [log4cplus/log4cplus#477]
use RollingFileAppender  MaxBackupIndex=10 
after file greater than 10 I find inode reuse
**eg:**
2020-08-11 13 clock
  File: IVU_obj0.log.2
  Size: 20971563        Blocks: 40976      IO Block: 4096   regular file
Device: 821h/2081d      **Inode: 40370236**    Links: 1

2020-08-11 21 clock
  File: IVU_obj0.log
  Size: 8829505         Blocks: 17256      IO Block: 4096   regular file
Device: 821h/2081d      **Inode: 40370236**    Links: 1
but i see  delete the oldest file ，so ask for help~
fileappender.cxx ->rolloverFiles -> file_remove

**config：**
log4cplus.logger.SVR_MSGS=DEBUG, SVR_MSGS
log4cplus.appender.SVR_MSGS=log4cplus::RollingFileAppender
log4cplus.appender.SVR_MSGS.MaxFileSize=20MB
log4cplus.appender.SVR_MSGS.MaxBackupIndex=10
log4cplus.appender.SVR_MSGS.File=/data/workspace/Common/mutual/log/IVUSvr.log
log4cplus.appender.SVR_MSGS.layout=log4cplus::PatternLayout
log4cplus.appender.SVR_MSGS.layout.ConversionPattern=%D:%d{%Q}	%p	%t	%l	%m%n
log4cplus.appender.SVR_MSGS.filters.1=log4cplus::spi::LogLevelRangeFilter
log4cplus.appender.SVR_MSGS.filters.1.LogLevelMin=TRACE
log4cplus.appender.SVR_MSGS.filters.1.LogLevelMax=FATAL
log4cplus.appender.SVR_MSGS.filters.1.AcceptOnMatch=true
log4cplus.appender.SVR_MSGS.filters.2=log4cplus::spi::DenyAllFilter

log4cplus.logger.ARMY_MSGS=DEBUG, ARMY_HID
log4cplus.appender.ARMY_HID=log4cplus::RollingFileAppender  
log4cplus.appender.ARMY_HID.MaxFileSize=20MB
log4cplus.appender.ARMY_HID.MaxBackupIndex=10
log4cplus.appender.ARMY_HID.File=/data/workspace/Common/mutual/log/IVU_obj0.log
log4cplus.appender.ARMY_HID.layout=log4cplus::PatternLayout
log4cplus.appender.ARMY_HID.layout.ConversionPattern=%D:%d{%Q}	%p	%t	%l	%m%n
log4cplus.appender.ARMY_HID.filters.1=log4cplus::spi::LogLevelRangeFilter
log4cplus.appender.ARMY_HID.filters.1.LogLevelMin=TRACE
log4cplus.appender.ARMY_HID.filters.1.LogLevelMax=FATAL
log4cplus.appender.ARMY_HID.filters.1.AcceptOnMatch=true
log4cplus.appender.ARMY_HID.filters.2=log4cplus::spi::DenyAllFilter

**Comment by wilx** [comment]
I don't understand what problem do you see. Why is it a problem if an inode gets re-used later?

**Comment by wilx** [comment]
In any case, I don't think there is anything I can do. The rollover does use normal file operations like renaming.

**Comment by qinzhenyi1314** [comment]
1. I need scan log  based on inode not filename because file rotate，inode reuse  will confuse me Is this a historical file or a current one~
2. I see rolloverFiles use file_remove to delete the oldest file, does you know the detail what happened after that~
I search a lot, but there was no result,so ask for help~

**Comment by wilx** [comment]
The files have names that clearly indicate the current log file and the old log files. I do not see why you would need to use inodes for that. Either way, I can't help you with this. This is out of the control of the library.

**Comment by qinzhenyi1314** [comment]
ok，thinks~
