### ISSUE TITLE
the {:x} come out is negative

### ISSUE THREAD

**Issue by chllcy** [log4cplus/log4cplus#485]
HRESULT hr = DXGI_ERROR_WAIT_TIMEOUT;//#define DXGI_ERROR_WAIT_TIMEOUT          (0x887A0027L)
    spdlogger->info(" result: {:x}.", hr);

but the log come out is -7785FFD9? how can I change to 887A0027

**Comment by wilx** [comment]
What formatter is that? I don't think log4cplus itself supports this formatting backend.

**Comment by wilx** [comment]
According to the docs, `HRESULT` is `LONG`. Maybe just casting it to `ULONG` would be enough to get the unsigned hexadecimal result?
