### ISSUE TITLE
Is log4cplus guaranteed to print log messages sequentially?

### ISSUE THREAD

**Issue by sdynan-r7** [log4cplus/log4cplus#488]
When I log to an appender, is message 1 guaranteed to appear **before** message 2?

```
LOGDEBUG("Message 1");
LOGDEBUG("Message 2");
. . .
[2020-11-18,10:22:35.090][8140][DEBUG][file.cpp:1] Message 1
[2020-11-18,10:22:35.090][8140][DEBUG][file.cpp:2] Message 2
```

Because I just saw this log output from this C++ code. (attached files). And I'm hoping for an explanation, even if it is my own stupidity. Thanks.

The json being parsed was `{\"hash\":\"\"}`

[sequential_logging.zip](https://github.com/log4cplus/log4cplus/files/5561212/sequential_logging.zip)

__________
Release build of app + log4cplus lib.
latest log4cplus from GitHub, consumed as a static lib.
Windows 10 x64
Visual C++ 14.1, 64-bit (Visual Studio 2019)

**Comment by wilx** [comment]
Well, in multi-threaded world, it is impossible to guarantee this. But within single thread, you should get the events logged in order they were generated.

Unless you are using asynchronous logging, which outsources the logging into Appenders into a thread pool, and there you cannot guarantee that events which were picked up from queue earlier than other will be logged earlier than other.

Each Appender has access mutex and that is locked before things get physically logged but that still does not take care of possible reordering between threads.

**Comment by sdynan-r7** [comment]
Is this asynchronous logging a feature of log4cplus? Can I turn that off somehow?

The example I posted was single threaded -- you can see the thread id in column 2.

**Comment by wilx** [comment]
It is a feature. By default, it is off. It can be enabled by setting property `AsyncAppend` on any `Appender`.
