### ISSUE TITLE
loggingmacros.h error

### ISSUE THREAD

**Issue by FLYo0O** [log4cplus/log4cplus#489]
Describe your problem here.

Also, provide the following information:

 - version: 2.0.4
 log4cplus/loggingmacros.h:210:5: error: expected unqualified-id before ‘do’
     do {                                                                \
     ^
log4cplus/loggingmacros.h:380:5: note: in expansion of macro ‘LOG4CPLUS_MACRO_BODY’
     LOG4CPLUS_MACRO_BODY (logger, logEvent, WARN_LOG_LEVEL)

how to fix it????????????????

**Comment by wilx** [comment]
This is probably a problem of your code and how it uses the macro. What is the context where it is used?

**Comment by mom1705** [comment]
Did u get a solution to your problem, I am also getting similar issue. Looks like in latest g++ ( 8.5.0), this error is being thrown. same code works in prev. g++ copiler version ie 4.8.5
