### ISSUE TITLE
compile missing file

### ISSUE THREAD

**Issue by JXT-Eden** [log4cplus/log4cplus#494]
in win10,compiled using VS2015,error:string_view no such file or directory! 
this file cannot be found in the project directory.
cloning of the latest version.

**Comment by wilx** [comment]
The master branch is C++17 source. I am pretty sure VS2015 is not C++17 compliant. You will have to upgrade your Visual Studio or use a different release / branch.

**Comment by JXT-Eden** [comment]
> The master branch is C++17 source. I am pretty sure VS2015 is not C++17 compliant. You will have to upgrade your Visual Studio or use a different release / branch.

clone 2.0.x branch ,vs2015 support C ++11 compliant, but error : catch.hpp no such file or directory!

**Comment by wilx** [comment]
The log4cplus repo has some submodules. You need to checkout the submodules
as well.

Dne út 12. 1. 2021 8:36 uživatel JXT-Eden <notifications@github.com> napsal:
