### ISSUE TITLE
RollingFileAppender block on write

### ISSUE THREAD

**Issue by Xiaobin0860** [log4cplus/log4cplus#504]
#0  0x000000375b2db6ed in write () from /lib64/libc.so.6
#1  0x00007fabafbca436 in (anonymous namespace)::xwrite(int, char const*, long) () at basic_file.cc:120
#2  0x00007fabafc0e278 in std::basic_filebuf<char, std::char_traits<char> >::_M_convert_to_external(char*, long) () at /data/src/sc/gcc-5.2.0/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/fstream.tcc:607
#3  0x00007fabafc0e621 in std::basic_filebuf<char, std::char_traits<char> >::overflow(int) () at /data/src/sc/gcc-5.2.0/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/fstream.tcc:534
#4  0x00007fabafc0c44f in std::basic_filebuf<char, std::char_traits<char> >::sync() () at /data/src/sc/gcc-5.2.0/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/fstream.tcc:987
#5  0x00007fabafc2e73e in std::basic_ostream<char, std::char_traits<char> >::flush() () at /data/src/sc/gcc-5.2.0/x86_64-unknown-linux-gnu/libstdc++-v3/include/streambuf:271
#6  0x00007fabafede00c in log4cplus::FileAppenderBase::append(log4cplus::spi::InternalLoggingEvent const&) () from /usr/local/lib/liblog4cplus-1.2.so.5
#7  0x00007fabafee0230 in log4cplus::RollingFileAppender::append(log4cplus::spi::InternalLoggingEvent const&) () from /usr/local/lib/liblog4cplus-1.2.so.5
#8  0x00007fabafecf047 in log4cplus::Appender::doAppend(log4cplus::spi::InternalLoggingEvent const&) () from /usr/local/lib/liblog4cplus-1.2.so.5
#9  0x00007fabafecde9e in log4cplus::helpers::AppenderAttachableImpl::appendLoopOnAppenders(log4cplus::spi::InternalLoggingEvent const&) const () from /usr/local/lib/liblog4cplus-1.2.so.5
#10 0x00007fabafeec0b4 in log4cplus::spi::LoggerImpl::callAppenders(log4cplus::spi::InternalLoggingEvent const&) () from /usr/local/lib/liblog4cplus-1.2.so.5
#11 0x0000000001729f93 in BattleScene::checkOpAndPlay_Nolock() ()

**Comment by wilx** [comment]
If it blocks in OS call, I am afraid I can't do anything about this.
