### ISSUE TITLE
-Wall

### ISSUE THREAD

**Issue by NeY3110W** [log4cplus/log4cplus#505]
If compile with flag -Wall, there are 2 warnings, -Wunused-variable, -Wunused-function.
Also, provide the following information:

 - version: 2.0.4
 - operating system, CPU, bitness: linux, mac
 - `configure` script, or CMake, etc., flags and settings: We build project with gyp, flags -Wall, -Werror
 - compiler and its version: clang, g++, c++11

**Comment by wilx** [comment]
There are probably a lot more than just 2 warnings, depending on compiler and version.
