### ISSUE TITLE
Include Makefile in distribution tarball

### ISSUE THREAD

**Issue by opello** [log4cplus/log4cplus#506]
When trying to build in environments with an older `automake` (one that can not satisfy `am__api_version='1.16'` from `configure`) there's no nice workaround.  It seems that if a `./configure; make; make install` flow should be able to build log4cplus, the distribution tarball should include a `Makefile` too?

Based on #436 it seems like that means it should be cached in the repository, depending on how that issue is resolved.

- version: 2.0.6

**Comment by wilx** [comment]
`Makefile` is not necessary or even desirable. You get `Makefile.in` which is filtered and `configure` produces `Makefile` from it.

**Comment by opello** [comment]
It seems desirable if you don't want to require end users to have autotools (and to that end, specific versions of autotools) to be available.  I'm not sure how popular of a perspective this is anymore.

**Comment by wilx** [comment]
Why do you think you need autotools? All you need to do is run `configure` script and it will produce `Makefile`. You do not need autotools if you have downloaded the distribution tar.gz or other provided package.

**Comment by opello** [comment]
You are correct, I just tested it in a clean environment and it builds just fine without automake being available.  Sorry for the noise!
