### ISSUE TITLE
Visual Studio Code Cmake global-init.cxx.obj: too many sections

### ISSUE THREAD

**Issue by 1060497222** [log4cplus/log4cplus#507]
CMakeFiles\log4cplusU.dir\global-init.cxx.obj: too many sections (34862)
 Fatal error: can't write 103 bytes to section .text of CMakeFiles\log4cplusU.dir\global-init.cxx.obj: 'File too big'
WINDOWS

**Comment by wilx** [comment]
I have not seen that. The Appveyor build manages to build this just fine.
