### ISSUE TITLE
How to compile log4cplus with gcc version 4.4.5 20110214?

### ISSUE THREAD

**Issue by 1405040117** [log4cplus/log4cplus#510]
The latest version of log4cplus must support C++11 gcc to compile, is there an older version of log4cplus that can be compiled with version 4.4.5 of gcc? thanks

**Comment by wilx** [comment]
Anything 1.x should be compilable with C++03 compiler. Try the 1.2.2 version from https://sourceforge.net/projects/log4cplus/files/log4cplus-stable/1.2.2/.

**Comment by 1405040117** [comment]
> Anything 1.x should be compilable with C++03 compiler. Try the 1.2.2 version from https://sourceforge.net/projects/log4cplus/files/log4cplus-stable/1.2.2/.

Okay, I'll try, thanks.

**Comment by 1405040117** [comment]
> Anything 1.x should be compilable with C++03 compiler. Try the 1.2.2 version from https://sourceforge.net/projects/log4cplus/files/log4cplus-stable/1.2.2/.

This version does work and the problem has been solved, thank you very much.
