### ISSUE TITLE
Add an alias to the target in 'src/CMakeLists.txt?

### ISSUE THREAD

**Issue by Joker2387089590** [log4cplus/log4cplus#511]
My question is easy: when I use CMake

**Comment by Joker2387089590** [comment]
Sorry, I hit ENTER accidentally... I use CMake to compile this project, and I found that the library name is defined by an variable. So I added an alias, just `add_library(log4cplus::log4cplus ALIAS ${log4cplus})`. But I think the variable may be changed in the future version. So I think an explicit name is helpful for me.

**Comment by wilx** [comment]
This seems useful. Can you prepare a pull request which adds these aliases to all the libraries?
