### ISSUE TITLE
What's the latest version that still supports visual studio 2005?

### ISSUE THREAD

**Issue by LinArcX** [log4cplus/log4cplus#521]
We have a legacy windows application that uses visual studio 2005.
And we want to use log4cplus for it. What's the latest version that supports this version of visual studio?

**Comment by wilx** [comment]
Try the 1.2.x version line.

**Comment by LinArcX** [comment]
There is no solution for visual studio 2005 in that version.

**Comment by wilx** [comment]
You could try building with CMake using the NMake makefiles target. But I do not even know if it will compile with such old compiler.

**Comment by LinArcX** [comment]
Yes, thanks. it compiled successfully.

This is the receipt just for other users:
1. download cmake.3.11.4 (This is the latest version that supports visual studio 2005 generator)
2. clone version 1.2.1 of log4cplus
3. go to source of log4cplust and create `build` directory
4. switch to build and run: `cmake -G "Visual Studio 8 2005" ..`
5. It will generate necessary files to build the library with visual studio 2005.
6. open log4cplus.sln and hit build button.
