### ISSUE TITLE
Is it possible to create parent folders of logs if they don't exist?

### ISSUE THREAD

**Issue by LinArcX** [log4cplus/log4cplus#523]
Look at this _**log4cplus.properties**_ file:

```
# Root logger option
log4cplus.rootLogger=DEBUG, stdout, test

# Console
log4cplus.appender.stdout=log4cplus::ConsoleAppender
log4cplus.appender.stdout.layout=log4cplus::PatternLayout
log4cplus.appender.stdout.layout.ConversionPattern=%d{%m/%d/%y %H:%M:%S} [%t] %-5p %c{2} %%%x%% - %m [%l]%n

# ATM
log4cplus.appender.test=log4cplus::RollingFileAppender
log4cplus.appender.test.File=C:\\Program Files\\test\\logs\\test_1.log
log4cplus.appender.test.MaxFileSize=500KB
log4cplus.appender.test.MaxBackupIndex=1
log4cplus.appender.test.layout=log4cplus::PatternLayout
log4cplus.appender.test.layout.ConversionPattern=%d{%m/%d/%y %H:%M:%S} %-5p %c{1} - %m%n
```

I don't have `test` folder inside `C:\\Program Files` and so if i run my application with this properties file, i get this error message:

`log4cplus:ERROR Unable to open file: C:\\Program Files\\test\\logs\\test_1.log`

[Seems ](https://stackoverflow.com/questions/53974434/prevent-log4j2-from-creating-parent-folder-of-a-log-file-if-it-doesnt-exist/53974549)in log4j, it create folders automatically. Can we have this feature in log4cplus too?

**Comment by wilx** [comment]
Try with `log4cplus.appender.test.CreateDirs=true`.
