### ISSUE TITLE
--enable-tests configure flag unrecognized on 2.0.7 releases

### ISSUE THREAD

**Issue by Crghilardi** [log4cplus/log4cplus#529]
The `enable-tests` configure flag seems to be missing in all of the `2.0.7` GitHub releases `configure` file.
I have confirmed this on both https://github.com/log4cplus/log4cplus/releases/download/REL_2_0_7/log4cplus-2.0.7.tar.gz and the default GitHub `Source Code` packaging https://github.com/log4cplus/log4cplus/archive/refs/tags/REL_2_0_7.tar.gz

To replicate
```
wget https://github.com/log4cplus/log4cplus/releases/download/REL_2_0_7/log4cplus-2.0.7.tar.gz

./configure \
--prefix=${prefix} \
--build=${MACHTYPE} \
--host=${target} \
--enable-unit-tests=no \
--enable-tests=no
```
which returns as 
```
...
config.status: creating tests/performance_test/log4cplus.properties
config.status: creating tests/propertyconfig_test/log4cplus.properties
config.status: creating tests/propertyconfig_test/log4cplus.tail.properties
config.status: creating include/log4cplus/config.h
config.status: creating include/log4cplus/config/defines.hxx
config.status: executing tests/atconfig commands
config.status: executing depfiles commands
config.status: executing libtool commands
configure: WARNING: unrecognized options: --enable-tests
```

The flag is present on the [master branch](https://github.com/log4cplus/log4cplus/blob/3565945256d68be6a6867228ddcd5480535e6f01/configure#L5505-L5512) but I could not track down exactly when or where it got added.It seems to be added in #500?

I can't tell which one is right or wrong, but the README or `./configure --help` don't seem to agree for the latest release

**Comment by wilx** [comment]
I cannot reproduce this. Also, you log message says `--enable-tests`. Maybe that is the issue?

**Comment by Crghilardi** [comment]
My mistake, I was copying/pasting from the wrong terminal. Here is the corrected version (also corrected in comment above) that reproduces the message.

```
./configure \
--prefix=${prefix} \
--build=${MACHTYPE} \
--host=${target} \
--enable-unit-tests=no \
--enable-tests=no

```
The [README](https://github.com/log4cplus/log4cplus#--enable-tests) lists `--enable-tests` as a valid flag, was this a recent addition? The README shows as last edited 2 years ago so I was confused.

**Comment by wilx** [comment]
I see what you mean now.

**Comment by wilx** [comment]
The README.md content is different between master branch and 2.0.x branch. What you see on GitHub page is the master branch README.md which does contain `--enable-tests` while the 2.0.x branch does not contain `--enable-tests`.

**Comment by Crghilardi** [comment]
OK, I see the difference now. If I need that functionality. I will need to build from `master.` 

Is `master` currently part of the `2.0.x` cycle or is it tracking a future `3.0.x`?

**Comment by wilx** [comment]
2.0.x is not master. If you need to build without the tests then we would have to patch the 2.0.x branch with similar change.
