### ISSUE TITLE
FeatureRequest -  Sentry integration

### ISSUE THREAD

**Issue by darkknight0007** [log4cplus/log4cplus#532]
There's an integration of Sentry with log4j and log4net
https://docs.sentry.io/platforms/java/guides/log4j2/
https://docs.sentry.io/platforms/dotnet/guides/log4net/

There's also sentry-native support c++
https://github.com/getsentry/sentry-native

So it'll be nice if there is an integration of Sentry with log4cplus also.

**Comment by wilx** [comment]
I don't see how this could be integrated into log4cplus. You can build your own custom Appender, if that is how you would like this to be integrated. I don't think this is something that should necessarily be part of log4cplus itself.
