### ISSUE TITLE
File size of release version (log4cplusS.lib) is too large(82 MB) , and even bigger than the debug version(log4cplusSD.lib 29MB)

### ISSUE THREAD

**Issue by happypass** [log4cplus/log4cplus#536]
Environment：
1. Version: log4cplus-1.2.2
2.  operating system: win10, 64bit.
3. IDE : Visual studio 2012

I want to use the static library of log4cplus,  and found a very strange thing that  
the file size of release version(log4cplusS.lib 82MB ) is much larger than that of the debug version(log4cplusSD.lib 29MB)

For example : 
  log4cplusS.lib    = 82.356 KB ( Path: log4cplus-1.2.2\msvc10\x64\bin.Release)
  log4cplusSD.lib =  29.742 KB (Path : log4cplus-1.2.2\msvc10\x64\bin.Release)

And  how can I reduce the file size of the release version lib  (log4cplusS.lib) ?

**Comment by wilx** [comment]
I suspect it is the link time optimization data. The size of the lib file is mostly irrelevant.
