### ISSUE TITLE
log4cplus: using AsyncAppend=true in appenders, how to set queue depth?

### ISSUE THREAD

**Issue by udovenkoav1981** [log4cplus/log4cplus#537]
I use modern log4cplus, 2.0.5. And i need to use async appenders, as i understand all appenders have param AsyncAppend, but there are no any info about queue depth for log events?  I see param  QueueLimit for AsyncAppender, but as i understand it is old logic for async logging - used before param AsyncAppend was released.

How i can set queue depth with AsyncAppend=true?

Is this queue depth per every appender? or per user thread ?

**Comment by udovenkoav1981** [comment]
Thanks' for reply.  One more question about performance in Async mode. I see that Ansync mode works about 6 times slower - is it normal?
my config:
```ini
log4cplus.rootLogger=DEBUG, ROLLING
 
log4cplus.appender.ROLLING=log4cplus::RollingFileAppender
log4cplus.appender.ROLLING.AsyncAppend=true
log4cplus.appender.ROLLING.MaxFileSize=220Kb
log4cplus.appender.ROLLING.MaxBackupIndex=5
log4cplus.appender.ROLLING.layout=log4cplus::PatternLayout  
log4cplus.appender.ROLLING.layout.ConversionPattern=%c %-5p %d{%y-%m-%d %H:%M:%S.%q} [%T][%l %M] %m%n
log4cplus.appender.ROLLING.File=Rolling.log
```

my code:

```c++
#include <iostream>
#include <log4cplus/logger.h>
#include <log4cplus/configurator.h>
#include <log4cplus/loggingmacros.h>
#include <log4cplus/initializer.h>

int main(int argc, char* argv[]) {
  log4cplus::Initializer initializer;
  log4cplus::PropertyConfigurator::doConfigure("log4cplus_configure2.ini");
  
  log4cplus::Logger main1 = log4cplus::Logger::getInstance("main1");

  for(int i=0;i<100000;++i){
    LOG4CPLUS_WARN(main1, "Hello, World! "<< i);
  }

  return 0;
}
```

AsyncAppend=true time is 3.7sec
AsyncAppend=false time is 0.5sec
why so slow?

**Comment by wilx** [comment]
This is basically [Amdahl's law](https://en.wikipedia.org/wiki/Amdahl%27s_law). There is no usable parallel component of your small algorithm there. So you see no speedup compared to sequential version. And you have added a bunch of overhead on top of it by introducing all the thread context switching and locking. So you see slowdown. The queue has to be drained so you actually pay the overhead price for all of the 100000 events.
