### ISSUE TITLE
RollingFileAppender is not working with 2.0.6

### ISSUE THREAD

**Issue by SlavaC1** [log4cplus/log4cplus#541]
Hi

I'm using 2.0.6 in Windows 64 bit compiled as static library.

My configuration is:

```
log4cplus.rootLogger=DEBUG, ROLLING, STDOUT

log4cplus.appender.STDOUT=log4cplus::ConsoleAppender
log4cplus.appender.STDOUT.layout=log4cplus::PatternLayout
#See http://logging.apache.org/log4j/docs/api/org/apache/log4j/PatternLayout.html
log4cplus.appender.STDOUT.layout.ConversionPattern=%D{%H:%M:%S} [%t] - %m%n

log4cplus.appender.ROLLING=log4cplus::RollingFileAppender
#MaxFileSize configures the maximum log file size. 
log4cplus.appender.ROLLING.MaxFileSize=400Kb
#MaxBackupIndex configures the number of backup log files.
log4cplus.appender.ROLLING.MaxBackupIndex=5
log4cplus.appender.ROLLING.layout=log4cplus::PatternLayout
log4cplus.appender.ROLLING.layout.ConversionPattern=%D{%d/%m/%Y %H:%M:%S:%q} [%t] %-5p - %m [%-l]%n
#File configures the log file path. if no path is specified the log will be created in MyDocuments folder. 
log4cplus.appender.ROLLING.File=log.txt
#log4cplus.appender.ROLLING.UseLockFile=true
log4cplus.appender.ROLLING.ImmediateFlush=true
```

I'm running a loop to write many log messages to see new log file is created, but I observe the following issues:

1. My log file is not flushed each entry, but the file size stays 0 until I finish the program
2. Additional log files are not created as expected when reaching 400 Kb with new name, but the single file is constantly overwritten.

Please advice.

Thanks a lot,
Slava

**Comment by SlavaC1** [comment]
I investigated this issue a bit. I'm getting the following error:

`log4cplus:ERROR Failed to rename file from .\logs\log.txt to .\logs\log.txt.1; error 13`

**Comment by wilx** [comment]
> I investigated this issue a bit. I'm getting the following error:
> 
> `log4cplus:ERROR Failed to rename file from .\logs\log.txt to .\logs\log.txt.1; error 13`
> 
> I see that 13 is EACCES. Could be that file is not closed properly and that's the reason that it can't be renamed?

Yes. That can be the reason on Windows.
