### ISSUE TITLE
Not throws exception in PropertyConfigurator::doConfigure() when config file is not found

### ISSUE THREAD

**Issue by Crisliu7** [log4cplus/log4cplus#553]
### Problem 

When I run following code with a unexisting config_file. I cannot catch any exception cuz doConfigure() didn't throws it. 

### Root Cause
And I find it's caused by the `throw_flag` is not set to true [here](https://github.com/log4cplus/log4cplus/blob/2.0.x/src/property.cxx#L221-L222) in Properties constructor. 

### To fix
Can we fix this problem? I think if the [error here](https://github.com/log4cplus/log4cplus/blob/2.0.x/src/loglog.cxx#L184) is thrown correctly that will be very helpful.

```
try
{
    log4cplus::PropertyConfigurator::doConfigure(config_file);
}
catch (...)
{
    std::cerr << "caught an error" ; std::endl;
}
```

 - version: *2.0.5*
 - operating system: *Ubuntu 18.04*
 - flags and settings used by your application: N/A
 - compiler and its version: *g++ 7.5.0*

**Comment by wilx** [comment]
The code in 2.1.x branch now throws `log4cplus::exception` which is derived from `std::runtime_exception`.
