### ISSUE TITLE
Initialization fails in case the config file is encoded as UTF-8 BOM

### ISSUE THREAD

**Issue by rabindra-harlalka** [log4cplus/log4cplus#556]
The config (ini/properties) file, which is passed to `log4cplus::PropertyConfigurator::doConfigure()`, isn't parsed correctly by log4cplus if it is encoded as UTF-8 BOM instead of UTF-8. If the first line of file, which starts with the BOM bytes, happens to be an important one, e.g. `log4cplus.rootLogger=ALL, MyFileAppender`, then the logging system is not initialized properly. Users see the following message on the console as a result:
```
log4cplus:ERROR No appenders could be found for logger (...).
log4cplus:ERROR Please initialize the log4cplus system properly.
```
As a user of the library, it is not clear that this wouldn't work. Many editors (on Windows especially) automatically create files with the BOM marker without users always realizing it. I couldn't find any documentation for log4cplus warning the users that file must be UTF-8/ASCII only.

The error message don't give any clue to the user where the problem lies. I could only realize this after debugging log4cplus code.

The current situation can be improved either by adding support for parsing UTF-8 BOM files, the `doConfigure()` method issuing a hint in the error message about this problem, or at least documenting prominently the behavior so that users don't meet with this surprise.

Also, provide the following information:

 - version: 2.0.8
 - operating system, CPU, bitness: Windows 10, x64
 - `configure` script, or CMake, etc., flags and settings: default settings, compiled the Visual Studio (MSVC) solution file, unicode flag off (MBCS)
 - flags and settings used by your application: Unicode off (MBCS)
 - compiler and its version: Visual Studio 2022 (v143), Windows SDK 10.0

**Comment by wilx** [comment]
You should be able to configure with the imbued stream that does consume the BOM. Something like this should do:

```c++
    std::ifstream file;
    file.imbue (
    std::locale (file.getloc (),
        new std::codecvt_utf8<tchar, 0x10FFFF,
            static_cast<std::codecvt_mode>(std::consume_header | std::little_endian)>));
    PropertyConfigurator pc(file, h, flags);
    pc.configure();
```

**Comment by rabindra-harlalka** [comment]
> You should be able to configure with the imbued stream that does consume the BOM. Something like this should do:

Thanks @wilx . I will give that a try. What do you suggest should be done to make it easy for users to discover that the encoding is the problem? Once this fact is discovered, a simple solution is also to reencode the file. While this issue itself may serve as documentation, should this be documented more prominently, perhaps an example or as a warning in the readme or wiki?
