### ISSUE TITLE
ConsoleAppender does not work in container

### ISSUE THREAD

**Issue by devintrowbridge** [log4cplus/log4cplus#557]
I'm trying to containerize my application but I'm having trouble getting log4cplus working. Bottom line up front, logging works when running on the host, but not in the container when I'm logging from long running loops. Its seems like a buffer somewhere is not getting flushed. A minimal example follows.

Additionally, removing the long lived loop removes the issue, presumably log4cplus flushes one last time before tearing down. Lengthening the `sleep` duration did not seem to help.

**main.cpp**
```c++
#include <iostream>
#include <unistd.h>

#include <log4cplus/logger.h>
#include <log4cplus/loggingmacros.h>
#include <log4cplus/configurator.h>
#include <log4cplus/initializer.h>

int main(int argc, char **argv)
{
    std::cout << "Sanity Check" << std::endl;

    auto log4cplus = ::log4cplus::Initializer();
    std::string logconfig("log4cplus_configure.ini");
    ::log4cplus::PropertyConfigurator::doConfigure(logconfig);
    auto logger = ::log4cplus::Logger::getInstance(LOG4CPLUS_TEXT("main"));

    while (true) { 
        LOG4CPLUS_ERROR(logger, "Sleeping...");
        // std::cout << "cout sleep..." << std::endl; // uncomment to get log messages working
        sleep(1);
    }

    return 0;
}
```

**log4cplus_configure.ini**
```
log4cplus.rootLogger=INFO, MyConsoleAppender
log4cplus.appender.MyConsoleAppender=log4cplus::ConsoleAppender
log4cplus.appender.MyConsoleAppender.layout=log4cplus::PatternLayout
log4cplus.appender.MyConsoleAppender.layout.ConversionPattern=[%-5p][%d] %m%n
```

**Dockerfile**
```Dockerfile
FROM rockylinux:latest

RUN dnf install -y boost-system

COPY ./build/sandbox /
COPY ./log4cplus_configure.ini /

CMD  ["/sandbox"]
```

**CMakeLists.txt**
```CMake
cmake_minimum_required(VERSION 3.10)
set (CMAKE_CXX_STANDARD 17)

# Project executable and library
add_executable(sandbox main.cpp)

target_link_libraries(sandbox
    PUBLIC liblog4cplus.a
    PUBLIC pthread
    PUBLIC boost_system
)
```

Also, provide the following information:

 - version: installed from 52dd360e
 - operating system, CPU, bitness: containerized via podman. Host is x64 rocky linux, container also rockylinux
 - `configure` script, or CMake, etc., flags and settings: `./scripts/fix-timestamps.sh; ./configure --disable-shared --enable-static`
 - flags and settings used by your application: see the files above
 - compiler and its version: `clang v13.0.1`

**Comment by wilx** [comment]
Try to add `log4cplus.appender.MyConsoleAppender.ImmediateFlush=true` to your configuration.

**Comment by wilx** [comment]
As for your build, `configure script, or CMake, etc., flags and settings: ./scripts/fix-timestamps.sh; ./configure --disable-shared --enable-static` probably works but the intended way to distribute the sources is the `log4cplus-2.0.8.*` archives, not the "Source code" produced by GitHub.

**Comment by devintrowbridge** [comment]
> As for your build, `configure script, or CMake, etc., flags and settings: ./scripts/fix-timestamps.sh; ./configure --disable-shared --enable-static` probably works but the intended way to distribute the sources is the `log4cplus-2.0.8.*` archives, not the "Source code" produced by GitHub.

Good to know. I've got it as a submodule right now. Moving to an official version would definitely be better.

> Try to add log4cplus.appender.MyConsoleAppender.ImmediateFlush=true to your configuration.

That fixed it! Thanks for the speedy help. What's the best place to look for configuration options? That's the biggest issue I've had working with log4x so far.

**Comment by wilx** [comment]
There is a Doxygen generated documentation. It is sort hard to find right now. See https://log4cplus.sourceforge.io/docs/api/2.0.x/classlog4cplus_1_1ConsoleAppender.html. Each Appender has a Doxygen comment above class declaration which describes its properties.
