### ISSUE TITLE
Use  Arm64 log4cplus.dll  Bug

### ISSUE THREAD

**Issue by MengTangYue** [log4cplus/log4cplus#560]
- version: log4cplus-2.0.8
 - vs 2019 
 - Arm64 log4cplus.dll

Logical Sequence:
 log4cplus.dll-> Simlogger.dll->MFCTest.exe
 
Compile all ARM64 , Mfctest. exe will compile, but will not run.

All X64 compiler, no problem,

Log4cplus.dll does not support ARM??

**Comment by MengTangYue** [comment]
Hello
This Simlogger.dll code:
#ifndef _SIM_LOGGER_H_
#define _SIM_LOGGER_H_

// The following ifdef block is the standard way of creating macros which make exporting 
// from a DLL simpler. All files within this DLL are compiled with the SIMLOGGER_EXPORTS
// symbol defined on the command line. this symbol should not be defined on any project
// that uses this DLL. This way any other project whose source files include this file see 
// SIMLOGGER_API functions as being imported from a DLL, whereas this DLL sees symbols
// defined with this macro as being exported.
#ifdef SIMLOGGER_EXPORTS
#define SIMLOGGER_API __declspec(dllexport)
#else
#define SIMLOGGER_API __declspec(dllimport)
#endif


#include <stdarg.h>
#include <stdlib.h>
#include <memory.h>
#include <string>


#include <log4cplus/logger.h>
#include <log4cplus/logger.h>
#include <log4cplus/fileappender.h>
#include <log4cplus/consoleappender.h>
#include <log4cplus/layout.h>
#include <log4cplus/configurator.h>
#include "windows.h"
#include "tchar.h"

#define SIM_MAX_FILE_SIZE (10*1024*1024)    //10MBytes
#define SIM_MAX_BKUP_INDEX 2                //num of backup file
#define SIM_MAX_LOG_MSG_SIZE  (1024)

//configuration file
#define LOG4_CONFIG_FILE_NAME "logProperties.cfg"


using namespace std;
using namespace log4cplus;
using namespace log4cplus::helpers;

extern SIMLOGGER_API int nSimLogger;

SIMLOGGER_API int fnSimLogger(void);

namespace  simlogger{
// This class is exported from the SimLogger.dll
class SIMLOGGER_API CSimLogger
{
public:
	int SetLogFile(const TCHAR* pszFile);
	~CSimLogger();

	/*FATAL_LOG_LEVEL, ERROR_LOG_LEVEL, WARN_LOG_LEVEL, INFO_LOG_LEVEL,DEBUG_LOG_LEVEL */
	void WriteLog(LogLevel level, const TCHAR* fmt, ...);

	static CSimLogger* getInstance();
	void DestroySimLogger();
protected:
	void InitSimLogger(BOOL bFile);



private:
	CSimLogger();

public:
	static Logger m_logger;
private:
	TCHAR* m_pFilePath;
	TCHAR* m_pBuf;
	static CSimLogger* m_pSimLogger;
};


#define LOG_DEBUG(pSimLog, fmt, ...) (pSimLog)->WriteLog(DEBUG_LOG_LEVEL, fmt,__VA_ARGS__); 
#define LOG_INFO(pSimLog,  fmt, ...) (pSimLog)->WriteLog(INFO_LOG_LEVEL, fmt,__VA_ARGS__); 
#define LOG_WARN(pSimLog,  fmt, ...) (pSimLog)->WriteLog(WARN_LOG_LEVEL, fmt,__VA_ARGS__); 
#define LOG_ERROR(pSimLog, fmt, ...) (pSimLog)->WriteLog(ERROR_LOG_LEVEL, fmt,__VA_ARGS__); 
#define LOG_FATAL(pSimLog, fmt, ...) (pSimLog)->WriteLog(FATAL_LOG_LEVEL, fmt,__VA_ARGS__); 

}

#endif //_SIM_LOGGER_H_

**Comment by MengTangYue** [comment]
![image](https://user-images.githubusercontent.com/61826177/191406083-b7ba2580-7475-4522-87ef-f0b19ef0cae1.png)

**Comment by wilx** [comment]
I am afraid there is not enough information to go on. Compile log4cplus and your project with for debugging with debugging symbols and provide a call stack at least.

You could also try and run the log4cplus tests. If they run, the problem is likely in your application code.
