### ISSUE TITLE
liblog4cplusplus.so: undefined reference to `log4cplus::Logger::log

### ISSUE THREAD

**Issue by shixingya** [log4cplus/log4cplus#564]
How to solve the following problem.
Unbuntu 18.04 gcc 11 compile error under Unbuntu 18.04. I use log4cplus-2.0.7.zip
my code: https://github.com/huihut/log4cplusplus.git

../../log4cplusplus/src/liblog4cplusplus.so: undefined reference to `log4cplus::Logger::log(int, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, char const*, int, char const*) const'
../../log4cplusplus/src/liblog4cplusplus.so: undefined reference to `log4cplus::helpers::snprintf_buf::print_va_list(wchar_t const*&, wchar_t const*, __va_list_tag*)'
collect2: error: ld returned 1 exit status

**Comment by wilx** [comment]
On Linux, you have to choose what variant of the library you will compile. See https://github.com/log4cplus/log4cplus/blob/2.0.x/README.md#--with-wchar_t-support
