### ISSUE TITLE
ASSERT_EQUALS failed on same double value with valgrind

### ISSUE THREAD

**Issue by zzDiego** [log4cplus/log4cplus#565]
Describe your problem here:
I generated my test run and it works perfectly when I ran it. 
But when I run with valgrind I have a test that always failed with this output :
```myTestSuite.h:263: Error: Expected (std::stod(reader[1][3]) == 25.3), found (25.3000 != 25.3000)```
The line in my code is 
```TS_ASSERT_EQUALS(std::stod(reader[1][3]), 25.3);```

I run the normal execution (the one which work) with just "./error_printer".
For the vlagrind execution I run "valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind-out.txt ./error_printer"

I could precise that I work in a docker container base on alpine. An extract of my dockerfile below could possibiliy help :
```
FROM alpine:3.16.2
RUN apk add g++ make log4cplus-dev linux-headers git python3 valgrind
```
which install liblog4cplus-2.0.so.3.4.6

Because the project doesn't move since a while, I could check myself and fork it if needed, but I just would have some advice to know where to start digging

Also, provide the following information:
 - version: version.h contains 2.0.7 (#define LOG4CPLUS_VERSION LOG4CPLUS_MAKE_VERSION(2, 0, 7))
 - operating system, CPU, bitness: alpine arm64
 - `configure` script, or CMake, etc., flags and settings: default provided by the package log4cplus-dev
 - flags and settings used by your application: nothing specific, just g++ -c -std=c++20 -Wall
 - compiler and its version: g++ (Alpine 11.2.1_git20220219) 11.2.1 20220219

**Comment by wilx** [comment]
What does `std::cout << (std::stod(reader[1][3]) - 25.3) << std::endl;`  print? This looks to me like typical floating point issue where two values computed differently are nearly the same bot not exactly the same.

**Comment by zzDiego** [comment]
You're right !!!
in "normal execution it display 0, but with valgrind it display 2.9e-12
I will use TS_ASSERT_DELTA to avoir this problem.

Thank you so mush for always supporting this project
