### ISSUE TITLE
SyslogAppender: how to send hostname instead of FQDN in log messages?

### ISSUE THREAD

**Issue by mbert** [log4cplus/log4cplus#570]
I am having an issue with a mixed environment where services based on different technologies log to a local rsyslogd via UDP which then passes everything on to a central log server which appends to per-host log files. The log files are named after their originating hosts (%HOSTNAME%).

Now in their log lines all other services (those not using log4cplus) send the short host name, only the ones using log4cplus sends the FQDN, hence leading to separate log files for the same host on the central log server.

Having searched for any such setting in vain it looks like this is turning out to be a feature request: could the host name format in the log lines be made configurable?

On a side note - I would normally prefer the FQDN, but this setting is beyond my control on some of the services I am running, and generally I'd like to see such a setting in all involved logging frameworks.

**Comment by wilx** [comment]
What version of log4cplus are you targeting?

**Comment by mbert** [comment]
> What version of log4cplus are you targeting?

Currently we use version 2.0.5.

**Comment by wilx** [comment]
@mbert Please test the 2.0.x branch.

**Comment by mbert** [comment]
Late feedback: I've made a test with services linked against the current 2.0.x branch, and things work as expected; thank you!

**Comment by mbert** [comment]
Any estimate when a 2.0.9 release can be expected?
