### ISSUE TITLE
How to setup a singleton logger instance 

### ISSUE THREAD

**Issue by hassanctech** [log4cplus/log4cplus#578]
We are using 2.0.1 of the library

In our application we have a Java application a JNI layer and a C++ component.  Starting from a java thread we go into native code and construct a native object, as part of this native objects construction we call:

```
log4cplus::initialize();
log4cplus::PropertyConfigurator::doConfigure("./log_configuration_file");
```

At any given time we may have multiple java threads going into native code and constructing these objects, we have a global singleton defined as follows:

```
// defines a class which contains a logger instance with the given tag
#define LOGGER_TAG(tag) \
  struct MyLogger { \
    static log4cplus::Logger& getInstance() { \
      static log4cplus::Logger s_logger = log4cplus::Logger::getInstance(tag); \
      return s_logger; \
    } \
  };

```

And in our main include header we have this set:

```
LOGGER_TAG("my_tag");
```

Then each time we log we do the following:

```
LOG4CPLUS_INFO(MyLogger::getInstance(), msg);
```

What we found is it appears that when we do initialize/doConfigure it actually creates a new logger each time writing to the same file we find that log lines are getting overwritten.

What is the correct way to do this so we have a singleton instance of the logger that we can share across instances of this object.  The log configuration file we set in the call to doConfigure() is always the same so I can see initialize/doConfigure do not need to be called each time the objects are constructed, I'm not sure where to put them though so they are shared across *all* of them.
  

Also, provide the following information:

 - version: *2.0.1*
 - operating system, CPU, bitness: *Ubuntu 22*
 - `configure` script, or CMake, etc., flags and settings: *none*
 - flags and settings used by your application: *none*
 - compiler and its version: *gcc*

**Comment by wilx** [comment]
You just have to initialize it once instead of on each entry from Java to C++ code. You could use [`std::call_once`](https://en.cppreference.com/w/cpp/thread/call_once), assuming you can use C++11.

**Comment by hassanctech** [comment]
How about calling `doConfigure(filename)` can we invoke that in a similar manner?  Also is it necessary to call `initialize()` ?

**Comment by wilx** [comment]
What I mean is that you probably should use `std::call_once` to run the entire initialisation only once. E.g., something like this:
```cpp
std::once_flag flag; // global variable

void java_callback()
{
  std::call_once(flag, [&]{
    log4cplus::initialize();
    log4cplus::PropertyConfigurator::doConfigure("./log_configuration_file");
  });

  // Create Logger and do logging here.
}
```

**Comment by wilx** [comment]
On Linux, log4cplus will typically be already initialised but calling `log4cplus::initialize()`, even multiple times, does no harm.

**Comment by hassanctech** [comment]
Yes so I defined the `std::once_flag` as a global in our top level include header with extern and then defined it in the class file that gets constructed by the java threads.  It resulted in some odd behavior so now what I observe is logging just stops all together after what seems like the very first thread has exited.  This didn't happen previously when we didn't use call_once.

Another question, so does this result in a unique new logger every time:

`log4cplus::Logger::getInstance(tag);`

What if the tag is the same will I get the same logger, I imagine if the tags are different it will be a new logger.  Each one of these needs a doConfigure call, correct?

**Comment by wilx** [comment]
> Each one of these needs a doConfigure call, correct?
No. You call `doConfigure` only once for the entire process.

**Comment by disa6302** [comment]
@wilx , 

Another question related: we have set up a log config file which has this syntax:

```
log4cplus.rootLogger=INFO

log4cplus.logger.<tag1>=TRACE, Tag1FileAppender
log4cplus.logger.<tag2>=TRACE, Tag2FileAppender
log4cplus.logger.<tag3>=TRACE, Tag3FileAppender

#Tag1FileAppender
log4cplus.appender.Tag1FileAppender=log4cplus::RollingFileAppender
log4cplus.appender.Tag1FileAppender.File=log/tag1.log
log4cplus.appender.Tag1FileAppender.MaxFileSize=10MB
log4cplus.appender.Tag1FileAppender.MaxBackupIndex=10
log4cplus.appender.Tag1FileAppender.CreateDirs=true
log4cplus.appender.Tag1FileAppender.layout=log4cplus::PatternLayout
log4cplus.appender.Tag1FileAppender.layout.ConversionPattern=[%-5p] [%d{%d-%m-%Y %H:%M:%S:%Q %Z}] [%-l][%t] %m%n

#Tag2FileAppender
log4cplus.appender.Tag2FileAppender=log4cplus::RollingFileAppender
log4cplus.appender.Tag2FileAppender.File=log/tag2.log
log4cplus.appender.Tag2FileAppender.MaxFileSize=10MB
log4cplus.appender.Tag2FileAppender.MaxBackupIndex=10
log4cplus.appender.Tag2FileAppender.CreateDirs=true
log4cplus.appender.Tag2FileAppender.layout=log4cplus::PatternLayout
log4cplus.appender.Tag2FileAppender.layout.ConversionPattern=[%-5p] [%d{%d-%m-%Y %H:%M:%S:%Q %Z}] [%-l][%t] %m%n

#Tag3FileAppender
log4cplus.appender.Tag3FileAppender=log4cplus::RollingFileAppender
log4cplus.appender.Tag3FileAppender.File=log/tag3.log
log4cplus.appender.Tag3FileAppender.MaxFileSize=10MB
log4cplus.appender.Tag3FileAppender.MaxBackupIndex=10
log4cplus.appender.Tag3FileAppender.CreateDirs=true
log4cplus.appender.Tag3FileAppender.layout=log4cplus::PatternLayout
log4cplus.appender.Tag3FileAppender.layout.ConversionPattern=[%-5p] [%d{%d-%m-%Y %H:%M:%S:%Q %Z}] [%-l][%t] %m%n
```

We invoke doConfigure only once using a singleton class from the java thread. I see logs being directed appropriately for Tag2 and Tag3, but for Tag1, the logs seem to be directed to Tag2 and Tag3 files instead of the Tag1 file. Why could this be happening? 

The tags are all part of different SDKs which are being included as dependencies in a project where the log4cplus is being configured and the log config file exists.

**Comment by wilx** [comment]
This is not possible. You must have a mistake somewhere. Your test must not be using the above configuration but a wrong one.

**Comment by disa6302** [comment]
Hmm. Ok. What happens when the config file is this way?

```
log4cplus.rootLogger=INFO

log4cplus.logger.<a.b.c.d.x>=TRACE, Tag1FileAppender
log4cplus.logger.<a.b.c.d>=TRACE, Tag2FileAppender
log4cplus.logger.<a.b.c.d.y>=TRACE, Tag3FileAppender

#Tag1FileAppender
log4cplus.appender.Tag1FileAppender=log4cplus::RollingFileAppender
log4cplus.appender.Tag1FileAppender.File=log/tag1.log
log4cplus.appender.Tag1FileAppender.MaxFileSize=10MB
log4cplus.appender.Tag1FileAppender.MaxBackupIndex=10
log4cplus.appender.Tag1FileAppender.CreateDirs=true
log4cplus.appender.Tag1FileAppender.layout=log4cplus::PatternLayout
log4cplus.appender.Tag1FileAppender.layout.ConversionPattern=[%-5p] [%d{%d-%m-%Y %H:%M:%S:%Q %Z}] [%-l][%t] %m%n

#Tag2FileAppender
log4cplus.appender.Tag2FileAppender=log4cplus::RollingFileAppender
log4cplus.appender.Tag2FileAppender.File=log/tag2.log
log4cplus.appender.Tag2FileAppender.MaxFileSize=10MB
log4cplus.appender.Tag2FileAppender.MaxBackupIndex=10
log4cplus.appender.Tag2FileAppender.CreateDirs=true
log4cplus.appender.Tag2FileAppender.layout=log4cplus::PatternLayout
log4cplus.appender.Tag2FileAppender.layout.ConversionPattern=[%-5p] [%d{%d-%m-%Y %H:%M:%S:%Q %Z}] [%-l][%t] %m%n

#Tag3FileAppender
log4cplus.appender.Tag3FileAppender=log4cplus::RollingFileAppender
log4cplus.appender.Tag3FileAppender.File=log/tag3.log
log4cplus.appender.Tag3FileAppender.MaxFileSize=10MB
log4cplus.appender.Tag3FileAppender.MaxBackupIndex=10
log4cplus.appender.Tag3FileAppender.CreateDirs=true
log4cplus.appender.Tag3FileAppender.layout=log4cplus::PatternLayout
log4cplus.appender.Tag3FileAppender.layout.ConversionPattern=[%-5p] [%d{%d-%m-%Y %H:%M:%S:%Q %Z}] [%-l][%t] %m%n
```

In this case, we have a namespace a.b.c.d with sub tags x and y. Would this mean that all the logs from a.b.c.d.x and a.b.c.d.y would go into log file for a.b.c.d?

**Comment by wilx** [comment]
```
log4cplus.logger.<a.b.c.d.x>=TRACE, Tag1FileAppender
log4cplus.logger.<a.b.c.d>=TRACE, Tag2FileAppender
log4cplus.logger.<a.b.c.d.y>=TRACE, Tag3FileAppender
```

The loggers form a hierarchy where each level is separated by a dot (`.`). The angle brackets have no meaning here. So you have a hierarchy of
```
"<a"─"b"─"c"─"d"─"x>"
              └──"y>"
```

Let's drop the angle brackets.

When you log a message, it will traverse the hierarchy to the root and it will be logged by each appender attached to any of the loggers on the way. In your case, if you try logging into "a.b.c.d.x" then it will log both into Tag1FileAppender and Tag2FileAppender. 

You can defeat this by adding a line like this:
```
log4cplus.additivity.a.b.c.d.x=false
```

**Comment by hassanctech** [comment]
Thanks @wilx for that explanation!  We tried with
```
log4cplus.additivity.a.b.c.d.x=false
log4cplus.additivity.a.b.c.d.y=false
```

But still for some reason and I don't know how x or y is different but all the logs from x go to the a.b.c.d appender and there's nothing logged in the log file that's associated with the x appender (though it does get created it's empty). Previously the y logs were going to both the y file and the a.b.c.d file, setting additivity to false made that stop.  But for some reason the x ones do not.  Given this non symmetric behavior I am also inclined to think this is an issue on our end.  Will report back if we have more questions.
