### ISSUE TITLE
[Question] Appender for AWS CloudWatch Logs

### ISSUE THREAD

**Issue by hassanctech** [log4cplus/log4cplus#580]
Are there any plans to support to logging to AWS CloudWatch Logs:  https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html

My understanding is to make this happen one would need to implement the Appender interface (and of course this requires auth / network but I imagine those details could be hidden behind the implementation with a way to ingest the config.  Are there any plans for log4cplus to support this?

**Comment by wilx** [comment]
I have no plans for AWS CloudWatch Logs.

I took a look and I do not see how an application could even use this API. It seems to me it is intended to be used to monitor AWS environment itself rather than the applications that run in it.

**Comment by wilx** [comment]
All the examples I can see are using file logging where the AWS agent is reading the log files and funneling them into AWS CloudWatch Logs.
