### ISSUE TITLE
./configure fails using c++2a 

### ISSUE THREAD

**Issue by Devlooper8** [log4cplus/log4cplus#581]
When I try to build this library using configure i get following error: 
configure: error: *** A compiler with support for C++20 language features is required.
I also tried to change cpp flag to c++2a because c++20 flag is not supported by my compiler
 - version: 2.1.0
 - operating system, CPU, bitness: Windows 10, intel i5, 64bit
 - `configure` script, or CMake, etc., flags and settings: configure using CPPFLAGS CXXFLAGS neither works
 - compiler and its version:  g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Comment by wilx** [comment]
Are you sure you are using the correct source tarball? The only mention of `language features is required` in `configure` script is with C++11: https://github.com/log4cplus/log4cplus/blob/59b9dc1f4d8c180259867aa54d8ef528e9c9c345/configure#L6403

**Comment by Devlooper8** [comment]
i just cloned latest sources and tried to build them but this error occurred, when i tried to download version 2.0.8 and build it everything went as supposed.

**Comment by wilx** [comment]
The master branch is now using C++20. The 2.1.x branch and 2.0.x branch are using C++11.
