### ISSUE TITLE
Question: Effect of LOG4CPLUS_REQUIRE_EXPLICIT_INITIALIZATION on Windows?

### ISSUE THREAD

**Issue by kritzel** [log4cplus/log4cplus#585]
I hope this is the right place to ask my question. I have a shared library using log4cplus for logging and several applications using the DLL. Since I updated log4cplus to REL_2.0.7 , these applications hang when the main() function exits. This only happens on Windows platforms but works fine on Linux.

I found that this issue can be solved by calling 

`log4cplus::Initializer initializer; `

at the beginning of main(). However I do not like the solution because this creates a dependency between the app using the shared library and log4cplus.

The documentation in README.md reads a bit confusing to me. The description of "--enable-implicit-initialization" suggests that the setting is platform-independent. And the description under "Windows and Visual Studio" does not suggest that the behavior can be changed by setting the flag accordingly. 

**So after all the background presented, it simply boils down to the question: Does the switch take effect on Windows platforms?**

In case the answer is "yes", my follow-up question would be "why doesn't it work for me?"

I updated to REL_3.0.0, but this did not change anything.

I am using CMake directly to build log4cplus, I checked that the setting is correctly set in the CMakeCache.txt:

`//Require explicit initialization (see log4cplus::Initializer)
LOG4CPLUS_REQUIRE_EXPLICIT_INITIALIZATION:BOOL=OFF`

I am using the following CMake settings for building log4cplus.
LOG4CPLUS_REQUIRE_EXPLICIT_INITIALIZATION=OFF
BUILD_SHARED_LIBS=ON
LOG4CPLUS_ENABLE_DECORATED_LIBRARY_NAME=OFF 
LOG4CPLUS_BUILD_LOGGINGSERVER=OFF 
LOG4CPLUS_BUILD_TESTING=OFF 
UNICODE=OFF 
WITH_UNIT_TESTS=OFF

I would like to use this occasion to say thanks to the maintainers of this great library, which I have been using for (literally) decades.

**Comment by kritzel** [comment]
Thanks a log @wilx for your swift response. It makes the matter totally clear to me. 
We are using the configuration file to configure the framework, so I cannot rule out that someone would use the AsyncAppender. Hence, I cannot disable the thread pool (correct me if I am wrong).

I just wanted to make sure not to miss any built-in option to solve the issue. I will now implement a viable workaround in my shared library.

Shall I close this issue now?

**Comment by wilx** [comment]
If anyone sets the `AsyncAppend=true` option and the thread pool has been disabled at compile time, the code will silently use the synchronous logging instead: https://github.com/log4cplus/log4cplus/blob/2.1.x/src/appender.cxx#L296-L320
