### ISSUE TITLE
What kind of compilation options can correctly generate a multi-threaded logging library

### ISSUE THREAD

**Issue by jeffreycsj** [log4cplus/log4cplus#591]
my compilation options : ./configure --prefix=/home/jeffreychen/log4cplus_multithread --enable-static --enable-threads=yes CXXFLAGS=-std=c++11 --disable-thread-pool
If I didn't use '--disable-thread-pool', it would fork a child process.I don't want that.
So I add '--disable-thread-pool', but if I use that,the library always dump.

**Comment by wilx** [comment]
What version of the library, what OS, what platform? If you get SIGSEGV then try to run it under a debugger to obtain a call stack.

**Comment by jeffreycsj** [comment]
version:log4cplus-2.0.8
linux centos

**Comment by jeffreycsj** [comment]
Function stack frames have been destroyed，so can't see the problem.But If I comment out the log output,it didn't dump.

**Comment by wilx** [comment]
It is impossible for me to help here. You will have to debug this yourself. I don't see an issue with the configure script parameters. Have you tried to run `make check`, does it succeed?

**Comment by jeffreycsj** [comment]
make check doesn't wrong,ok,I will figure out that. Thx for your time.Appreciate!
