### ISSUE TITLE
Question: Which latest version of Log4cplus I should use on RedHat 7.9 with DevToolset11-toolchain (  GCC 11.2 ) compiler 

### ISSUE THREAD

**Issue by Sonalsr28** [log4cplus/log4cplus#605]
Hi,

My application need to be ported and recompiled on Red Hat 7.9 Linux with DevToolSet-11-Toolchain ( GCC 11.2 , Std=C++17 ) version which uses Log4cplus.  
Pls let me know which is the latest version of log4cplus compatible for this system requirements ? 

Thanks for help!

**Comment by wilx** [comment]
Any released version should work.

**Comment by Sonalsr28** [comment]
Thanks for your response.  

1. If you can refer to specific version then it would be great. 
2. Currently I have option for  log4cplus 1.1.3 as it is showing under EPEL package for RHEL 7. Does this version support C++17 std ? 
3. I can use this version installed through EPEL 7 RPM (log4cplus-1.1.3-0.4.rc3.el7.x86_64.rpm )  instead of compiling on RHEL7 platform. But RPM does not comes with static library ( .a) , so need to compile the source code.  
Also, Static RPM does not comes with this version which provides static libs. Considering this , Do I need to compile the source code for log4cplus 1.1.3 with std=C++17 flag  or just compiling with gcc 11.2 should be ok ?  as I am getting warnings related to  auto_ptr class  deprecated in  c++17.  How to ensure C++17 compatibility so that no run time issues are there 
4. If Yes, How to add std=C++17 flag during compilation of log4clus ?
Thanks.

**Comment by wilx** [comment]
The 1.1.3 version does not support C++17 explicitly. It supports C++11. It might work with C++17 but I have not tested that. If you are going to compile from sources anyway, I would suggest using the latest version.

**Comment by wilx** [comment]
I am guessing using different -std=c++XY should not matter much as long as you use the same version of GCC for all of the objects that linked together. (https://stackoverflow.com/questions/46746878/is-it-safe-to-link-c17-c14-and-c11-objects)

**Comment by wilx** [comment]
As for the flags, `./configure CXXFLAGS="-std=c++17"` should work, I think.

**Comment by Sonalsr28** [comment]
> The 1.1.3 version does not support C++17 explicitly. It supports C++11. It might work with C++17 but I have not tested that. If you are going to compile from sources anyway, I would suggest using the latest version.

Hi,   So which one is better approach in my case -- 

1. Using any version with 2.x  series having C++17 support . In that case which version in 2.x series is the latest to support C++17 standards  ?   OR
2.  using 1.1.3 version compiled with same GCC compiler ( 11.2) and ignoring C+17 standard as it does not support and do not impact compatibility though as per stackoverflow link shared ?  OR

Thanks

**Comment by Sonalsr28** [comment]
One question is related to Log4Cplus RPM ((log4cplus-1.1.3-0.4.rc3.el7.x86_64.rpm ) distributed with EPEL RHEL 7 : 

This RPM will installed Log4cplus Dynamic Libs ( .so) and may be  ( I am not sure ) compiled with default GCC compiler GCC 4.8.5 for RHEL 7. 
Since my Application going to be compiled on RHEL 7 but using Devtoolset-11 GCC 11.2 package , here GCC compiler are different.  I have tried compiled my application by using Log4Cplus dynamic library from this RPM and it is compiled but I am not sure of Runtime errors as of now. Will this ensure compatiblity ?    Hence wanted to make sure no compatibility issues at later stage wrt of Log4Cplus ?

Thankyou
