### ISSUE TITLE
Include Headers Possibly Causing Build Error

### ISSUE THREAD

**Issue by stefankiesz** [log4cplus/log4cplus#610]
Hi, I'm getting the following build error when running `cmake`:
```
src/log4judpappender.cxx:49:15: error: no member named 'iswcntrl' in namespace 'std'; did you mean simply 'iswcntrl'?
    return !! std::iswcntrl (std::char_traits<tchar>::to_int_type (ch));
              ^~~~~~~~~~~~~
              iswcntrl
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_wctype.h:63:1: note: 'iswcntrl' declared here
iswcntrl(wint_t _wc)
```
The header which includes `iswcntrl` is `<cwctype>`.

I'm wondering if it may be due to the **log4judpappender.cxx** file including the 3rd-party header `<log4cplus/helpers/property.h>` prior to the `<cwctype>` standard library header [here](https://github.com/log4cplus/log4cplus/blob/dcae948cefe54707370e9da04c2858fab808e28d/src/log4judpappender.cxx#L31C1-L35), but the **property.cxx** file including `<cwctype>` prior to `<log4cplus/helpers/property.h>` [here](https://github.com/log4cplus/log4cplus/blob/dcae948cefe54707370e9da04c2858fab808e28d/src/property.cxx#L24-L28).

 - log4cplus version: 2.0.6
 - Intel Mac OS 12.7.3
 - compiler: AppleClang 14

**Comment by wilx** [comment]
It seems to work fine with some version of Mac OS X and XCode: <https://github.com/log4cplus/log4cplus/blob/2.1.x/.github/workflows/c-cpp.yml>
Are you able to update your XCode/Clang?

**Comment by wilx** [comment]
The successful Mac OS X build: https://github.com/log4cplus/log4cplus/actions/runs/7848553892/job/21419941036

**Comment by stefankiesz** [comment]
@wilx thanks for the response. I'm only seeing it with that particular OS X 12 version - it works on OS X 14, have not tested 13. Would it be possible for you to run a similar check with the github actions OS set to macos-latest? That should pull it down to 12.x

**Comment by wilx** [comment]
@stefankiesz It seems to compile with older XCode as well: https://github.com/log4cplus/log4cplus/actions/runs/7850635594/job/21426379073

**Comment by stefankiesz** [comment]
Ah, thanks for the confirmation, will keep looking into how our build configurations could be causing this.
