### ISSUE TITLE
'LOG4CXX_ASSERT' equivalent

### ISSUE THREAD

**Issue by diverger** [log4cplus/log4cplus#617]
Are there any functions like what in log4cxx:

LOG4CXX_ASSERT(logger, condition, message)
LOG4CXX_ASSERT_FMT(logger, condition, fmt, ...)

**Comment by wilx** [comment]
There is [`LOG4CPLUS_ASSERT(logger, cond)`](https://log4cplus.github.io/log4cplus/docs/log4cplus-2.1.0/doxygen/loggingmacros_8h.html#a1de586715dc7a01bf8c2574d845aa70e). It should print the condition source.

**Comment by diverger** [comment]
> There is [`LOG4CPLUS_ASSERT(logger, cond)`](https://log4cplus.github.io/log4cplus/docs/log4cplus-2.1.0/doxygen/loggingmacros_8h.html#a1de586715dc7a01bf8c2574d845aa70e). It should print the condition source.

Yes, but it won't accept extra messages or formatted messages. :)
