### ISSUE TITLE
Feature request: non-blocking logging with SyslogAppender

### ISSUE THREAD

**Issue by vcill** [log4cplus/log4cplus#624]
- We use SyslogAppender (async) in our application to forward logs to remote syslog server
- When the disk on syslog server becomes full the syslog server stops accepting new logs
- This leads to the internal log4cplus queue becoming full and then every log attempt becomes blocking which freezes the entire application

Q: Would it be possible to make log4cplus simply discard the message in this case instead of blocking?

Rationale: It's better to lose some logs than to lose the whole application

Maybe this can be done simply by setting the syslogSocket to non-blocking mode and handling the EWOULDBLOCK error? 

EDIT: this is our full syslog appender config:
```
log4cplus.appender.syslog=log4cplus::SysLogAppender
log4cplus.appender.syslog.layout=log4cplus::PatternLayout
log4cplus.appender.syslog.layout.ConversionPattern=%D{%Y-%m-%dT%H:%M:%S.%Q} [%T] <%x> %c %-5p %m%n
log4cplus.appender.syslog.ident=vas-proxy
log4cplus.appender.syslog.host=10.10.10.10
log4cplus.appender.syslog.udp=false
log4cplus.appender.syslog.port=5519
log4cplus.appender.syslog.facility=user
log4cplus.appender.syslog.AsyncAppend=true
```

**Comment by wilx** [comment]
When you say "We use SyslogAppender (async)", what do you mean exactly? Do you use the async property? Or do you wrap the entire SyslogAppender into AsyncAppender?

**Comment by wilx** [comment]
One thing that comes to mind is that you could switch from TCP to UDP, assuming your remote syslog server can accept on UDP port.

**Comment by vcill** [comment]
Hi, thanks for the reply. This is what I meant by async:
`log4cplus.appender.syslog.AsyncAppend=true`

We have been using UDP for quite some time but under heavy load we are losing a lot of logs (even if there is plenty of disk space available on the syslog server). I tried increasing the buffer sizes on the syslog side but this just delays the issue but eventually the data loss occurs. With TCP and flow-control on the syslog side there is never a data loss (Except for the case when there's no space left on the syslog server, in which case the data loss is acceptable) so that's why we want to swtich to TCP.

**Comment by wilx** [comment]
I have committed changes that allow you to change the behaviour of the thread pool queue. (https://github.com/log4cplus/log4cplus/compare/11adfe784da442ac23903ff313126dfa4235d451...2.1.x?expand=1)

Now, on 2.1.x branch and on master branch, you can either configure the global property `log4cplus.threadPoolBlockOnFull=false` or call `log4cplus::setThreadPoolBlockOnFull(false)` to disable the blocking behaviour. Any logging event that would block will be silently dropped.

**Comment by wilx** [comment]
I have added some logging in 490122a4a7b961b838059bde2de090600ea8ff9b.
