### ISSUE TITLE
How do I enable lto in the cmake build system for log4cpp?

### ISSUE THREAD

**Issue by jdmdmm** [log4cplus/log4cplus#641]
Quick question:
How do I enable lto in the cmake build system for log4cpp? I see there's an ac option but I can't see a cmake one

Also is there a way to specify optimisation level 3 (-O3)?

**Comment by wilx** [comment]
I have changed the CMake build to enable the LTO / IPO for the Release build type. 

You can choose the type of the build with [`CMAKE_BUILD_TYPE`](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html). `-O3` is used for the `Release` build type.
