### ISSUE TITLE
can not compile over in vs2013

### ISSUE THREAD

**Issue by Solaris-wj** [log4cplus/log4cplus#72]
vs 2013 does not support constexpr, can you fix this? I think the constexpr isn't necessary.

**Comment by wilx** [comment]
I committed a merge https://github.com/log4cplus/log4cplus/commit/0e437ed87ac6f6e837ea5916c9547f50f25e5459. It removes the uses of `constexpr`. Please test it, I do not have access to VS 2013 right now.

**Comment by Solaris-wj** [comment]
Thank you.
It works without constexpr. 
I found another issue. The following simple code does not work in vs2013 but it works find in linux.

    int main()
    {
        BasicConfigurator config;
       config.configure();
       Logger logger = Logger::getInstance("mylogger");
       LOG4CPLUS_WARN(logger, "Hello, World!");
    }

The program crashed when leave main function. I'll look into it.

By the way, I wonder where can I find some examples of correctly usage of log4cplus, as the website of sourceforge.net doesn't has examples.

**Comment by wilx** [comment]
Master is a work in progress. You are likely hitting issues MSVC has with destroying C++11 threads and synchronization primitives after `main() ` exits. To fix this, include new header `initializer.h`. From there, instantiate `Initializer` class on top of `main()`. It will do initialization and shutdown properly. If you have problems even after doing this, please report it.

**Comment by wilx** [comment]
There are some examples linked on the SourceForge wiki. Also, take a look at the tests in the source.

**Comment by joseAndresGomezTovar** [comment]
Hi, I´m trying to compile with vs2013 express. Do you know where are the files catch.hpp and ThreadPool.h? thank you in advance

**Comment by Solaris-wj** [comment]
catch.hpp may be used for test, so it's not necessary.
ThreadPool.h is a sub repo of log4cpp, may be you need clone log4cpp recursively, or download it by hand,

**Comment by joseAndresGomezTovar** [comment]
Ok, for now I will try with the log4cplus-REL_1_1_3-RC4.

I propose you to change in the x.vcxproj 
in This line

`
<PlatformToolset>v140</PlatformToolset>
`

to this another three lines

`
<PlatformToolset Condition="'$(VisualStudioVersion)'=='11.0'">v110</PlatformToolset>
<PlatformToolset Condition="'$(VisualStudioVersion)'=='12.0'">v120</PlatformToolset>
<PlatformToolset Condition="'$(VisualStudioVersion)'=='14.0'">v140</PlatformToolset>
`
To have vs2012 and vs2013 support.

**Comment by wilx** [comment]
Catch is a unit testing framework. It is included in log4cplus as a Git submodule. Make sure you run the appropriate `git submodule` command.

**Comment by wilx** [comment]
I am closing this as fixed.
