### ISSUE TITLE
hourly log delayed

### ISSUE THREAD

**Issue by lwmonster** [log4cplus/log4cplus#92]
After my service running for a month, I found  the hourly output log was delayed; 
My setting:
~~~~
log4cplus.appender.UI=log4cplus::DailyRollingFileAppender
log4cplus.appender.UI.Schedule=HOURLY
~~~~

and the hourly logs are generated at 26 minites of every hour
eg.  with commend [ls -l] I get this:
~~~
-rw-r--r-- 1 resys resys  698763 6月  25 09:26 client_running.log.2015-06-25-08
~~~

client_running.log.2015-06-25-08 was generated at 09:26

**Comment by wilx** [comment]
The file rolling is only done when a logging event is logged. There is no independent timer to roll the files. This is definitely something that could be improved.

**Comment by lwmonster** [comment]
@wilx  It seems not this reason,  my server print out log 3 or 4 times every second.  And once one log file was delayed, the following logs will be delayed too. eg.
-rw-r--r-- 1 resys resys  622301 7月   6 00:02 client_running.log.2015-07-05-23
-rw-r--r-- 1 resys resys  631277 7月   6 01:02 client_running.log.2015-07-06-00
-rw-r--r-- 1 resys resys  643454 7月   6 02:02 client_running.log.2015-07-06-01
-rw-r--r-- 1 resys resys  651104 7月   6 03:02 client_running.log.2015-07-06-02
-rw-r--r-- 1 resys resys  629211 7月   6 04:02 client_running.log.2015-07-06-03
-rw-r--r-- 1 resys resys  633569 7月   6 05:02 client_running.log.2015-07-06-04
-rw-r--r-- 1 resys resys  619077 7月   6 06:02 client_running.log.2015-07-06-05
-rw-r--r-- 1 resys resys  655482 7月   6 07:02 client_running.log.2015-07-06-06
-rw-r--r-- 1 resys resys  726445 7月   6 08:02 client_running.log.2015-07-06-07
-rw-r--r-- 1 resys resys  723866 7月   6 09:02 client_running.log.2015-07-06-08
-rw-r--r-- 1 resys resys  706012 7月   6 10:02 client_running.log.2015-07-06-09
-rw-r--r-- 1 resys resys  907280 7月   6 11:02 client_running.log.2015-07-06-10
-rw-r--r-- 1 resys resys  922084 7月   6 12:02 client_running.log.2015-07-06-11
-rw-r--r-- 1 resys resys  925613 7月   6 13:02 client_running.log.2015-07-06-12
-rw-r--r-- 1 resys resys  983667 7月   6 14:02 client_running.log.2015-07-06-13

**Comment by wilx** [comment]
Check the logged events time stamp in the files against the `ctime` of the file that you see from `ls -l`. If they are the same, then everything works as intended.

**Comment by lwmonster** [comment]
@wilx   
The logged events time stamp is delayed too. see client_running.log.2015-07-06-14:
INFO 2015-07-06 15:02:23.116 [client/UserItemClient.cpp:107] "UserItemClient::Run Get users finish, number:1 start time:1436166139695 newest time:1436166139695"
INFO 2015-07-06 15:02:24.118 [client/UserItemClient.cpp:107] "UserItemClient::Run Get users finish, number:1 start time:1436166139695 newest time:1436166139695"
INFO 2015-07-06 15:02:25.120 [client/UserItemClient.cpp:107] "UserItemClient::Run Get users finish, number:1 start time:1436166139695 newest time:1436166139695"
INFO 2015-07-06 15:02:26.134 [client/UserItemClient.cpp:107] "UserItemClient::Run Get users finish, number:1 start time:1436166139695 newest time:1436166139695"

The logged events of 15:02:23 was output to 【client_running.log.2015-07-06-14】

**Comment by lwmonster** [comment]
And at the first few days of my server started, it works good; But actually, it was delayed slowly, like a lost time watch

**Comment by lwmonster** [comment]
see log of 2015-06-27-00:  client_running.log.2015-06-27-00, the last logged event is:
~~~~INFO 2015-06-27 01:00:07.366 [client/UserItemClient.cpp:107] "UserItemClient::Run Get users finish, number:1 start time:1435337979101 newest time:1435337979101"~~~~

see log of 2015-06-30-00: client_running.log.2015-06-30-00, the last logged event is:
~~~~INFO 2015-06-30 01:00:54.116 [client/UserItemClient.cpp:107] "UserItemClient::Run Get users finish, number:1 start time:1435597253699 newest time:1435597253699"~~~~

see log of 2015-07-02-00: client_running.log.2015-07-02-00, the last logged event is:
~~~~INFO 2015-07-02 01:01:23.117 [client/UserItemClient.cpp:107] "UserItemClient::Run Get users finish, number:1 start time:1435770012435 newest time:1435770012435"~~~~

Time 01:00:07.366 ->  01:00:54.116 ->  01:01:23.117 
The time was later and later, and some day, the logs will be delayed more than one hour

**Comment by wilx** [comment]
@lwmonster : Please test the branch (based on 1.2.x branch) linked above. I think this might fix the issue. I think the rollover time was getting skewed due to `now` time not getting rounded to whole minutes.

**Comment by wilx** [comment]
I have pushed another change to the branch which should fix the issue for other schedules as well.

**Comment by lwmonster** [comment]
ok, thank you, I will have a try ~  
Thank you ~

**Comment by lwmonster** [comment]
I didn't upgrade it to 1.2.x, I just added the code of [bug #92](https://github.com/wilx/log4cplus/commit/b114cc48f67afb7b526f4a55cf5d7fb120cd7bd7) and it works; thank you very much~

**Comment by wilx** [comment]
Cool. I will apply to other branches as well.

**Comment by lwmonster** [comment]
Cool! (graphics/emojis/thumbsup.png)
