### ISSUE TITLE
Remove change of CMake target names

### ISSUE THREAD

**Issue by robiwano** [log4cplus/log4cplus#98]
Running cmake on different platforms yields different targets, log4cplusS on Unix, and log4cplusSU on Windows f.i. This makes it hard for dependent targets, since TARGET_LINK_LIBRARIES must take this into account. I see no reason why the target cannot be simply called 'log4cplus', since there is only one target produced.

**Comment by wilx** [comment]
I want to keep having the distinct names for builds with distinct properties (shared/static library and char/wchar_t builds). However, I have added an option to the CMake build system to allow you to turn it off.

**Comment by robiwano** [comment]
Thank you, that will be perfect!

**Comment by robiwano** [comment]
Btw, which branch is this change on ?

**Comment by wilx** [comment]
It is now both on master and 1.2.x branches in my personal repository. I will merge to log4cplus/log4cplus soon.

**Comment by robiwano** [comment]
Thanks!

**Comment by robiwano** [comment]
CMake tip: Use TARGET_INCLUDE_DIRECTORIES and TARGET_COMPILE_DEFINITIONS to specify include dirs and compile defs. This way a dependent target (via TARGET_LINK_LIBRARIES) will automatically have its include dirs and compile defs set to the PUBLIC values as defined in log4cplus. This is a fantastic CMake feature.
